//! Hash Aggregate Executor
//!
//! Implements hash-based aggregation with support for GROUP BY and aggregate functions.
//!
//! Algorithm:
//! 1. Build hash table: group key → accumulators
//! 2. For each input row:
//!    - Evaluate GROUP BY expressions to compute group key
//!    - Update accumulators for this group
//! 3. Finalize: convert accumulators to output rows

use super::eval::eval_expr;
use super::executor::{ExecutionContext, ExecutionError, Row, RowStream};
use super::operators::PhysicalPlan;
use super::window::compare::compare_literals;
use futures::stream::{self, StreamExt};
use indexmap::IndexMap;
use raisin_models::nodes::properties::PropertyValue;
use raisin_sql::analyzer::{Literal, TypedExpr};
use raisin_sql::logical_plan::{AggregateExpr, AggregateFunction};
use raisin_storage::Storage;
use std::collections::HashMap;
use std::collections::HashSet;

/// Execute a hash aggregate operation
pub async fn execute_hash_aggregate<
    S: Storage + raisin_storage::transactional::TransactionalStorage + 'static,
>(
    plan: &PhysicalPlan,
    ctx: &ExecutionContext<S>,
) -> Result<RowStream, ExecutionError> {
    let (input, group_by, aggregates) = match plan {
        PhysicalPlan::HashAggregate {
            input,
            group_by,
            aggregates,
        } => (input, group_by, aggregates),
        _ => {
            return Err(ExecutionError::Backend(
                "Invalid plan passed to execute_hash_aggregate".to_string(),
            ))
        }
    };

    // Execute input
    let input_stream = super::executor::execute_plan(input.as_ref(), ctx).await?;

    // Materialize all input rows and build aggregation hash table
    // Store both the group key and the actual PropertyValues for GROUP BY columns
    let mut groups: HashMap<GroupKey, (Vec<PropertyValue>, Vec<Accumulator>)> = HashMap::new();

    let input_rows: Vec<_> = input_stream.collect().await;
    for row_result in input_rows {
        let row = row_result?;

        // Evaluate GROUP BY expressions to get group key and values
        let (group_key, group_values) = evaluate_group_key(group_by, &row)?;

        // Get or create accumulators for this group
        let (stored_values, accumulators) = groups.entry(group_key.clone()).or_insert_with(|| {
            let new_accumulators = aggregates.iter().map(Accumulator::new).collect();
            (group_values.clone(), new_accumulators)
        });

        // Update each accumulator with values from this row
        for (i, agg_expr) in aggregates.iter().enumerate() {
            // Check FILTER clause if present
            let should_include = if let Some(filter_expr) = &agg_expr.filter {
                let filter_result = eval_expr(filter_expr, &row)?;
                match filter_result {
                    Literal::Boolean(true) => true,
                    Literal::Boolean(false) | Literal::Null => false,
                    other => {
                        return Err(ExecutionError::Validation(format!(
                            "FILTER condition must evaluate to BOOLEAN, got {:?}",
                            other
                        )))
                    }
                }
            } else {
                true // No filter, include all rows
            };

            // Only update accumulator if filter passes
            if should_include {
                // Evaluate aggregate argument. COUNT(*) has no argument and
                // counts the row; COUNT(expr) and the others skip NULLs.
                let value = if agg_expr.args.is_empty() {
                    Literal::Int(1)
                } else {
                    eval_expr(&agg_expr.args[0], &row)?
                };
                if !agg_expr.args.is_empty() && matches!(value, Literal::Null) {
                    continue;
                }
                let mut sort_keys = Vec::with_capacity(agg_expr.order_by.len());
                for (key_expr, _) in &agg_expr.order_by {
                    sort_keys.push(eval_expr(key_expr, &row)?);
                }

                accumulators[i].update(value, sort_keys)?;
            }
        }
    }

    // Finalize: convert groups to output rows
    let mut output_rows = Vec::new();
    for (_group_key, (group_values, accumulators)) in groups {
        let mut columns = IndexMap::new();

        // Add GROUP BY columns to output.
        //
        // The column name MUST be the shared canonical group-key name: the
        // logical plan builder rewrites SELECT expressions that match a GROUP
        // BY expression into column references generated by the same function
        // (raisin_sql::logical_plan::group_key_column_name). Any divergence
        // makes the projection above re-evaluate the raw expression against
        // this aggregated row — where the source columns no longer exist —
        // and silently produce NULL group keys.
        for (i, expr) in group_by.iter().enumerate() {
            if i < group_values.len() {
                let col_name = raisin_sql::logical_plan::group_key_column_name(expr);
                tracing::debug!(
                    "HashAggregate: Storing GROUP BY column '{}' with value {:?}",
                    col_name,
                    group_values[i]
                );
                columns.insert(col_name, group_values[i].clone());
            }
        }

        // Add aggregate results
        for (i, accumulator) in accumulators.iter().enumerate() {
            let agg_expr = &aggregates[i];
            let result = accumulator.finalize()?;

            // Store with the user-provided alias
            columns.insert(agg_expr.alias.clone(), result.clone());

            // Also store with canonical name for lookup during projection evaluation
            let canonical_name = generate_canonical_aggregate_name(agg_expr);
            tracing::debug!(
                "HashAggregate: Storing aggregate '{}' (canonical: '{}') with value {:?}",
                agg_expr.alias,
                canonical_name,
                result
            );
            columns.insert(canonical_name, result);
        }

        output_rows.push(Row::from_map(columns));
    }

    // Convert to stream
    Ok(Box::pin(stream::iter(output_rows.into_iter().map(Ok))))
}

/// Group key for hash aggregation
/// We use a wrapper around PropertyValue strings for hashing
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
struct GroupKey {
    values: Vec<String>,
}

/// Evaluate GROUP BY expressions to compute group key and values
fn evaluate_group_key(
    group_by: &[TypedExpr],
    row: &Row,
) -> Result<(GroupKey, Vec<PropertyValue>), ExecutionError> {
    let mut key_strings = Vec::new();
    let mut prop_values = Vec::new();

    for expr in group_by {
        let literal = eval_expr(expr, row)?;
        // Convert to string for hashing
        let key_string = format!("{:?}", literal);
        key_strings.push(key_string);

        // Also store the PropertyValue for output
        let prop_value = literal_to_property_value(literal)?;
        prop_values.push(prop_value);
    }

    Ok((
        GroupKey {
            values: key_strings,
        },
        prop_values,
    ))
}

/// Convert Literal to PropertyValue
fn literal_to_property_value(lit: Literal) -> Result<PropertyValue, ExecutionError> {
    use super::types::to_property_value;
    to_property_value(&lit).map_err(ExecutionError::Backend)
}

/// Generate canonical name for aggregate function result
/// Must match the logic in eval.rs generate_function_column_name
fn generate_canonical_aggregate_name(agg_expr: &AggregateExpr) -> String {
    use raisin_sql::analyzer::Expr;
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};

    let base = match agg_expr.func {
        AggregateFunction::Count => "COUNT",
        AggregateFunction::CountDistinct => "COUNT",
        AggregateFunction::Sum => "SUM",
        AggregateFunction::Avg => "AVG",
        AggregateFunction::Min => "MIN",
        AggregateFunction::Max => "MAX",
        AggregateFunction::ArrayAgg => "ARRAY_AGG",
    };
    // The projection still holds the analyzer's `Expr::Function`, whose name
    // carries DISTINCT / ORDER BY modifiers and whose argument list includes
    // the ORDER BY keys — reproduce both so the lookup name matches.
    let func_name_upper = raisin_sql::analyzer::aggregate_spec::AggregateSpec {
        base: base.to_string(),
        distinct: agg_expr.distinct,
        order_desc: agg_expr.order_by.iter().map(|(_, d)| *d).collect(),
    }
    .encode();
    let total_args = agg_expr.args.len() + agg_expr.order_by.len();

    // Generate base name matching eval.rs format: FUNCTION_NAME(arg) or FUNCTION_NAME()
    let base_name = if total_args == 0 {
        // No arguments (e.g., COUNT(*) which is represented as empty args in some contexts)
        format!("{}()", func_name_upper)
    } else if total_args == 1 {
        // Single argument - extract argument name
        let arg_name = match &agg_expr.args[0].expr {
            Expr::Column { table, column } => format!("{}.{}", table, column),
            _ => "...".to_string(),
        };
        format!("{}({})", func_name_upper, arg_name)
    } else {
        // Multiple arguments
        format!("{}(...)", func_name_upper)
    };

    // Include FILTER clause in canonical name to distinguish filtered aggregates
    if let Some(ref filter) = agg_expr.filter {
        // Hash the filter expression to create a unique suffix
        let mut hasher = DefaultHasher::new();
        format!("{:?}", filter).hash(&mut hasher);
        let filter_hash = hasher.finish();
        format!("{}_filter_{:x}", base_name, filter_hash)
    } else {
        base_name
    }
}

/// Accumulator for aggregate functions
///
/// NULL inputs never reach an accumulator (the caller skips them for every
/// function except `COUNT(*)`), so each variant only has to fold real values.
#[derive(Debug, Clone)]
enum Accumulator {
    Count {
        count: usize,
    },
    CountDistinct {
        seen: HashSet<String>,
    },
    Sum {
        sum: f64,
        has_value: bool,
    },
    Avg {
        sum: f64,
        count: usize,
    },
    Min {
        min: Option<Literal>,
    },
    Max {
        max: Option<Literal>,
    },
    ArrayAgg {
        /// `(value, inner ORDER BY keys, DESC flags)` in arrival order
        values: Vec<(Literal, Vec<Literal>)>,
        order_desc: Vec<bool>,
        distinct: bool,
    },
}

impl Accumulator {
    /// Create new accumulator for the given aggregate expression
    fn new(agg: &AggregateExpr) -> Self {
        match agg.func {
            AggregateFunction::Count => Accumulator::Count { count: 0 },
            AggregateFunction::CountDistinct => Accumulator::CountDistinct {
                seen: HashSet::new(),
            },
            AggregateFunction::Sum => Accumulator::Sum {
                sum: 0.0,
                has_value: false,
            },
            AggregateFunction::Avg => Accumulator::Avg { sum: 0.0, count: 0 },
            AggregateFunction::Min => Accumulator::Min { min: None },
            AggregateFunction::Max => Accumulator::Max { max: None },
            AggregateFunction::ArrayAgg => Accumulator::ArrayAgg {
                values: Vec::new(),
                order_desc: agg.order_by.iter().map(|(_, d)| *d).collect(),
                distinct: agg.distinct,
            },
        }
    }

    /// Update accumulator with a new (non-NULL) value
    fn update(&mut self, value: Literal, sort_keys: Vec<Literal>) -> Result<(), ExecutionError> {
        match self {
            Accumulator::Count { count } => {
                *count += 1;
            }
            Accumulator::CountDistinct { seen } => {
                seen.insert(format!("{:?}", value));
            }
            Accumulator::Sum { sum, has_value } => {
                if let Some(num) = extract_number(&value) {
                    *sum += num;
                    *has_value = true;
                }
            }
            Accumulator::Avg { sum, count } => {
                if let Some(num) = extract_number(&value) {
                    *sum += num;
                    *count += 1;
                }
            }
            Accumulator::Min { min } => {
                let smaller = match min {
                    Some(current) => compare_literals(&value, current) == std::cmp::Ordering::Less,
                    None => true,
                };
                if smaller {
                    *min = Some(value);
                }
            }
            Accumulator::Max { max } => {
                let larger = match max {
                    Some(current) => {
                        compare_literals(&value, current) == std::cmp::Ordering::Greater
                    }
                    None => true,
                };
                if larger {
                    *max = Some(value);
                }
            }
            Accumulator::ArrayAgg { values, .. } => {
                values.push((value, sort_keys));
            }
        }
        Ok(())
    }

    /// Finalize accumulator and return result
    fn finalize(&self) -> Result<PropertyValue, ExecutionError> {
        match self {
            Accumulator::Count { count } => Ok(PropertyValue::Integer(*count as i64)),
            Accumulator::CountDistinct { seen } => Ok(PropertyValue::Integer(seen.len() as i64)),
            Accumulator::Sum { sum, has_value } => {
                // Return 0 if no values, following PostgreSQL behavior
                Ok(PropertyValue::Float(if *has_value { *sum } else { 0.0 }))
            }
            Accumulator::Avg { sum, count } => {
                // Return 0 if no values
                if *count > 0 {
                    Ok(PropertyValue::Float(sum / (*count as f64)))
                } else {
                    Ok(PropertyValue::Float(0.0))
                }
            }
            // No non-NULL input: NULL, as in PostgreSQL
            Accumulator::Min { min } => {
                literal_to_property_value(min.clone().unwrap_or(Literal::Null))
            }
            Accumulator::Max { max } => {
                literal_to_property_value(max.clone().unwrap_or(Literal::Null))
            }
            Accumulator::ArrayAgg {
                values,
                order_desc,
                distinct,
            } => {
                let mut items: Vec<(Literal, Vec<Literal>)> = values.clone();
                if !order_desc.is_empty() {
                    items.sort_by(|a, b| {
                        for (i, desc) in order_desc.iter().enumerate() {
                            let c = compare_literals(&a.1[i], &b.1[i]);
                            if c != std::cmp::Ordering::Equal {
                                return if *desc { c.reverse() } else { c };
                            }
                        }
                        std::cmp::Ordering::Equal
                    });
                }
                let mut out = Vec::with_capacity(items.len());
                let mut seen = HashSet::new();
                for (value, _) in items {
                    if *distinct && !seen.insert(format!("{:?}", value)) {
                        continue;
                    }
                    out.push(literal_to_property_value(value)?);
                }
                Ok(PropertyValue::Array(out))
            }
        }
    }
}

/// Extract numeric value from literal
fn extract_number(lit: &Literal) -> Option<f64> {
    match lit {
        Literal::Int(i) => Some(*i as f64),
        Literal::BigInt(i) => Some(*i as f64),
        Literal::Double(f) => Some(*f),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use raisin_sql::analyzer::DataType;

    fn agg(func: AggregateFunction) -> AggregateExpr {
        AggregateExpr {
            func,
            args: vec![],
            alias: "a".into(),
            return_type: DataType::Unknown,
            filter: None,
            distinct: false,
            order_by: vec![],
        }
    }

    #[test]
    fn test_count_accumulator() {
        let mut acc = Accumulator::new(&agg(AggregateFunction::Count));
        for v in [1, 2, 3] {
            acc.update(Literal::Int(v), vec![]).unwrap();
        }
        assert_eq!(acc.finalize().unwrap(), PropertyValue::Integer(3));
    }

    #[test]
    fn count_distinct_counts_unique_values() {
        let mut acc = Accumulator::new(&agg(AggregateFunction::CountDistinct));
        for v in ["a", "b", "a", "a"] {
            acc.update(Literal::Text(v.into()), vec![]).unwrap();
        }
        assert_eq!(acc.finalize().unwrap(), PropertyValue::Integer(2));
    }

    #[test]
    fn test_sum_accumulator() {
        let mut acc = Accumulator::new(&agg(AggregateFunction::Sum));
        for v in [1, 2, 3] {
            acc.update(Literal::Int(v), vec![]).unwrap();
        }
        assert_eq!(acc.finalize().unwrap(), PropertyValue::Float(6.0));
    }

    #[test]
    fn test_avg_accumulator() {
        let mut acc = Accumulator::new(&agg(AggregateFunction::Avg));
        for v in [1, 2, 3] {
            acc.update(Literal::Int(v), vec![]).unwrap();
        }
        assert_eq!(acc.finalize().unwrap(), PropertyValue::Float(2.0));
    }

    #[test]
    fn min_max_compare_numerically_and_return_null_when_empty() {
        // 101 < 42 lexicographically; the accumulators must compare as numbers
        let mut mn = Accumulator::new(&agg(AggregateFunction::Min));
        let mut mx = Accumulator::new(&agg(AggregateFunction::Max));
        for v in [101, 42, 8] {
            mn.update(Literal::Int(v), vec![]).unwrap();
            mx.update(Literal::Int(v), vec![]).unwrap();
        }
        assert_eq!(mn.finalize().unwrap(), PropertyValue::Integer(8));
        assert_eq!(mx.finalize().unwrap(), PropertyValue::Integer(101));

        let empty = Accumulator::new(&agg(AggregateFunction::Max));
        assert_eq!(empty.finalize().unwrap(), PropertyValue::Null);
    }

    #[test]
    fn test_array_agg_accumulator() {
        let mut acc = Accumulator::new(&agg(AggregateFunction::ArrayAgg));
        for v in ["a", "b", "c"] {
            acc.update(Literal::Text(v.into()), vec![]).unwrap();
        }
        match acc.finalize().unwrap() {
            PropertyValue::Array(arr) => {
                assert_eq!(arr.len(), 3);
                assert_eq!(arr[0], PropertyValue::String("a".to_string()));
                assert_eq!(arr[2], PropertyValue::String("c".to_string()));
            }
            _ => panic!("Expected array"),
        }
    }

    #[test]
    fn array_agg_honours_distinct_and_order_by() {
        let mut spec = agg(AggregateFunction::ArrayAgg);
        spec.distinct = true;
        spec.order_by = vec![(
            raisin_sql::analyzer::TypedExpr::column("t".into(), "k".into(), DataType::Int),
            true,
        )];
        let mut acc = Accumulator::new(&spec);
        // (value, sort key): sorted DESC by key, duplicates removed
        for (v, k) in [("b", 2), ("a", 1), ("c", 3), ("a", 5)] {
            acc.update(Literal::Text(v.into()), vec![Literal::Int(k)])
                .unwrap();
        }
        let arr = match acc.finalize().unwrap() {
            PropertyValue::Array(arr) => arr,
            _ => panic!("Expected array"),
        };
        let names: Vec<String> = arr
            .into_iter()
            .map(|p| match p {
                PropertyValue::String(s) => s,
                other => panic!("unexpected {:?}", other),
            })
            .collect();
        assert_eq!(names, vec!["a", "c", "b"]);
    }
}
