/**
 * WebSocket protocol definitions for RaisinDB
 *
 * This module defines TypeScript interfaces matching the Rust protocol.
 * All messages are serialized using MessagePack for efficiency.
 */

import { encode, decode } from '@msgpack/msgpack';

// ============================================================================
// Core Envelope Types
// ============================================================================

/**
 * Request envelope wrapping all client-to-server messages
 */
export interface RequestEnvelope {
  /** Unique identifier for this request (generated by client) */
  request_id: string;
  /** Type of request */
  type: RequestType;
  /** Request context (tenant, repository, workspace) */
  context: RequestContext;
  /** Request-specific payload */
  payload: unknown;
}

/**
 * Response envelope wrapping all server-to-client messages
 */
export interface ResponseEnvelope {
  /** Request ID this response corresponds to */
  request_id: string;
  /** Response status */
  status: ResponseStatus;
  /** Response data (if successful) */
  result?: unknown;
  /** Error information (if failed) */
  error?: ErrorInfo;
  /** Metadata for streaming responses */
  metadata?: ResponseMetadata;
}

/**
 * Event message for server-initiated events (subscriptions)
 */
export interface EventMessage {
  /** Unique event ID */
  event_id: string;
  /** Subscription ID this event belongs to */
  subscription_id: string;
  /** Event type */
  event_type: string;
  /** Event payload */
  payload: unknown;
  /** Timestamp of the event (ISO 8601 string) */
  timestamp: string;
}

/**
 * Connected message sent by server on WebSocket connection
 * Includes anonymous token for HTTP API calls when anonymous access is enabled
 */
export interface ConnectedMessage {
  /** Message type identifier */
  type: 'connected';
  /** Connection ID assigned by server */
  connection_id: string;
  /** Whether this is an anonymous connection */
  anonymous: boolean;
  /** JWT token for HTTP API calls (only for anonymous connections) */
  token?: string;
  /** User ID (for anonymous connections, a generated UUID) */
  user_id?: string;
}

/**
 * Request context containing scope information
 */
export interface RequestContext {
  /** Tenant ID */
  tenant_id: string;
  /** Repository ID (optional for some operations) */
  repository?: string;
  /** Branch name (optional, defaults to "main") */
  branch?: string;
  /** Workspace ID (optional for some operations) */
  workspace?: string;
  /** Revision/commit ID for time-travel queries (optional) */
  revision?: string;
  /** Transaction ID for transactional operations (optional) */
  transaction_id?: string;
}

// ============================================================================
// Enums
// ============================================================================

/**
 * Type of request
 */
export enum RequestType {
  // Authentication
  Authenticate = 'authenticate',
  AuthenticateJwt = 'authenticate_jwt',
  RefreshToken = 'refresh_token',

  // Node operations
  NodeCreate = 'node_create',
  NodeUpdate = 'node_update',
  NodeDelete = 'node_delete',
  NodeGet = 'node_get',
  NodeQuery = 'node_query',
  NodeQueryByPath = 'node_query_by_path',
  NodeQueryByProperty = 'node_query_by_property',

  // Tree operations
  NodeListChildren = 'node_list_children',
  NodeGetTree = 'node_get_tree',
  NodeGetTreeFlat = 'node_get_tree_flat',

  // Node manipulation operations
  NodeMove = 'node_move',
  NodeRename = 'node_rename',
  NodeCopy = 'node_copy',
  NodeCopyTree = 'node_copy_tree',
  NodeReorder = 'node_reorder',
  NodeMoveChildBefore = 'node_move_child_before',
  NodeMoveChildAfter = 'node_move_child_after',

  // Property path operations
  PropertyGet = 'property_get',
  PropertyUpdate = 'property_update',

  // Relationship operations
  RelationAdd = 'relation_add',
  RelationRemove = 'relation_remove',
  RelationsGet = 'relations_get',

  // SQL queries
  SqlQuery = 'sql_query',

  // Workspace operations
  WorkspaceCreate = 'workspace_create',
  WorkspaceGet = 'workspace_get',
  WorkspaceList = 'workspace_list',
  WorkspaceDelete = 'workspace_delete',
  WorkspaceUpdate = 'workspace_update',

  // Branch operations
  BranchCreate = 'branch_create',
  BranchGet = 'branch_get',
  BranchList = 'branch_list',
  BranchDelete = 'branch_delete',
  BranchGetHead = 'branch_get_head',
  BranchUpdateHead = 'branch_update_head',
  BranchMerge = 'branch_merge',
  BranchCompare = 'branch_compare',

  // Tag operations
  TagCreate = 'tag_create',
  TagGet = 'tag_get',
  TagList = 'tag_list',
  TagDelete = 'tag_delete',

  // NodeType operations
  NodeTypeCreate = 'node_type_create',
  NodeTypeGet = 'node_type_get',
  NodeTypeList = 'node_type_list',
  NodeTypeUpdate = 'node_type_update',
  NodeTypeDelete = 'node_type_delete',
  NodeTypePublish = 'node_type_publish',
  NodeTypeUnpublish = 'node_type_unpublish',
  NodeTypeValidate = 'node_type_validate',
  NodeTypeGetResolved = 'node_type_get_resolved',

  // Archetype operations
  ArchetypeCreate = 'archetype_create',
  ArchetypeGet = 'archetype_get',
  ArchetypeList = 'archetype_list',
  ArchetypeUpdate = 'archetype_update',
  ArchetypeDelete = 'archetype_delete',
  ArchetypePublish = 'archetype_publish',
  ArchetypeUnpublish = 'archetype_unpublish',

  // ElementType operations
  ElementTypeCreate = 'element_type_create',
  ElementTypeGet = 'element_type_get',
  ElementTypeList = 'element_type_list',
  ElementTypeUpdate = 'element_type_update',
  ElementTypeDelete = 'element_type_delete',
  ElementTypePublish = 'element_type_publish',
  ElementTypeUnpublish = 'element_type_unpublish',

  // Search operations
  FullTextSearch = 'full_text_search',
  VectorSearch = 'vector_search',

  // Event subscriptions
  Subscribe = 'subscribe',
  Unsubscribe = 'unsubscribe',

  // Repository management
  RepositoryCreate = 'repository_create',
  RepositoryGet = 'repository_get',
  RepositoryList = 'repository_list',
  RepositoryUpdate = 'repository_update',
  RepositoryDelete = 'repository_delete',

  // Audit operations
  AuditQuery = 'audit_query',

  // Binary operations
  BinaryUpload = 'binary_upload',
  BinaryDownload = 'binary_download',

  // Batch operations
  Batch = 'batch',

  // Transaction operations
  TransactionBegin = 'transaction_begin',
  TransactionCommit = 'transaction_commit',
  TransactionRollback = 'transaction_rollback',

  // Flow operations
  FlowRun = 'flow_run',
  FlowResume = 'flow_resume',
  FlowGetInstanceStatus = 'flow_get_instance_status',
  FlowCancel = 'flow_cancel',
  FlowSubscribeEvents = 'flow_subscribe_events',
  FlowUnsubscribeEvents = 'flow_unsubscribe_events',

  // Function operations
  FunctionInvoke = 'function_invoke',
  FunctionInvokeSync = 'function_invoke_sync',
}

/**
 * Response status
 */
export enum ResponseStatus {
  /** Request succeeded, complete result included */
  Success = 'success',
  /** Request failed, error information included */
  Error = 'error',
  /** Streaming response, more chunks to come */
  Streaming = 'streaming',
  /** Final chunk of a streaming response */
  Complete = 'complete',
  /** Request acknowledged, processing asynchronously */
  Acknowledged = 'acknowledged',
}

// ============================================================================
// Error Types
// ============================================================================

/**
 * Error information
 */
export interface ErrorInfo {
  /** Error code */
  code: string;
  /** Human-readable error message */
  message: string;
  /** Additional error details */
  details?: unknown;
}

/**
 * Response metadata for streaming and pagination
 */
export interface ResponseMetadata {
  /** Current chunk number (for streaming) */
  chunk?: number;
  /** Total number of chunks (if known) */
  total_chunks?: number;
  /** Total number of results (for pagination) */
  total?: number;
  /** Has more results available */
  has_more?: boolean;
  /** Credits consumed (for backpressure) */
  credits_consumed?: number;
}

// ============================================================================
// Node Operation Types
// ============================================================================

/**
 * Node data structure
 */
/**
 * A reference to a related node in the graph database
 */
export interface RelationRef {
  /** ID of the target node */
  target: string;
  /** Workspace containing the target node */
  workspace: string;
  /** Node type of the target (for filtering) */
  target_node_type: string;
  /** Semantic relationship type (e.g., "references", "links_to") */
  relation_type: string;
  /** Optional weight for graph algorithms */
  weight?: number;
}

/**
 * An incoming relationship record including the source node metadata
 */
export interface IncomingRelation {
  /** Workspace containing the source node */
  source_workspace: string;
  /** ID of the source node */
  source_node_id: string;
  /** Relationship details pointing to the current node */
  relation: RelationRef;
}

/**
 * Complete incoming/outgoing relationship information for a node
 */
export interface NodeRelationships {
  /** Relationships originating from this node */
  outgoing: RelationRef[];
  /** Relationships targeting this node */
  incoming: IncomingRelation[];
}

/**
 * A content node in RaisinDB's hierarchical structure
 */
export interface Node {
  /** Unique identifier for this node */
  id: string;
  /** Display name of the node (used in URLs and hierarchical paths) */
  name: string;
  /** Full path to this node in the tree (e.g., "/content/my-page") */
  path: string;
  /** The NodeType name that defines this node's schema */
  node_type: string;
  /** Optional archetype for specialized rendering */
  archetype?: string;
  /** Key-value map of properties, validated against the NodeType schema */
  properties: Record<string, PropertyValue>;
  /** Ordered list of child node IDs */
  children: string[];
  /** Fractional index for ordering among siblings (Base62 string) */
  order_key: string;
  /** Whether this node has children (computed field) */
  has_children?: boolean;
  /**
   * Name of the parent node (not the full path, just the name).
   * Example: If path is "/content/docs/page1", parent should be "docs"
   */
  parent?: string;
  /** Version number for this node (incremented on updates) */
  version: number;
  /** Timestamp when this node was created (ISO 8601 string) */
  created_at?: string;
  /** Timestamp when this node was last updated (ISO 8601 string) */
  updated_at?: string;
  /** Timestamp when this node was published (ISO 8601 string, null if unpublished) */
  published_at?: string;
  /** User ID who published this node */
  published_by?: string;
  /** User ID who last updated this node */
  updated_by?: string;
  /** User ID who created this node */
  created_by?: string;
  /** Translations for multi-language support */
  translations?: Record<string, PropertyValue>;
  /** Tenant ID for multi-tenant deployments */
  tenant_id?: string;
  /** Workspace this node belongs to */
  workspace?: string;
  /** Owner user ID (for access control) */
  owner_id?: string;
  /** Relations to other nodes */
  relations: RelationRef[];
}

/**
 * Property value types
 */
export type PropertyValue =
  | string
  | number
  | boolean
  | null
  | PropertyValue[]
  | { [key: string]: PropertyValue };

/**
 * Node create payload
 */
export interface NodeCreatePayload {
  node_type: string;
  path: string;
  properties: Record<string, PropertyValue>;
  content?: unknown;
}

/**
 * Node update payload
 */
export interface NodeUpdatePayload {
  node_id: string;
  properties: Record<string, PropertyValue>;
  content?: unknown;
}

/**
 * Node delete payload
 */
export interface NodeDeletePayload {
  node_id: string;
}

/**
 * Node get payload
 */
export interface NodeGetPayload {
  node_id: string;
}

/**
 * Node query payload
 */
export interface NodeQueryPayload {
  query: unknown;
  limit?: number;
  offset?: number;
}

/**
 * Relationship add payload
 */
export interface RelationAddPayload {
  source_path: string;
  target_workspace: string;
  target_path: string;
  weight?: number;
  relation_type?: string;
}

/**
 * Relationship remove payload
 */
export interface RelationRemovePayload {
  source_path: string;
  target_workspace: string;
  target_path: string;
}

/**
 * Relationship list payload
 */
export interface RelationsGetPayload {
  node_path: string;
}

/**
 * SQL query payload
 */
export interface SqlQueryPayload {
  /** SQL query string */
  query: string;
  /** Parameters for the query (for injection protection) */
  params?: unknown[];
}

/**
 * SQL query result
 */
export interface SqlResult {
  columns: string[];
  rows: Record<string, unknown>[];
  row_count: number;
}

// ============================================================================
// Workspace Operation Types
// ============================================================================

/**
 * Workspace data structure
 */
export interface Workspace {
  id: string;
  name: string;
  description?: string;
  allowed_node_types?: string[];
  allowed_root_node_types?: string[];
  created_at?: string;
  updated_at?: string;
}

/**
 * Workspace create payload
 */
export interface WorkspaceCreatePayload {
  name: string;
  description?: string;
}

/**
 * Workspace get payload
 */
export interface WorkspaceGetPayload {
  name: string;
}

/**
 * Workspace delete payload
 */
export interface WorkspaceDeletePayload {
  name: string;
}

/**
 * Workspace update payload
 */
export interface WorkspaceUpdatePayload {
  name: string;
  description?: string;
  allowed_node_types?: string[];
  allowed_root_node_types?: string[];
}

// ============================================================================
// Transaction Operation Types
// ============================================================================

/**
 * Transaction begin payload
 */
export interface TransactionBeginPayload {
  /** Optional commit message */
  message?: string;
  /** Optional actor identifier */
  actor?: string;
}

/**
 * Transaction begin response
 */
export interface TransactionBeginResponse {
  /** Unique transaction ID */
  transaction_id: string;
}

/**
 * Transaction commit payload
 */
export interface TransactionCommitPayload {}

/**
 * Transaction commit response
 */
export interface TransactionCommitResponse {
  /** Revision (HLC timestamp) assigned to this commit in format "timestamp-counter" (e.g., "1762780281515-0") */
  revision: string;
  /** Unique commit ID */
  commit_id: string;
}

/**
 * Transaction rollback payload
 */
export interface TransactionRollbackPayload {}

// ============================================================================
// Event Subscription Types
// ============================================================================

/**
 * Subscribe payload
 */
export interface SubscribePayload {
  /** Filters for this subscription */
  filters: SubscriptionFilters;
}

/**
 * Subscription filters
 */
export interface SubscriptionFilters {
  /** Filter by workspace */
  workspace?: string;
  /** Filter by path pattern (supports wildcards like "/folder/*") */
  path?: string;
  /** Filter by event types */
  event_types?: string[];
  /** Filter by node type */
  node_type?: string;
  /** Include full node data in event payload (default: false) */
  include_node?: boolean;
}

/**
 * Unsubscribe payload
 */
export interface UnsubscribePayload {
  /** Subscription ID to cancel */
  subscription_id: string;
}

/**
 * Subscription response
 */
export interface SubscriptionResponse {
  /** Unique subscription ID */
  subscription_id: string;
}

// ============================================================================
// Authentication Types
// ============================================================================

/**
 * Authenticate payload (admin user with username/password)
 */
export interface AuthenticatePayload {
  username: string;
  password: string;
}

/**
 * Authenticate with JWT token (identity user)
 *
 * Used by SPAs and clients that have already obtained a JWT token
 * via HTTP API (e.g., /auth/{repo}/login)
 */
export interface AuthenticateJwtPayload {
  /** JWT access token from identity provider */
  token: string;
}

/**
 * Authenticate response (admin auth)
 */
export interface AuthenticateResponse {
  access_token: string;
  refresh_token: string;
  expires_in: number;
}

/**
 * Authenticate JWT response (identity auth)
 */
export interface AuthenticateJwtResponse {
  /** User ID from the JWT */
  user_id: string;
  /** Effective roles assigned to the user */
  roles: string[];
}

/**
 * Refresh token payload
 */
export interface RefreshTokenPayload {
  refresh_token: string;
}

// ============================================================================
// MessagePack Utilities
// ============================================================================

/**
 * Encode a message to MessagePack binary format
 */
export function encodeMessage(message: RequestEnvelope): Uint8Array {
  return encode(message);
}

/**
 * Decode a MessagePack binary message
 */
export function decodeMessage(data: ArrayBuffer | Uint8Array): ResponseEnvelope | EventMessage {
  const decoded = decode(data) as ResponseEnvelope | EventMessage;

  // Type guard: check if it's an event message
  if ('subscription_id' in decoded && 'event_type' in decoded) {
    return decoded as EventMessage;
  }

  return decoded as ResponseEnvelope;
}

/**
 * Type guard to check if a message is an event
 */
export function isEventMessage(message: ResponseEnvelope | EventMessage): message is EventMessage {
  return 'subscription_id' in message && 'event_type' in message;
}

/**
 * Type guard to check if a message is a response
 */
export function isResponseEnvelope(message: ResponseEnvelope | EventMessage): message is ResponseEnvelope {
  return 'status' in message && !('subscription_id' in message);
}

/**
 * Type guard to check if a message is a connected message
 */
export function isConnectedMessage(message: unknown): message is ConnectedMessage {
  return (
    typeof message === 'object' &&
    message !== null &&
    'type' in message &&
    (message as ConnectedMessage).type === 'connected'
  );
}
