export function sdkAssetsKnowledge(): string {
  return `# RaisinDB Assets -- Upload & Display

## Overview

RaisinDB handles binary assets (images, videos, documents, etc.) through the
built-in \`raisin:Asset\` node type. Assets are stored as nodes with a \`Resource\`
property that holds file metadata and a storage key to the binary data.

The lifecycle: **upload** (chunked) -> **store** as node with Resource property ->
**sign URL** for secure access -> **display** in frontend.

## The raisin:Asset Node Type

Every uploaded file creates a \`raisin:Asset\` node with these properties:

| Property | Type | Description |
|----------|------|-------------|
| title | String | Display name (indexed for search) |
| file | Resource | The binary file (see Resource format below) |
| file_type | String | MIME category (e.g. "image", "video") |
| file_size | Number | Size in bytes |
| description | String | Optional description (indexed) |
| alt_text | String | Alt text for images |
| keywords | Array | Tags for search (indexed) |
| meta | Object | Custom metadata |

## Resource Property Format

A \`Resource\` property stores file metadata as JSON:

\`\`\`json
{
  "uuid": "file-uuid",
  "name": "photo.jpeg",
  "size": 102400,
  "mime_type": "image/jpeg",
  "url": "storage-key-path",
  "metadata": {
    "storage_key": "internal-storage-path"
  },
  "is_loaded": true,
  "is_external": false,
  "created_at": "2026-01-15T10:00:00Z",
  "updated_at": "2026-01-15T10:00:00Z"
}
\`\`\`

You don't need to construct this manually -- the upload API creates it automatically.

## Uploading Assets (Browser)

Use the SDK's workspace upload methods:

\`\`\`typescript
import { RaisinClient } from '@raisindb/client';

const client = new RaisinClient('ws://localhost:8081/sys/default/my-repo', { ... });
const db = client.database('my-repo');
const ws = db.workspace('content');

// Single file upload
const fileInput = document.querySelector('input[type="file"]');
const file = fileInput.files[0];

const upload = await ws.upload(file, '/files/my-image.jpg', {
  onProgress: (p) => {
    console.log(\`\${Math.round(p.progress * 100)}% - \${p.status}\`);
    // p.speed (bytes/sec), p.eta (seconds), p.bytesUploaded, p.bytesTotal
  },
});

const result = await upload.start();
// result contains the created node with Resource property
\`\`\`

### Upload Controls

\`\`\`typescript
const upload = await ws.upload(file, path, options);

await upload.start();    // Begin uploading
upload.pause();          // Pause (can resume later)
await upload.resume();   // Resume after pause
await upload.cancel();   // Cancel upload

const progress = upload.getProgress();  // Check status anytime
\`\`\`

### Upload Options

\`\`\`typescript
await ws.upload(file, path, {
  nodeType: 'raisin:Asset',           // default
  metadata: { source: 'user-upload' }, // custom metadata
  chunkSize: 10 * 1024 * 1024,        // 10 MB default
  autoRetry: true,                     // retry on failure (default)
  maxRetries: 3,                       // retry attempts (default)
  signal: abortController.signal,      // for cancellation
  onProgress: (progress) => { ... },   // progress callback
});
\`\`\`

### Batch Upload (Multiple Files)

\`\`\`typescript
const files = document.querySelector('input[type="file"]').files;

const batch = await ws.uploadFiles(files, '/files/', {
  concurrency: 3,                        // parallel uploads (default)
  continueOnError: true,                 // don't stop on single failure
  onProgress: (p) => {
    console.log(\`\${p.filesCompleted}/\${p.filesTotal} files, \${Math.round(p.progress * 100)}%\`);
  },
  onFileComplete: (filePath, result) => {
    console.log('Uploaded:', filePath);
  },
  onFileError: (filePath, error) => {
    console.error('Failed:', filePath, error);
  },
});

const results = await batch.start();
\`\`\`

## Displaying Assets (Signed URLs)

Assets are accessed via **signed URLs** that are time-limited and secure.
The server generates an HMAC-signed URL that expires (default 5 minutes).

### Get a Display URL (inline)

\`\`\`typescript
const ws = db.workspace('content');

// Display in browser (Content-Disposition: inline)
const { url } = await ws.signAssetUrl('/files/my-image.jpg', 'display');
\`\`\`

### Get a Download URL

\`\`\`typescript
// Force download (Content-Disposition: attachment)
const { url } = await ws.signAssetUrl('/files/document.pdf', 'download');
\`\`\`

### Get Thumbnail URL

If the asset has a \`thumbnail\` property (e.g. generated by a processor):

\`\`\`typescript
const { url } = await ws.signAssetUrl('/files/my-image.jpg', 'display', {
  propertyPath: 'thumbnail',
});
\`\`\`

### Use in HTML

\`\`\`html
<!-- Image display -->
<img src={displayUrl} alt="My image" />

<!-- Download link -->
<a href={downloadUrl} download>Download PDF</a>

<!-- Background image -->
<div style="background-image: url({displayUrl})"></div>
\`\`\`

### signAssetUrl Parameters

\`\`\`typescript
ws.signAssetUrl(
  path: string,                     // node path (e.g. '/files/image.jpg')
  command: 'display' | 'download',  // inline vs force-download
  options?: {
    propertyPath?: string,          // 'file' (default), 'thumbnail', etc.
    expiresIn?: number,             // seconds, default 300 (5 minutes)
  }
): Promise<{ url: string; expiresAt: string }>
\`\`\`

## Querying Assets

\`\`\`sql
-- List all assets in a workspace
SELECT id, path, properties ->> 'title' AS title,
       properties ->> 'file_type' AS type,
       properties ->> 'file_size' AS size
FROM 'content'
WHERE node_type = 'raisin:Asset'

-- Search assets by keyword
SELECT * FROM 'content'
WHERE node_type = 'raisin:Asset'
  AND FULLTEXT_MATCH('landscape photo', 'english')

-- Filter by MIME type
SELECT * FROM 'content'
WHERE node_type = 'raisin:Asset'
  AND properties ->> 'file_type' = 'image'

-- Assets in a specific folder
SELECT * FROM 'content'
WHERE node_type = 'raisin:Asset'
  AND CHILD_OF('/content/images')
\`\`\`

## MediaField in Archetypes

Use \`MediaField\` in an archetype to let editors pick/upload assets:

\`\`\`yaml
# archetypes/blog-post.yaml
fields:
  - $type: MediaField
    name: cover_image
    title: Cover Image
\`\`\`

This creates a Resource property on the node. In the frontend, resolve the
asset URL to display it:

\`\`\`typescript
// Get the asset path from the cover_image Resource property
const coverImage = page.properties.cover_image;
if (coverImage?.url) {
  const { url } = await ws.signAssetUrl(assetNodePath, 'display');
  // Use url in an <img> tag
}
\`\`\`

## Complete Example: Image Gallery

\`\`\`typescript
// 1. Upload images
const files = document.querySelector('#gallery-upload').files;
const batch = await ws.uploadFiles(files, '/content/gallery/', {
  onProgress: (p) => updateProgressBar(p.progress),
});
await batch.start();

// 2. Query gallery images
const images = await query(\`
  SELECT id, path, properties ->> 'title' AS title,
         properties ->> 'alt_text' AS alt
  FROM 'content'
  WHERE node_type = 'raisin:Asset'
    AND CHILD_OF('/content/gallery')
    AND properties ->> 'file_type' = 'image'
\`);

// 3. Get signed URLs for display
const gallery = await Promise.all(
  images.map(async (img) => ({
    ...img,
    url: (await ws.signAssetUrl(img.path, 'display')).url,
    thumbUrl: (await ws.signAssetUrl(img.path, 'display', {
      propertyPath: 'thumbnail'
    })).url,
  }))
);

// 4. Render
gallery.forEach(img => {
  // <img src={img.thumbUrl} alt={img.alt} />
});
\`\`\`

## Server-Side Asset Access

In server-side functions, access assets via the \`raisin\` API:

\`\`\`javascript
async function handler(context) {
  // Query assets
  const assets = await raisin.sql.query(\`
    SELECT path, properties FROM 'content'
    WHERE node_type = 'raisin:Asset' AND CHILD_OF('/content/uploads')
  \`);

  // Access binary data is handled by the storage layer
  // Functions typically work with asset metadata, not raw binary
  return { assets: assets.rows };
}
\`\`\`
`;
}
