// SPDX-License-Identifier: BSL-1.1

//! Envelope types, request/response enums, and helper constructors.
//!
//! This module contains the top-level message structures that wrap all
//! WebSocket communication: [`RequestEnvelope`], [`ResponseEnvelope`],
//! and [`EventMessage`], together with their associated context and
//! metadata types.

use serde::{Deserialize, Serialize};
use uuid::Uuid;

// ---------------------------------------------------------------------------
// Request envelope
// ---------------------------------------------------------------------------

/// Request envelope wrapping all client-to-server messages
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RequestEnvelope {
    /// Unique identifier for this request (generated by client)
    pub request_id: String,

    /// Type of request
    #[serde(rename = "type")]
    pub request_type: RequestType,

    /// Request context (tenant, repository, workspace)
    pub context: RequestContext,

    /// Request-specific payload
    pub payload: serde_json::Value,
}

impl RequestEnvelope {
    /// Create a new request envelope with a generated request ID
    pub fn new(
        request_type: RequestType,
        context: RequestContext,
        payload: serde_json::Value,
    ) -> Self {
        Self {
            request_id: Uuid::new_v4().to_string(),
            request_type,
            context,
            payload,
        }
    }
}

// ---------------------------------------------------------------------------
// Response envelope
// ---------------------------------------------------------------------------

/// Response envelope wrapping all server-to-client messages
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResponseEnvelope {
    /// Request ID this response corresponds to
    pub request_id: String,

    /// Response status
    pub status: ResponseStatus,

    /// Response data (if successful)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<serde_json::Value>,

    /// Error information (if failed)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<ErrorInfo>,

    /// Metadata for streaming responses
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<ResponseMetadata>,
}

impl ResponseEnvelope {
    /// Create a successful response
    pub fn success(request_id: String, result: serde_json::Value) -> Self {
        Self {
            request_id,
            status: ResponseStatus::Success,
            result: Some(result),
            error: None,
            metadata: None,
        }
    }

    /// Create an error response
    pub fn error(request_id: String, code: String, message: String) -> Self {
        Self {
            request_id,
            status: ResponseStatus::Error,
            result: None,
            error: Some(ErrorInfo {
                code,
                message,
                details: None,
            }),
            metadata: None,
        }
    }

    /// Create a streaming response chunk
    pub fn streaming(request_id: String, result: serde_json::Value, chunk: u32) -> Self {
        Self {
            request_id,
            status: ResponseStatus::Streaming,
            result: Some(result),
            error: None,
            metadata: Some(ResponseMetadata {
                chunk: Some(chunk),
                total_chunks: None,
                total: None,
                has_more: Some(true),
                credits_consumed: None,
            }),
        }
    }

    /// Create a final streaming response chunk
    pub fn complete(request_id: String, result: serde_json::Value) -> Self {
        Self {
            request_id,
            status: ResponseStatus::Complete,
            result: Some(result),
            error: None,
            metadata: Some(ResponseMetadata {
                chunk: None,
                total_chunks: None,
                total: None,
                has_more: Some(false),
                credits_consumed: None,
            }),
        }
    }
}

// ---------------------------------------------------------------------------
// Event message
// ---------------------------------------------------------------------------

/// Event message for server-initiated events (subscriptions)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventMessage {
    /// Unique event ID
    pub event_id: String,

    /// Subscription ID this event belongs to
    pub subscription_id: String,

    /// Event type
    pub event_type: String,

    /// Event payload
    pub payload: serde_json::Value,

    /// Timestamp of the event
    pub timestamp: chrono::DateTime<chrono::Utc>,
}

impl EventMessage {
    /// Create a new event message
    pub fn new(subscription_id: String, event_type: String, payload: serde_json::Value) -> Self {
        Self {
            event_id: Uuid::new_v4().to_string(),
            subscription_id,
            event_type,
            payload,
            timestamp: chrono::Utc::now(),
        }
    }
}

// ---------------------------------------------------------------------------
// Context & metadata
// ---------------------------------------------------------------------------

/// Request context containing scope information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RequestContext {
    /// Tenant ID
    pub tenant_id: String,

    /// Repository ID (optional for some operations)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub repository: Option<String>,

    /// Branch name (optional, defaults to "main")
    #[serde(skip_serializing_if = "Option::is_none")]
    pub branch: Option<String>,

    /// Workspace ID (optional for some operations)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workspace: Option<String>,

    /// Revision/commit ID for time-travel queries (optional)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
}

/// Response status
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ResponseStatus {
    /// Request succeeded, complete result included
    Success,

    /// Request failed, error information included
    Error,

    /// Streaming response, more chunks to come
    Streaming,

    /// Final chunk of a streaming response
    Complete,

    /// Request acknowledged, processing asynchronously
    Acknowledged,
}

/// Error information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ErrorInfo {
    /// Error code
    pub code: String,

    /// Human-readable error message
    pub message: String,

    /// Additional error details
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<serde_json::Value>,
}

/// Response metadata for streaming and pagination
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResponseMetadata {
    /// Current chunk number (for streaming)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub chunk: Option<u32>,

    /// Total number of chunks (if known)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_chunks: Option<u32>,

    /// Total number of results (for pagination)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total: Option<u64>,

    /// Has more results available
    #[serde(skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,

    /// Credits consumed (for backpressure)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub credits_consumed: Option<u32>,
}

// ---------------------------------------------------------------------------
// Request type enum
// ---------------------------------------------------------------------------

/// Type of request
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RequestType {
    // Authentication
    Authenticate,
    AuthenticateJwt,
    RefreshToken,

    // Node operations
    NodeCreate,
    NodeUpdate,
    NodeDelete,
    NodeGet,
    NodeQuery,
    NodeQueryByPath,
    NodeQueryByProperty,

    // Node manipulation operations
    NodeMove,
    NodeRename,
    NodeCopy,
    NodeCopyTree,
    NodeReorder,
    NodeMoveChildBefore,
    NodeMoveChildAfter,

    // Tree operations
    NodeListChildren,
    NodeGetTree,
    NodeGetTreeFlat,

    // Property path operations
    PropertyGet,
    PropertyUpdate,

    // Relationship operations
    RelationAdd,
    RelationRemove,
    RelationsGet,

    // Translation operations
    TranslationUpdate,
    TranslationList,
    TranslationDelete,
    TranslationHide,
    TranslationUnhide,

    // SQL queries
    SqlQuery,

    // Workspace operations
    WorkspaceCreate,
    WorkspaceGet,
    WorkspaceList,
    WorkspaceDelete,
    WorkspaceUpdate,

    // Branch operations
    BranchCreate,
    BranchGet,
    BranchList,
    BranchDelete,
    BranchGetHead,
    BranchUpdateHead,
    BranchMerge,
    BranchCompare,

    // Tag operations
    TagCreate,
    TagGet,
    TagList,
    TagDelete,

    // NodeType operations
    NodeTypeCreate,
    NodeTypeGet,
    NodeTypeList,
    NodeTypeUpdate,
    NodeTypeDelete,
    NodeTypePublish,
    NodeTypeUnpublish,
    NodeTypeValidate,
    NodeTypeGetResolved,

    // Archetype operations
    ArchetypeCreate,
    ArchetypeGet,
    ArchetypeList,
    ArchetypeUpdate,
    ArchetypeDelete,
    ArchetypePublish,
    ArchetypeUnpublish,

    // ElementType operations
    ElementTypeCreate,
    ElementTypeGet,
    ElementTypeList,
    ElementTypeUpdate,
    ElementTypeDelete,
    ElementTypePublish,
    ElementTypeUnpublish,

    // Search operations
    FullTextSearch,
    VectorSearch,

    // Event subscriptions
    Subscribe,
    Unsubscribe,

    // Repository management
    RepositoryCreate,
    RepositoryGet,
    RepositoryList,
    RepositoryUpdate,
    RepositoryDelete,

    // Audit operations
    AuditQuery,

    // Binary operations
    BinaryUpload,
    BinaryDownload,

    // Batch operations
    Batch,

    // Transaction operations
    TransactionBegin,
    TransactionCommit,
    TransactionRollback,

    // Flow operations
    FlowRun,
    FlowResume,
    FlowGetInstanceStatus,
    FlowCancel,
    FlowSubscribeEvents,
    FlowUnsubscribeEvents,

    // Function operations
    FunctionInvoke,
    FunctionInvokeSync,
}
