//! Legacy node creation methods for NodeService
//!
//! These methods provide high-level node creation APIs with validation,
//! path generation, and initial_structure support.

use raisin_error::Result;
use raisin_models as models;
use raisin_storage::{scope::BranchScope, NodeRepository, NodeTypeRepository, Storage};

use super::NodeService;
use crate::sanitize_name;

impl<S: Storage + raisin_storage::transactional::TransactionalStorage> NodeService<S> {
    /// Recursively creates initial children from InitialChild definitions.
    /// This is called after a node is created if its NodeType has an initial_structure.
    pub(super) fn create_initial_children<'a>(
        &'a self,
        parent_node: &'a models::nodes::Node,
        children: &'a [raisin_models::nodes::types::initial_structure::InitialChild],
    ) -> std::pin::Pin<
        Box<dyn std::future::Future<Output = Result<Vec<models::nodes::Node>>> + Send + 'a>,
    > {
        Box::pin(async move {
            let mut created_children = Vec::new();

            for child_def in children {
                // Create child node from definition
                let child_properties = child_def.properties.clone().unwrap_or_default();

                // Convert HashMap<String, serde_json::Value> to HashMap<String, PropertyValue>
                let properties: std::collections::HashMap<
                    String,
                    models::nodes::properties::PropertyValue,
                > = child_properties
                    .into_iter()
                    .filter_map(|(k, v)| serde_json::from_value(v).ok().map(|pv| (k, pv)))
                    .collect();

                // Convert translations if present
                let translations = child_def.translations.as_ref().map(|trans| {
                    trans
                        .iter()
                        .filter_map(|(k, v)| {
                            serde_json::from_value(v.clone())
                                .ok()
                                .map(|pv| (k.clone(), pv))
                        })
                        .collect()
                });

                let child_node = models::nodes::Node {
                    id: String::new(), // Will be auto-generated by add_node
                    name: child_def.name.clone(),
                    path: String::new(), // Will be auto-generated by add_node
                    node_type: child_def.node_type.clone(),
                    archetype: child_def.archetype.clone(),
                    properties,
                    children: vec![],
                    order_key: String::new(), // Will be assigned by storage layer
                    has_children: None,       // Computed at service layer
                    parent: None,             // Will be auto-derived by storage layer from path
                    version: 1,
                    created_at: None,
                    updated_at: None,
                    published_at: None,
                    published_by: None,
                    updated_by: None,
                    created_by: None,
                    translations,
                    tenant_id: parent_node.tenant_id.clone(),
                    workspace: Some(self.workspace_id.clone()),
                    owner_id: parent_node.owner_id.clone(),
                    relations: Vec::new(),
                };

                // Create the child node (this validates NodeType, properties, etc.)
                match self.add_node(&parent_node.path, child_node).await {
                    Ok(created_child) => {
                        created_children.push(created_child.clone());

                        // Recursively create nested children if defined
                        if let Some(nested_children) = &child_def.children {
                            match self
                                .create_initial_children(&created_child, nested_children)
                                .await
                            {
                                Ok(nested_created) => created_children.extend(nested_created),
                                Err(e) => {
                                    // Rollback: delete all children created so far
                                    for created in &created_children {
                                        let _ = self
                                            .storage
                                            .nodes()
                                            .delete(
                                                self.scope(),
                                                &created.id,
                                                raisin_storage::DeleteNodeOptions::default(),
                                            )
                                            .await;
                                    }
                                    return Err(e);
                                }
                            }
                        }
                    }
                    Err(e) => {
                        // Rollback: delete all children created so far
                        for created in &created_children {
                            let _ = self
                                .storage
                                .nodes()
                                .delete(
                                    self.scope(),
                                    &created.id,
                                    raisin_storage::DeleteNodeOptions::default(),
                                )
                                .await;
                        }
                        return Err(e);
                    }
                }
            }

            Ok(created_children)
        })
    }

    /// Validates that a node with the given name doesn't already exist under the parent.
    async fn validate_unique_name_under_parent(&self, parent_path: &str, name: &str) -> Result<()> {
        let full_path = if parent_path.is_empty() || parent_path == "/" {
            format!("/{}", name)
        } else {
            format!("{}/{}", parent_path, name)
        };

        if self.get_by_path(&full_path).await?.is_some() {
            return Err(raisin_error::Error::Validation(format!(
                "A node with the name '{}' already exists under the specified parent",
                name
            )));
        }
        Ok(())
    }

    /// Creates a folder node at the given path if it doesn't exist.
    /// Used by ensure_path_exists to auto-create missing parent folders.
    async fn create_folder_if_missing(&self, path: &str) -> Result<()> {
        // Check if already exists
        if self.get_by_path(path).await?.is_some() {
            return Ok(());
        }

        // Extract parent and name
        let (parent, name) = if let Some(idx) = path.rfind('/') {
            let parent = &path[..idx];
            let name = &path[idx + 1..];
            (if parent.is_empty() { "/" } else { parent }, name)
        } else {
            ("/", path)
        };

        // Create the folder node
        let folder = models::nodes::Node {
            id: nanoid::nanoid!(),
            name: name.to_string(),
            path: path.to_string(),
            node_type: "raisin:Folder".to_string(),
            archetype: None,
            properties: Default::default(),
            children: vec![],
            order_key: String::new(), // Will be assigned by storage layer
            has_children: None,       // Computed at service layer
            parent: None,             // Will be auto-derived by storage layer from path
            version: 1,
            created_at: Some(chrono::Utc::now()),
            updated_at: Some(chrono::Utc::now()),
            published_at: None,
            published_by: None,
            updated_by: None,
            created_by: None,
            translations: None,
            tenant_id: None,
            workspace: Some(self.workspace_id.clone()),
            owner_id: None,
            relations: Vec::new(),
        };

        self.upsert(folder).await
    }

    /// Ensures that all parent directories in a path exist, creating them as folders if needed.
    /// This is used for deep node creation.
    async fn ensure_path_exists(&self, path: &str) -> Result<()> {
        if path.is_empty() || path == "/" {
            return Ok(());
        }

        let trimmed = path.trim_start_matches('/');
        let segments: Vec<&str> = trimmed.split('/').collect();

        let mut current_path = String::new();
        for segment in segments {
            if segment.is_empty() {
                continue;
            }
            current_path.push('/');
            current_path.push_str(segment);

            self.create_folder_if_missing(&current_path).await?;
        }

        Ok(())
    }

    /// Adds a node with standard validation (parent must exist).
    /// This method:
    /// 1. Validates NodeType exists and is published
    /// 2. Validates node against NodeType schema (required properties, strict mode, unique constraints)
    /// 3. Validates parent exists (if not root)
    /// 4. Sanitizes the node name
    /// 5. Auto-generates the path from parent + name
    /// 6. Validates unique name under parent
    /// 7. Saves the node using put()
    ///
    /// # Arguments
    /// * `parent_path` - Parent location (e.g., "/company" to create child "/company/team")
    /// * `node` - Node data with name, node_type, properties (path and id will be auto-generated)
    pub async fn add_node(
        &self,
        parent_path: &str,
        mut node: models::nodes::Node,
    ) -> Result<models::nodes::Node> {
        // Validate NodeType exists and validate node against schema
        // NOTE: RocksDB transaction layer also validates, but InMemoryStorage doesn't,
        // so we validate here as well for consistent behavior across backends.
        self.validator
            .validate_node_type_exists(&node.node_type)
            .await?;
        self.validator
            .validate_node(&self.workspace_id, &node)
            .await?;

        // Sanitize the node name
        let clean_name = sanitize_name(&node.name)?;
        node.name = clean_name.clone();

        // Validate parent exists (unless creating at root)
        if parent_path != "/" && !parent_path.is_empty() {
            let _parent = self.get_by_path(parent_path).await?.ok_or_else(|| {
                raisin_error::Error::NotFound(format!("Parent node '{}' not found", parent_path))
            })?;
            // Do NOT set node.parent here - storage layer will derive it from node.path
        }
        // Do NOT set node.parent - storage layer will derive it from node.path

        // Generate the full path
        let full_path = if parent_path.is_empty() || parent_path == "/" {
            format!("/{}", clean_name)
        } else {
            format!("{}/{}", parent_path, clean_name)
        };
        node.path = full_path.clone();

        // Validate unique name under parent
        self.validate_unique_name_under_parent(parent_path, &clean_name)
            .await?;

        // Generate ID if not provided
        if node.id.is_empty() {
            node.id = nanoid::nanoid!();
        }

        // Set timestamps
        if node.created_at.is_none() {
            node.created_at = Some(chrono::Utc::now());
        }
        if node.updated_at.is_none() {
            node.updated_at = Some(chrono::Utc::now());
        }

        // Set workspace
        node.workspace = Some(self.workspace_id.clone());

        // Create automatic commit for this operation
        // This triggers tree building and creates a new revision
        let commit_message = format!("Created node: {}", node.id);
        let ctx = self.storage.begin_context().await?;

        // Set auth context for RLS enforcement
        if let Some(auth) = &self.auth_context {
            ctx.set_auth_context(auth.clone())?;
        }

        // Set transaction context for revision tracking
        ctx.set_tenant_repo(&self.tenant_id, &self.repo_id)?;
        ctx.set_branch(&self.branch)?;
        ctx.set_message(&commit_message)?;

        // CRITICAL: Use add_node (optimized) instead of put_node for new nodes
        // The ORDERED_CHILDREN index automatically handles child ordering
        ctx.add_node(&self.workspace_id, &node).await?;

        // Commit the transaction
        ctx.commit().await?;

        // Auto-create initial_structure children if defined in NodeType
        let node_type = self
            .storage
            .node_types()
            .get(
                BranchScope::new(&self.tenant_id, &self.repo_id, &self.branch),
                &node.node_type,
                None,
            )
            .await?
            .ok_or_else(|| {
                raisin_error::Error::NotFound(format!("NodeType '{}' not found", node.node_type))
            })?;

        if let Some(initial_structure) = &node_type.initial_structure {
            if let Some(children) = &initial_structure.children {
                // Create all initial children recursively
                match self.create_initial_children(&node, children).await {
                    Ok(_) => {
                        // Successfully created initial children
                    }
                    Err(e) => {
                        // Rollback: delete the parent node since initial children failed
                        let _ = self
                            .storage
                            .nodes()
                            .delete(
                                self.scope(),
                                &node.id,
                                raisin_storage::DeleteNodeOptions::default(),
                            )
                            .await;
                        return Err(raisin_error::Error::Validation(format!(
                            "Failed to create initial_structure children: {}",
                            e
                        )));
                    }
                }
            }
        }

        // CRITICAL: Derive parent NAME from path before returning
        // Storage layer auto-derives this during save, but we need to sync the in-memory node
        node.parent = models::nodes::Node::extract_parent_name_from_path(&node.path);

        Ok(node)
    }

    /// Adds a node with deep creation (auto-creates missing parent folders).
    /// This method:
    /// 1. Auto-creates missing parent folders as "raisin:Folder" nodes
    /// 2. Then calls add_node() for validation and creation
    ///
    /// # Arguments
    /// * `parent_path` - Parent location (can be non-existent, will be created)
    /// * `node` - Node data with name, node_type, properties
    pub async fn add_deep_node(
        &self,
        parent_path: &str,
        node: models::nodes::Node,
    ) -> Result<models::nodes::Node> {
        // Ensure all parent directories exist, creating folders as needed
        if parent_path != "/" && !parent_path.is_empty() {
            self.ensure_path_exists(parent_path).await?;
        }

        // Now use standard add_node (parent is guaranteed to exist)
        self.add_node(parent_path, node).await
    }
}
