// Code generated by `cargo run -p raisin-functions --bin gen-bindings`.
// DO NOT EDIT — edit `crates/raisin-functions/src/runtime/bindings/` and
// re-run `make gen-bindings` instead.
//!
//! Typed wrappers over the single WIT gateway `host.call(method, args)`.
//! Every function serialises its arguments into a positional JSON array
//! and decodes the reply through `crate::wire`, which turns an
//! `{"error": true, ...}` envelope into an `Err` (defensive rule: a host
//! that answers Ok with an error envelope is still an error).

#![allow(clippy::too_many_arguments)]

pub mod admin {
    pub mod nodes {
        /// `raisin.admin.nodes.create` — registry method `admin_nodes_create`.
        pub fn create(workspace: &str, parent_path: &str, data: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
            let args = ::serde_json::Value::Array(vec![
                ::serde_json::to_value(workspace)?,
                ::serde_json::to_value(parent_path)?,
                ::serde_json::to_value(data)?,
            ])
            .to_string();
            let raw = crate::host::call("admin_nodes_create", &args)?;
            crate::wire::decode_json(&raw)
        }

        /// Typed form of `create`. `T` is inferred from the binding site
        /// (turbofish is unavailable when the method takes a JSON argument).
        pub fn create_as<T: ::serde::de::DeserializeOwned>(workspace: &str, parent_path: &str, data: impl ::serde::Serialize) -> crate::Result<T> {
            let args = ::serde_json::Value::Array(vec![
                ::serde_json::to_value(workspace)?,
                ::serde_json::to_value(parent_path)?,
                ::serde_json::to_value(data)?,
            ])
            .to_string();
            let raw = crate::host::call("admin_nodes_create", &args)?;
            crate::wire::decode_json_as(&raw)
        }

        /// `raisin.admin.nodes.delete` — registry method `admin_nodes_delete`.
        pub fn delete(workspace: &str, path: &str) -> crate::Result<()> {
            let args = ::serde_json::Value::Array(vec![
                ::serde_json::to_value(workspace)?,
                ::serde_json::to_value(path)?,
            ])
            .to_string();
            let raw = crate::host::call("admin_nodes_delete", &args)?;
            crate::wire::decode_void(&raw)
        }

        /// `raisin.admin.nodes.get` — registry method `admin_nodes_get`.
        pub fn get(workspace: &str, path: &str) -> crate::Result<Option<::serde_json::Value>> {
            let args = ::serde_json::Value::Array(vec![
                ::serde_json::to_value(workspace)?,
                ::serde_json::to_value(path)?,
            ])
            .to_string();
            let raw = crate::host::call("admin_nodes_get", &args)?;
            crate::wire::decode_optional_json(&raw)
        }

        /// Typed form of `get`. `T` is inferred from the binding site
        /// (turbofish is unavailable when the method takes a JSON argument).
        pub fn get_as<T: ::serde::de::DeserializeOwned>(workspace: &str, path: &str) -> crate::Result<Option<T>> {
            let args = ::serde_json::Value::Array(vec![
                ::serde_json::to_value(workspace)?,
                ::serde_json::to_value(path)?,
            ])
            .to_string();
            let raw = crate::host::call("admin_nodes_get", &args)?;
            crate::wire::decode_optional_json_as(&raw)
        }

        /// `raisin.admin.nodes.getById` — registry method `admin_nodes_getById`.
        pub fn get_by_id(workspace: &str, id: &str) -> crate::Result<Option<::serde_json::Value>> {
            let args = ::serde_json::Value::Array(vec![
                ::serde_json::to_value(workspace)?,
                ::serde_json::to_value(id)?,
            ])
            .to_string();
            let raw = crate::host::call("admin_nodes_getById", &args)?;
            crate::wire::decode_optional_json(&raw)
        }

        /// Typed form of `get_by_id`. `T` is inferred from the binding site
        /// (turbofish is unavailable when the method takes a JSON argument).
        pub fn get_by_id_as<T: ::serde::de::DeserializeOwned>(workspace: &str, id: &str) -> crate::Result<Option<T>> {
            let args = ::serde_json::Value::Array(vec![
                ::serde_json::to_value(workspace)?,
                ::serde_json::to_value(id)?,
            ])
            .to_string();
            let raw = crate::host::call("admin_nodes_getById", &args)?;
            crate::wire::decode_optional_json_as(&raw)
        }

        /// `raisin.admin.nodes.getChildren` — registry method `admin_nodes_getChildren`.
        pub fn get_children(workspace: &str, parent_path: &str, limit: Option<u32>) -> crate::Result<Vec<::serde_json::Value>> {
            let args = ::serde_json::Value::Array(vec![
                ::serde_json::to_value(workspace)?,
                ::serde_json::to_value(parent_path)?,
                ::serde_json::to_value(limit)?,
            ])
            .to_string();
            let raw = crate::host::call("admin_nodes_getChildren", &args)?;
            crate::wire::decode_json_array(&raw)
        }

        /// Typed form of `get_children`. `T` is inferred from the binding site
        /// (turbofish is unavailable when the method takes a JSON argument).
        pub fn get_children_as<T: ::serde::de::DeserializeOwned>(workspace: &str, parent_path: &str, limit: Option<u32>) -> crate::Result<Vec<T>> {
            let args = ::serde_json::Value::Array(vec![
                ::serde_json::to_value(workspace)?,
                ::serde_json::to_value(parent_path)?,
                ::serde_json::to_value(limit)?,
            ])
            .to_string();
            let raw = crate::host::call("admin_nodes_getChildren", &args)?;
            crate::wire::decode_json_array_as(&raw)
        }

        /// `raisin.admin.nodes.query` — registry method `admin_nodes_query`.
        pub fn query(workspace: &str, query: impl ::serde::Serialize) -> crate::Result<Vec<::serde_json::Value>> {
            let args = ::serde_json::Value::Array(vec![
                ::serde_json::to_value(workspace)?,
                ::serde_json::to_value(query)?,
            ])
            .to_string();
            let raw = crate::host::call("admin_nodes_query", &args)?;
            crate::wire::decode_json_array(&raw)
        }

        /// Typed form of `query`. `T` is inferred from the binding site
        /// (turbofish is unavailable when the method takes a JSON argument).
        pub fn query_as<T: ::serde::de::DeserializeOwned>(workspace: &str, query: impl ::serde::Serialize) -> crate::Result<Vec<T>> {
            let args = ::serde_json::Value::Array(vec![
                ::serde_json::to_value(workspace)?,
                ::serde_json::to_value(query)?,
            ])
            .to_string();
            let raw = crate::host::call("admin_nodes_query", &args)?;
            crate::wire::decode_json_array_as(&raw)
        }

        /// `raisin.admin.nodes.update` — registry method `admin_nodes_update`.
        pub fn update(workspace: &str, path: &str, data: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
            let args = ::serde_json::Value::Array(vec![
                ::serde_json::to_value(workspace)?,
                ::serde_json::to_value(path)?,
                ::serde_json::to_value(data)?,
            ])
            .to_string();
            let raw = crate::host::call("admin_nodes_update", &args)?;
            crate::wire::decode_json(&raw)
        }

        /// Typed form of `update`. `T` is inferred from the binding site
        /// (turbofish is unavailable when the method takes a JSON argument).
        pub fn update_as<T: ::serde::de::DeserializeOwned>(workspace: &str, path: &str, data: impl ::serde::Serialize) -> crate::Result<T> {
            let args = ::serde_json::Value::Array(vec![
                ::serde_json::to_value(workspace)?,
                ::serde_json::to_value(path)?,
                ::serde_json::to_value(data)?,
            ])
            .to_string();
            let raw = crate::host::call("admin_nodes_update", &args)?;
            crate::wire::decode_json_as(&raw)
        }

        /// `raisin.admin.nodes.updateProperty` — registry method `admin_nodes_updateProperty`.
        pub fn update_property(workspace: &str, node_path: &str, property_path: &str, value: impl ::serde::Serialize) -> crate::Result<()> {
            let args = ::serde_json::Value::Array(vec![
                ::serde_json::to_value(workspace)?,
                ::serde_json::to_value(node_path)?,
                ::serde_json::to_value(property_path)?,
                ::serde_json::to_value(value)?,
            ])
            .to_string();
            let raw = crate::host::call("admin_nodes_updateProperty", &args)?;
            crate::wire::decode_void(&raw)
        }

    }

    pub mod sql {
        /// `raisin.admin.sql.execute` — registry method `admin_sql_execute`.
        pub fn execute(sql: &str, params: &[::serde_json::Value]) -> crate::Result<i64> {
            let args = ::serde_json::Value::Array(vec![
                ::serde_json::to_value(sql)?,
                ::serde_json::to_value(params)?,
            ])
            .to_string();
            let raw = crate::host::call("admin_sql_execute", &args)?;
            crate::wire::decode_i64(&raw)
        }

        /// `raisin.admin.sql.query` — registry method `admin_sql_query`.
        pub fn query(sql: &str, params: &[::serde_json::Value]) -> crate::Result<::serde_json::Value> {
            let args = ::serde_json::Value::Array(vec![
                ::serde_json::to_value(sql)?,
                ::serde_json::to_value(params)?,
            ])
            .to_string();
            let raw = crate::host::call("admin_sql_query", &args)?;
            crate::wire::decode_json(&raw)
        }

        /// Typed form of `query`. `T` is inferred from the binding site
        /// (turbofish is unavailable when the method takes a JSON argument).
        pub fn query_as<T: ::serde::de::DeserializeOwned>(sql: &str, params: &[::serde_json::Value]) -> crate::Result<T> {
            let args = ::serde_json::Value::Array(vec![
                ::serde_json::to_value(sql)?,
                ::serde_json::to_value(params)?,
            ])
            .to_string();
            let raw = crate::host::call("admin_sql_query", &args)?;
            crate::wire::decode_json_as(&raw)
        }

    }

}

pub mod ai {
    /// `raisin.ai.completion` — registry method `ai_completion`.
    pub fn completion(request: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(request)?,
        ])
        .to_string();
        let raw = crate::host::call("ai_completion", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `completion`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn completion_as<T: ::serde::de::DeserializeOwned>(request: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(request)?,
        ])
        .to_string();
        let raw = crate::host::call("ai_completion", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.ai.embed` — registry method `ai_embed`.
    pub fn embed(request: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(request)?,
        ])
        .to_string();
        let raw = crate::host::call("ai_embed", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `embed`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn embed_as<T: ::serde::de::DeserializeOwned>(request: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(request)?,
        ])
        .to_string();
        let raw = crate::host::call("ai_embed", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.ai.getDefaultModel` — registry method `ai_getDefaultModel`.
    pub fn get_default_model(use_case: &str) -> crate::Result<Option<::serde_json::Value>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(use_case)?,
        ])
        .to_string();
        let raw = crate::host::call("ai_getDefaultModel", &args)?;
        crate::wire::decode_optional_json(&raw)
    }

    /// Typed form of `get_default_model`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn get_default_model_as<T: ::serde::de::DeserializeOwned>(use_case: &str) -> crate::Result<Option<T>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(use_case)?,
        ])
        .to_string();
        let raw = crate::host::call("ai_getDefaultModel", &args)?;
        crate::wire::decode_optional_json_as(&raw)
    }

    /// `raisin.ai.listModels` — registry method `ai_listModels`.
    pub fn list_models() -> crate::Result<Vec<::serde_json::Value>> {
        let args = "[]".to_string();
        let raw = crate::host::call("ai_listModels", &args)?;
        crate::wire::decode_json_array(&raw)
    }

    /// Typed form of `list_models`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn list_models_as<T: ::serde::de::DeserializeOwned>() -> crate::Result<Vec<T>> {
        let args = "[]".to_string();
        let raw = crate::host::call("ai_listModels", &args)?;
        crate::wire::decode_json_array_as(&raw)
    }

    /// `raisin.ai.listProviders` — registry method `ai_listProviders`.
    pub fn list_providers() -> crate::Result<Vec<::serde_json::Value>> {
        let args = "[]".to_string();
        let raw = crate::host::call("ai_listProviders", &args)?;
        crate::wire::decode_json_array(&raw)
    }

    /// Typed form of `list_providers`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn list_providers_as<T: ::serde::de::DeserializeOwned>() -> crate::Result<Vec<T>> {
        let args = "[]".to_string();
        let raw = crate::host::call("ai_listProviders", &args)?;
        crate::wire::decode_json_array_as(&raw)
    }

}

pub mod assets {
    /// `raisin.assets.ensureContent` — registry method `asset_ensure_content`.
    pub fn ensure_content(workspace: &str, node_ref: &str) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(node_ref)?,
        ])
        .to_string();
        let raw = crate::host::call("asset_ensure_content", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `ensure_content`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn ensure_content_as<T: ::serde::de::DeserializeOwned>(workspace: &str, node_ref: &str) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(node_ref)?,
        ])
        .to_string();
        let raw = crate::host::call("asset_ensure_content", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.assets.reextract` — registry method `asset_reextract`.
    pub fn reextract(workspace: &str, node_ref: &str) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(node_ref)?,
        ])
        .to_string();
        let raw = crate::host::call("asset_reextract", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `reextract`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn reextract_as<T: ::serde::de::DeserializeOwned>(workspace: &str, node_ref: &str) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(node_ref)?,
        ])
        .to_string();
        let raw = crate::host::call("asset_reextract", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.assets.setExtractedText` — registry method `asset_set_extraction`.
    pub fn set_extracted_text(workspace: &str, node_ref: &str, text: &str, options: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(node_ref)?,
            ::serde_json::to_value(text)?,
            ::serde_json::to_value(options)?,
        ])
        .to_string();
        let raw = crate::host::call("asset_set_extraction", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `set_extracted_text`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn set_extracted_text_as<T: ::serde::de::DeserializeOwned>(workspace: &str, node_ref: &str, text: &str, options: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(node_ref)?,
            ::serde_json::to_value(text)?,
            ::serde_json::to_value(options)?,
        ])
        .to_string();
        let raw = crate::host::call("asset_set_extraction", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.assets.signedUrl` — registry method `asset_signed_url`.
    pub fn signed_url(workspace: &str, node_ref: &str, options: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(node_ref)?,
            ::serde_json::to_value(options)?,
        ])
        .to_string();
        let raw = crate::host::call("asset_signed_url", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `signed_url`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn signed_url_as<T: ::serde::de::DeserializeOwned>(workspace: &str, node_ref: &str, options: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(node_ref)?,
            ::serde_json::to_value(options)?,
        ])
        .to_string();
        let raw = crate::host::call("asset_signed_url", &args)?;
        crate::wire::decode_json_as(&raw)
    }

}

pub mod branches {
    /// `raisin.branches.compare` — registry method `branches_compare`.
    pub fn compare(branch: &str, base_branch: &str) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(branch)?,
            ::serde_json::to_value(base_branch)?,
        ])
        .to_string();
        let raw = crate::host::call("branches_compare", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `compare`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn compare_as<T: ::serde::de::DeserializeOwned>(branch: &str, base_branch: &str) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(branch)?,
            ::serde_json::to_value(base_branch)?,
        ])
        .to_string();
        let raw = crate::host::call("branches_compare", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.branches.copyNodes` — registry method `branches_copyNodes`.
    pub fn copy_nodes(source_branch: &str, target_branch: &str, opts: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(source_branch)?,
            ::serde_json::to_value(target_branch)?,
            ::serde_json::to_value(opts)?,
        ])
        .to_string();
        let raw = crate::host::call("branches_copyNodes", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `copy_nodes`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn copy_nodes_as<T: ::serde::de::DeserializeOwned>(source_branch: &str, target_branch: &str, opts: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(source_branch)?,
            ::serde_json::to_value(target_branch)?,
            ::serde_json::to_value(opts)?,
        ])
        .to_string();
        let raw = crate::host::call("branches_copyNodes", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.branches.diff` — registry method `branches_diff`.
    pub fn diff(branch: &str, base_branch: &str) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(branch)?,
            ::serde_json::to_value(base_branch)?,
        ])
        .to_string();
        let raw = crate::host::call("branches_diff", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `diff`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn diff_as<T: ::serde::de::DeserializeOwned>(branch: &str, base_branch: &str) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(branch)?,
            ::serde_json::to_value(base_branch)?,
        ])
        .to_string();
        let raw = crate::host::call("branches_diff", &args)?;
        crate::wire::decode_json_as(&raw)
    }

}

pub mod crypto {
    /// `raisin.crypto.generateKeyPair` — registry method `crypto_generate_key_pair`.
    pub fn generate_key_pair(alg: Option<&str>) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(alg)?,
        ])
        .to_string();
        let raw = crate::host::call("crypto_generate_key_pair", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `generate_key_pair`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn generate_key_pair_as<T: ::serde::de::DeserializeOwned>(alg: Option<&str>) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(alg)?,
        ])
        .to_string();
        let raw = crate::host::call("crypto_generate_key_pair", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.crypto.hash` — registry method `crypto_hash`.
    pub fn hash(input: &str, alg: Option<&str>) -> crate::Result<String> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(input)?,
            ::serde_json::to_value(alg)?,
        ])
        .to_string();
        let raw = crate::host::call("crypto_hash", &args)?;
        crate::wire::decode_string(&raw)
    }

    /// `raisin.crypto.randomBytes` — registry method `crypto_random_bytes`.
    pub fn random_bytes(n: u32) -> crate::Result<String> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(n)?,
        ])
        .to_string();
        let raw = crate::host::call("crypto_random_bytes", &args)?;
        crate::wire::decode_string(&raw)
    }

    /// `raisin.crypto.signJwt` — registry method `crypto_sign_jwt`.
    pub fn sign_jwt(claims: impl ::serde::Serialize, private_jwk: impl ::serde::Serialize, opts: Option<::serde_json::Value>) -> crate::Result<String> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(claims)?,
            ::serde_json::to_value(private_jwk)?,
            ::serde_json::to_value(opts)?,
        ])
        .to_string();
        let raw = crate::host::call("crypto_sign_jwt", &args)?;
        crate::wire::decode_string(&raw)
    }

    /// `raisin.crypto.uuid` — registry method `crypto_uuid`.
    pub fn uuid() -> crate::Result<String> {
        let args = "[]".to_string();
        let raw = crate::host::call("crypto_uuid", &args)?;
        crate::wire::decode_string(&raw)
    }

    /// `raisin.crypto.verifyJwt` — registry method `crypto_verify_jwt`.
    pub fn verify_jwt(token: &str, opts: Option<::serde_json::Value>) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(token)?,
            ::serde_json::to_value(opts)?,
        ])
        .to_string();
        let raw = crate::host::call("crypto_verify_jwt", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `verify_jwt`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn verify_jwt_as<T: ::serde::de::DeserializeOwned>(token: &str, opts: Option<::serde_json::Value>) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(token)?,
            ::serde_json::to_value(opts)?,
        ])
        .to_string();
        let raw = crate::host::call("crypto_verify_jwt", &args)?;
        crate::wire::decode_json_as(&raw)
    }

}

pub mod date {
    /// `raisin.date.addDays` — registry method `date_addDays`.
    pub fn add_days(timestamp: i64, days: i64) -> crate::Result<i64> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(timestamp)?,
            ::serde_json::to_value(days)?,
        ])
        .to_string();
        let raw = crate::host::call("date_addDays", &args)?;
        crate::wire::decode_i64(&raw)
    }

    /// `raisin.date.diffDays` — registry method `date_diffDays`.
    pub fn diff_days(ts1: i64, ts2: i64) -> crate::Result<i64> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(ts1)?,
            ::serde_json::to_value(ts2)?,
        ])
        .to_string();
        let raw = crate::host::call("date_diffDays", &args)?;
        crate::wire::decode_i64(&raw)
    }

    /// `raisin.date.format` — registry method `date_format`.
    pub fn format(timestamp: i64, format: Option<&str>) -> crate::Result<String> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(timestamp)?,
            ::serde_json::to_value(format)?,
        ])
        .to_string();
        let raw = crate::host::call("date_format", &args)?;
        crate::wire::decode_string(&raw)
    }

    /// `raisin.date.now` — registry method `date_now`.
    pub fn now() -> crate::Result<String> {
        let args = "[]".to_string();
        let raw = crate::host::call("date_now", &args)?;
        crate::wire::decode_string(&raw)
    }

    /// `raisin.date.parse` — registry method `date_parse`.
    pub fn parse(date_str: &str, format: Option<&str>) -> crate::Result<i64> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(date_str)?,
            ::serde_json::to_value(format)?,
        ])
        .to_string();
        let raw = crate::host::call("date_parse", &args)?;
        crate::wire::decode_i64(&raw)
    }

    /// `raisin.date.timestamp` — registry method `date_timestamp`.
    pub fn timestamp() -> crate::Result<i64> {
        let args = "[]".to_string();
        let raw = crate::host::call("date_timestamp", &args)?;
        crate::wire::decode_i64(&raw)
    }

    /// `raisin.date.timestampMillis` — registry method `date_timestampMillis`.
    pub fn timestamp_millis() -> crate::Result<i64> {
        let args = "[]".to_string();
        let raw = crate::host::call("date_timestampMillis", &args)?;
        crate::wire::decode_i64(&raw)
    }

}

pub mod email {
    /// `raisin.email.providers` — registry method `email_providers`.
    pub fn providers() -> crate::Result<::serde_json::Value> {
        let args = "[]".to_string();
        let raw = crate::host::call("email_providers", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `providers`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn providers_as<T: ::serde::de::DeserializeOwned>() -> crate::Result<T> {
        let args = "[]".to_string();
        let raw = crate::host::call("email_providers", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.email.send` — registry method `email_send`.
    pub fn send(message: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(message)?,
        ])
        .to_string();
        let raw = crate::host::call("email_send", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `send`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn send_as<T: ::serde::de::DeserializeOwned>(message: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(message)?,
        ])
        .to_string();
        let raw = crate::host::call("email_send", &args)?;
        crate::wire::decode_json_as(&raw)
    }

}

pub mod events {
    /// `raisin.events.emit` — registry method `events_emit`.
    pub fn emit(event_type: &str, data: impl ::serde::Serialize) -> crate::Result<()> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(event_type)?,
            ::serde_json::to_value(data)?,
        ])
        .to_string();
        let raw = crate::host::call("events_emit", &args)?;
        crate::wire::decode_void(&raw)
    }

}

pub mod flows {
    /// `raisin.flows.run` — registry method `flows_run`.
    pub fn run(flow_path: &str, input: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(flow_path)?,
            ::serde_json::to_value(input)?,
        ])
        .to_string();
        let raw = crate::host::call("flows_run", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `run`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn run_as<T: ::serde::de::DeserializeOwned>(flow_path: &str, input: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(flow_path)?,
            ::serde_json::to_value(input)?,
        ])
        .to_string();
        let raw = crate::host::call("flows_run", &args)?;
        crate::wire::decode_json_as(&raw)
    }

}

pub mod functions {
    /// `raisin.functions.call` — registry method `functions_call`.
    pub fn call(function_path: &str, arguments: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(function_path)?,
            ::serde_json::to_value(arguments)?,
        ])
        .to_string();
        let raw = crate::host::call("functions_call", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `call`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn call_as<T: ::serde::de::DeserializeOwned>(function_path: &str, arguments: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(function_path)?,
            ::serde_json::to_value(arguments)?,
        ])
        .to_string();
        let raw = crate::host::call("functions_call", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.functions.execute` — registry method `functions_execute`.
    pub fn execute(function_path: &str, arguments: impl ::serde::Serialize, context: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(function_path)?,
            ::serde_json::to_value(arguments)?,
            ::serde_json::to_value(context)?,
        ])
        .to_string();
        let raw = crate::host::call("functions_execute", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `execute`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn execute_as<T: ::serde::de::DeserializeOwned>(function_path: &str, arguments: impl ::serde::Serialize, context: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(function_path)?,
            ::serde_json::to_value(arguments)?,
            ::serde_json::to_value(context)?,
        ])
        .to_string();
        let raw = crate::host::call("functions_execute", &args)?;
        crate::wire::decode_json_as(&raw)
    }

}

pub mod http {
    /// `raisin.http.request` — registry method `http_request`.
    pub fn request(method: &str, url: &str, options: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(method)?,
            ::serde_json::to_value(url)?,
            ::serde_json::to_value(options)?,
        ])
        .to_string();
        let raw = crate::host::call("http_request", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `request`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn request_as<T: ::serde::de::DeserializeOwned>(method: &str, url: &str, options: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(method)?,
            ::serde_json::to_value(url)?,
            ::serde_json::to_value(options)?,
        ])
        .to_string();
        let raw = crate::host::call("http_request", &args)?;
        crate::wire::decode_json_as(&raw)
    }

}

pub mod identities {
    /// `raisin.identities.findByEmail` — registry method `identities_findByEmail`.
    pub fn find_by_email(email: &str) -> crate::Result<Option<::serde_json::Value>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(email)?,
        ])
        .to_string();
        let raw = crate::host::call("identities_findByEmail", &args)?;
        crate::wire::decode_optional_json(&raw)
    }

    /// Typed form of `find_by_email`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn find_by_email_as<T: ::serde::de::DeserializeOwned>(email: &str) -> crate::Result<Option<T>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(email)?,
        ])
        .to_string();
        let raw = crate::host::call("identities_findByEmail", &args)?;
        crate::wire::decode_optional_json_as(&raw)
    }

    /// `raisin.identities.update` — registry method `identities_update`.
    pub fn update(id: &str, patch: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(id)?,
            ::serde_json::to_value(patch)?,
        ])
        .to_string();
        let raw = crate::host::call("identities_update", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `update`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn update_as<T: ::serde::de::DeserializeOwned>(id: &str, patch: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(id)?,
            ::serde_json::to_value(patch)?,
        ])
        .to_string();
        let raw = crate::host::call("identities_update", &args)?;
        crate::wire::decode_json_as(&raw)
    }

}

pub mod imap {
    /// `raisin.imap.fetchMessage` — registry method `imap_fetch_message`.
    pub fn fetch_message(conn: impl ::serde::Serialize, uid: i64, opts: Option<::serde_json::Value>) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(conn)?,
            ::serde_json::to_value(uid)?,
            ::serde_json::to_value(opts)?,
        ])
        .to_string();
        let raw = crate::host::call("imap_fetch_message", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `fetch_message`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn fetch_message_as<T: ::serde::de::DeserializeOwned>(conn: impl ::serde::Serialize, uid: i64, opts: Option<::serde_json::Value>) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(conn)?,
            ::serde_json::to_value(uid)?,
            ::serde_json::to_value(opts)?,
        ])
        .to_string();
        let raw = crate::host::call("imap_fetch_message", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.imap.fetchSince` — registry method `imap_fetch_since`.
    pub fn fetch_since(conn: impl ::serde::Serialize, since_uid: i64, opts: Option<::serde_json::Value>) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(conn)?,
            ::serde_json::to_value(since_uid)?,
            ::serde_json::to_value(opts)?,
        ])
        .to_string();
        let raw = crate::host::call("imap_fetch_since", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `fetch_since`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn fetch_since_as<T: ::serde::de::DeserializeOwned>(conn: impl ::serde::Serialize, since_uid: i64, opts: Option<::serde_json::Value>) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(conn)?,
            ::serde_json::to_value(since_uid)?,
            ::serde_json::to_value(opts)?,
        ])
        .to_string();
        let raw = crate::host::call("imap_fetch_since", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.imap.listMailboxes` — registry method `imap_list_mailboxes`.
    pub fn list_mailboxes(conn: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(conn)?,
        ])
        .to_string();
        let raw = crate::host::call("imap_list_mailboxes", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `list_mailboxes`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn list_mailboxes_as<T: ::serde::de::DeserializeOwned>(conn: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(conn)?,
        ])
        .to_string();
        let raw = crate::host::call("imap_list_mailboxes", &args)?;
        crate::wire::decode_json_as(&raw)
    }

}

pub mod integrations {
    /// `raisin.integrations.syncNow` — registry method `integrations_sync_now`.
    pub fn sync_now(mount_id: &str, mode: Option<&str>) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(mount_id)?,
            ::serde_json::to_value(mode)?,
        ])
        .to_string();
        let raw = crate::host::call("integrations_sync_now", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `sync_now`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn sync_now_as<T: ::serde::de::DeserializeOwned>(mount_id: &str, mode: Option<&str>) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(mount_id)?,
            ::serde_json::to_value(mode)?,
        ])
        .to_string();
        let raw = crate::host::call("integrations_sync_now", &args)?;
        crate::wire::decode_json_as(&raw)
    }

}

pub mod inventory {
    /// `raisin.inventory.claim` — registry method `inventory_claim`.
    pub fn claim(pool: &str, n: i64, capacity: i64) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(pool)?,
            ::serde_json::to_value(n)?,
            ::serde_json::to_value(capacity)?,
        ])
        .to_string();
        let raw = crate::host::call("inventory_claim", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `claim`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn claim_as<T: ::serde::de::DeserializeOwned>(pool: &str, n: i64, capacity: i64) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(pool)?,
            ::serde_json::to_value(n)?,
            ::serde_json::to_value(capacity)?,
        ])
        .to_string();
        let raw = crate::host::call("inventory_claim", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.inventory.release` — registry method `inventory_release`.
    pub fn release(pool: &str, n: i64) -> crate::Result<i64> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(pool)?,
            ::serde_json::to_value(n)?,
        ])
        .to_string();
        let raw = crate::host::call("inventory_release", &args)?;
        crate::wire::decode_i64(&raw)
    }

}

pub mod locks {
    /// `raisin.locks.acquire` — registry method `locks_acquire`.
    pub fn acquire(key: &str, ttl_ms: i64, owner: Option<&str>) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(key)?,
            ::serde_json::to_value(ttl_ms)?,
            ::serde_json::to_value(owner)?,
        ])
        .to_string();
        let raw = crate::host::call("locks_acquire", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `acquire`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn acquire_as<T: ::serde::de::DeserializeOwned>(key: &str, ttl_ms: i64, owner: Option<&str>) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(key)?,
            ::serde_json::to_value(ttl_ms)?,
            ::serde_json::to_value(owner)?,
        ])
        .to_string();
        let raw = crate::host::call("locks_acquire", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.locks.release` — registry method `locks_release`.
    pub fn release(key: &str, token: i64) -> crate::Result<bool> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(key)?,
            ::serde_json::to_value(token)?,
        ])
        .to_string();
        let raw = crate::host::call("locks_release", &args)?;
        crate::wire::decode_bool(&raw)
    }

    /// `raisin.locks.renew` — registry method `locks_renew`.
    pub fn renew(key: &str, token: i64, ttl_ms: i64) -> crate::Result<bool> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(key)?,
            ::serde_json::to_value(token)?,
            ::serde_json::to_value(ttl_ms)?,
        ])
        .to_string();
        let raw = crate::host::call("locks_renew", &args)?;
        crate::wire::decode_bool(&raw)
    }

}

pub mod nodes {
    /// `raisin.nodes.addResource` — registry method `nodes_addResource`.
    pub fn add_resource(workspace: &str, node_path: &str, property_path: &str, upload_data: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(node_path)?,
            ::serde_json::to_value(property_path)?,
            ::serde_json::to_value(upload_data)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_addResource", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `add_resource`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn add_resource_as<T: ::serde::de::DeserializeOwned>(workspace: &str, node_path: &str, property_path: &str, upload_data: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(node_path)?,
            ::serde_json::to_value(property_path)?,
            ::serde_json::to_value(upload_data)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_addResource", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.nodes.applyChildOrder` — registry method `nodes_applyChildOrder`.
    pub fn apply_child_order(workspace: &str, parent_path: &str, source_branch: &str, target_branch: &str) -> crate::Result<()> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(parent_path)?,
            ::serde_json::to_value(source_branch)?,
            ::serde_json::to_value(target_branch)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_applyChildOrder", &args)?;
        crate::wire::decode_void(&raw)
    }

    /// `raisin.nodes.create` — registry method `nodes_create`.
    pub fn create(workspace: &str, parent_path: &str, data: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(parent_path)?,
            ::serde_json::to_value(data)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_create", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `create`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn create_as<T: ::serde::de::DeserializeOwned>(workspace: &str, parent_path: &str, data: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(parent_path)?,
            ::serde_json::to_value(data)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_create", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.nodes.delete` — registry method `nodes_delete`.
    pub fn delete(workspace: &str, path: &str) -> crate::Result<()> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(path)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_delete", &args)?;
        crate::wire::decode_void(&raw)
    }

    /// `raisin.nodes.get` — registry method `nodes_get`.
    pub fn get(workspace: &str, path: &str) -> crate::Result<Option<::serde_json::Value>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(path)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_get", &args)?;
        crate::wire::decode_optional_json(&raw)
    }

    /// Typed form of `get`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn get_as<T: ::serde::de::DeserializeOwned>(workspace: &str, path: &str) -> crate::Result<Option<T>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(path)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_get", &args)?;
        crate::wire::decode_optional_json_as(&raw)
    }

    /// `raisin.nodes.getById` — registry method `nodes_getById`.
    pub fn get_by_id(workspace: &str, id: &str) -> crate::Result<Option<::serde_json::Value>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(id)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_getById", &args)?;
        crate::wire::decode_optional_json(&raw)
    }

    /// Typed form of `get_by_id`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn get_by_id_as<T: ::serde::de::DeserializeOwned>(workspace: &str, id: &str) -> crate::Result<Option<T>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(id)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_getById", &args)?;
        crate::wire::decode_optional_json_as(&raw)
    }

    /// `raisin.nodes.getChildren` — registry method `nodes_getChildren`.
    pub fn get_children(workspace: &str, parent_path: &str, limit: Option<u32>) -> crate::Result<Vec<::serde_json::Value>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(parent_path)?,
            ::serde_json::to_value(limit)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_getChildren", &args)?;
        crate::wire::decode_json_array(&raw)
    }

    /// Typed form of `get_children`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn get_children_as<T: ::serde::de::DeserializeOwned>(workspace: &str, parent_path: &str, limit: Option<u32>) -> crate::Result<Vec<T>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(parent_path)?,
            ::serde_json::to_value(limit)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_getChildren", &args)?;
        crate::wire::decode_json_array_as(&raw)
    }

    /// `raisin.nodes.history` — registry method `nodes_history`.
    pub fn history(workspace: &str, id: &str, limit: Option<u32>) -> crate::Result<Vec<::serde_json::Value>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(id)?,
            ::serde_json::to_value(limit)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_history", &args)?;
        crate::wire::decode_json_array(&raw)
    }

    /// Typed form of `history`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn history_as<T: ::serde::de::DeserializeOwned>(workspace: &str, id: &str, limit: Option<u32>) -> crate::Result<Vec<T>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(id)?,
            ::serde_json::to_value(limit)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_history", &args)?;
        crate::wire::decode_json_array_as(&raw)
    }

    /// `raisin.nodes.move` — registry method `nodes_move`.
    pub fn r#move(workspace: &str, node_path: &str, new_parent_path: &str) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(node_path)?,
            ::serde_json::to_value(new_parent_path)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_move", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `r#move`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn move_as<T: ::serde::de::DeserializeOwned>(workspace: &str, node_path: &str, new_parent_path: &str) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(node_path)?,
            ::serde_json::to_value(new_parent_path)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_move", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.nodes.moveChildAfter` — registry method `nodes_moveChildAfter`.
    pub fn move_child_after(workspace: &str, parent_path: &str, child_name: &str, after_child_name: &str) -> crate::Result<()> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(parent_path)?,
            ::serde_json::to_value(child_name)?,
            ::serde_json::to_value(after_child_name)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_moveChildAfter", &args)?;
        crate::wire::decode_void(&raw)
    }

    /// `raisin.nodes.moveChildBefore` — registry method `nodes_moveChildBefore`.
    pub fn move_child_before(workspace: &str, parent_path: &str, child_name: &str, before_child_name: &str) -> crate::Result<()> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(parent_path)?,
            ::serde_json::to_value(child_name)?,
            ::serde_json::to_value(before_child_name)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_moveChildBefore", &args)?;
        crate::wire::decode_void(&raw)
    }

    /// `raisin.nodes.query` — registry method `nodes_query`.
    pub fn query(workspace: &str, query: impl ::serde::Serialize) -> crate::Result<Vec<::serde_json::Value>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(query)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_query", &args)?;
        crate::wire::decode_json_array(&raw)
    }

    /// Typed form of `query`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn query_as<T: ::serde::de::DeserializeOwned>(workspace: &str, query: impl ::serde::Serialize) -> crate::Result<Vec<T>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(query)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_query", &args)?;
        crate::wire::decode_json_array_as(&raw)
    }

    /// `raisin.nodes.reorderChild` — registry method `nodes_reorderChild`.
    pub fn reorder_child(workspace: &str, parent_path: &str, child_name: &str, position: u32) -> crate::Result<()> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(parent_path)?,
            ::serde_json::to_value(child_name)?,
            ::serde_json::to_value(position)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_reorderChild", &args)?;
        crate::wire::decode_void(&raw)
    }

    /// `raisin.nodes.update` — registry method `nodes_update`.
    pub fn update(workspace: &str, path: &str, data: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(path)?,
            ::serde_json::to_value(data)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_update", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `update`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn update_as<T: ::serde::de::DeserializeOwned>(workspace: &str, path: &str, data: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(path)?,
            ::serde_json::to_value(data)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_update", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.nodes.updateProperty` — registry method `nodes_updateProperty`.
    pub fn update_property(workspace: &str, node_path: &str, property_path: &str, value: impl ::serde::Serialize) -> crate::Result<()> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(node_path)?,
            ::serde_json::to_value(property_path)?,
            ::serde_json::to_value(value)?,
        ])
        .to_string();
        let raw = crate::host::call("nodes_updateProperty", &args)?;
        crate::wire::decode_void(&raw)
    }

}

pub mod notify {
    /// `raisin.notify.notify` — registry method `notify_send`.
    pub fn notify(options: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(options)?,
        ])
        .to_string();
        let raw = crate::host::call("notify_send", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `notify`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn notify_as<T: ::serde::de::DeserializeOwned>(options: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(options)?,
        ])
        .to_string();
        let raw = crate::host::call("notify_send", &args)?;
        crate::wire::decode_json_as(&raw)
    }

}

pub mod ocr {
    /// `raisin.ocr.image` — registry method `ocr_image`.
    pub fn image(base64_data: &str, options: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(base64_data)?,
            ::serde_json::to_value(options)?,
        ])
        .to_string();
        let raw = crate::host::call("ocr_image", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `image`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn image_as<T: ::serde::de::DeserializeOwned>(base64_data: &str, options: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(base64_data)?,
            ::serde_json::to_value(options)?,
        ])
        .to_string();
        let raw = crate::host::call("ocr_image", &args)?;
        crate::wire::decode_json_as(&raw)
    }

}

pub mod pdf {
    /// `raisin.pdf.extractText` — registry method `pdf_extractText`.
    pub fn extract_text(base64_data: &str) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(base64_data)?,
        ])
        .to_string();
        let raw = crate::host::call("pdf_extractText", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `extract_text`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn extract_text_as<T: ::serde::de::DeserializeOwned>(base64_data: &str) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(base64_data)?,
        ])
        .to_string();
        let raw = crate::host::call("pdf_extractText", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.pdf.getPageCount` — registry method `pdf_getPageCount`.
    pub fn get_page_count(base64_data: &str) -> crate::Result<i64> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(base64_data)?,
        ])
        .to_string();
        let raw = crate::host::call("pdf_getPageCount", &args)?;
        crate::wire::decode_i64(&raw)
    }

    /// `raisin.pdf.ocr` — registry method `pdf_ocr`.
    pub fn ocr(base64_data: &str, options: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(base64_data)?,
            ::serde_json::to_value(options)?,
        ])
        .to_string();
        let raw = crate::host::call("pdf_ocr", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `ocr`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn ocr_as<T: ::serde::de::DeserializeOwned>(base64_data: &str, options: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(base64_data)?,
            ::serde_json::to_value(options)?,
        ])
        .to_string();
        let raw = crate::host::call("pdf_ocr", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.pdf.processFromStorage` — registry method `pdf_processFromStorage`.
    pub fn process_from_storage(storage_key: &str, options: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(storage_key)?,
            ::serde_json::to_value(options)?,
        ])
        .to_string();
        let raw = crate::host::call("pdf_processFromStorage", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `process_from_storage`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn process_from_storage_as<T: ::serde::de::DeserializeOwned>(storage_key: &str, options: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(storage_key)?,
            ::serde_json::to_value(options)?,
        ])
        .to_string();
        let raw = crate::host::call("pdf_processFromStorage", &args)?;
        crate::wire::decode_json_as(&raw)
    }

}

pub mod platform {
    /// `raisin.platform.hook` — registry method `platform_hook`.
    pub fn hook(name: &str, payload: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(name)?,
            ::serde_json::to_value(payload)?,
        ])
        .to_string();
        let raw = crate::host::call("platform_hook", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `hook`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn hook_as<T: ::serde::de::DeserializeOwned>(name: &str, payload: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(name)?,
            ::serde_json::to_value(payload)?,
        ])
        .to_string();
        let raw = crate::host::call("platform_hook", &args)?;
        crate::wire::decode_json_as(&raw)
    }

}

pub mod resources {
    /// `raisin.resources.getBinary` — registry method `resources_getBinary`.
    pub fn get_binary(storage_key: &str) -> crate::Result<String> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(storage_key)?,
        ])
        .to_string();
        let raw = crate::host::call("resources_getBinary", &args)?;
        crate::wire::decode_string(&raw)
    }

}

pub mod scheduler {
    /// `raisin.scheduler.cancel` — registry method `scheduler_cancel`.
    pub fn cancel(job_id_or_key: &str) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(job_id_or_key)?,
        ])
        .to_string();
        let raw = crate::host::call("scheduler_cancel", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `cancel`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn cancel_as<T: ::serde::de::DeserializeOwned>(job_id_or_key: &str) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(job_id_or_key)?,
        ])
        .to_string();
        let raw = crate::host::call("scheduler_cancel", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.scheduler.get` — registry method `scheduler_get`.
    pub fn get(job_id_or_key: &str) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(job_id_or_key)?,
        ])
        .to_string();
        let raw = crate::host::call("scheduler_get", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `get`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn get_as<T: ::serde::de::DeserializeOwned>(job_id_or_key: &str) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(job_id_or_key)?,
        ])
        .to_string();
        let raw = crate::host::call("scheduler_get", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.scheduler.list` — registry method `scheduler_list`.
    pub fn list(filter: Option<::serde_json::Value>) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(filter)?,
        ])
        .to_string();
        let raw = crate::host::call("scheduler_list", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `list`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn list_as<T: ::serde::de::DeserializeOwned>(filter: Option<::serde_json::Value>) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(filter)?,
        ])
        .to_string();
        let raw = crate::host::call("scheduler_list", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.scheduler.schedule` — registry method `scheduler_schedule`.
    pub fn schedule(request: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(request)?,
        ])
        .to_string();
        let raw = crate::host::call("scheduler_schedule", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `schedule`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn schedule_as<T: ::serde::de::DeserializeOwned>(request: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(request)?,
        ])
        .to_string();
        let raw = crate::host::call("scheduler_schedule", &args)?;
        crate::wire::decode_json_as(&raw)
    }

}

pub mod secrets {
    /// `raisin.secrets.delete` — registry method `secrets_delete`.
    pub fn delete(name: &str) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(name)?,
        ])
        .to_string();
        let raw = crate::host::call("secrets_delete", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `delete`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn delete_as<T: ::serde::de::DeserializeOwned>(name: &str) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(name)?,
        ])
        .to_string();
        let raw = crate::host::call("secrets_delete", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.secrets.get` — registry method `secrets_get`.
    pub fn get(name: &str, version: Option<i64>) -> crate::Result<String> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(name)?,
            ::serde_json::to_value(version)?,
        ])
        .to_string();
        let raw = crate::host::call("secrets_get", &args)?;
        crate::wire::decode_string(&raw)
    }

    /// `raisin.secrets.list` — registry method `secrets_list`.
    pub fn list() -> crate::Result<Vec<::serde_json::Value>> {
        let args = "[]".to_string();
        let raw = crate::host::call("secrets_list", &args)?;
        crate::wire::decode_json_array(&raw)
    }

    /// Typed form of `list`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn list_as<T: ::serde::de::DeserializeOwned>() -> crate::Result<Vec<T>> {
        let args = "[]".to_string();
        let raw = crate::host::call("secrets_list", &args)?;
        crate::wire::decode_json_array_as(&raw)
    }

    /// `raisin.secrets.put` — registry method `secrets_put`.
    pub fn put(name: &str, value: &str) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(name)?,
            ::serde_json::to_value(value)?,
        ])
        .to_string();
        let raw = crate::host::call("secrets_put", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `put`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn put_as<T: ::serde::de::DeserializeOwned>(name: &str, value: &str) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(name)?,
            ::serde_json::to_value(value)?,
        ])
        .to_string();
        let raw = crate::host::call("secrets_put", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.secrets.resolve` — registry method `secrets_resolve`.
    pub fn resolve(value: &str) -> crate::Result<String> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(value)?,
        ])
        .to_string();
        let raw = crate::host::call("secrets_resolve", &args)?;
        crate::wire::decode_string(&raw)
    }

    /// `raisin.secrets.rotate` — registry method `secrets_rotate`.
    pub fn rotate(name: &str, value: &str) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(name)?,
            ::serde_json::to_value(value)?,
        ])
        .to_string();
        let raw = crate::host::call("secrets_rotate", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `rotate`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn rotate_as<T: ::serde::de::DeserializeOwned>(name: &str, value: &str) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(name)?,
            ::serde_json::to_value(value)?,
        ])
        .to_string();
        let raw = crate::host::call("secrets_rotate", &args)?;
        crate::wire::decode_json_as(&raw)
    }

}

pub mod sql {
    /// `raisin.sql.execute` — registry method `sql_execute`.
    pub fn execute(sql: &str, params: &[::serde_json::Value]) -> crate::Result<i64> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(sql)?,
            ::serde_json::to_value(params)?,
        ])
        .to_string();
        let raw = crate::host::call("sql_execute", &args)?;
        crate::wire::decode_i64(&raw)
    }

    /// `raisin.sql.query` — registry method `sql_query`.
    pub fn query(sql: &str, params: &[::serde_json::Value]) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(sql)?,
            ::serde_json::to_value(params)?,
        ])
        .to_string();
        let raw = crate::host::call("sql_query", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `query`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn query_as<T: ::serde::de::DeserializeOwned>(sql: &str, params: &[::serde_json::Value]) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(sql)?,
            ::serde_json::to_value(params)?,
        ])
        .to_string();
        let raw = crate::host::call("sql_query", &args)?;
        crate::wire::decode_json_as(&raw)
    }

}

pub mod tasks {
    /// `raisin.tasks.complete` — registry method `tasks_complete`.
    pub fn complete(task_id: &str, response: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(task_id)?,
            ::serde_json::to_value(response)?,
        ])
        .to_string();
        let raw = crate::host::call("tasks_complete", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `complete`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn complete_as<T: ::serde::de::DeserializeOwned>(task_id: &str, response: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(task_id)?,
            ::serde_json::to_value(response)?,
        ])
        .to_string();
        let raw = crate::host::call("tasks_complete", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.tasks.create` — registry method `tasks_create`.
    pub fn create(request: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(request)?,
        ])
        .to_string();
        let raw = crate::host::call("tasks_create", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `create`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn create_as<T: ::serde::de::DeserializeOwned>(request: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(request)?,
        ])
        .to_string();
        let raw = crate::host::call("tasks_create", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.tasks.query` — registry method `tasks_query`.
    pub fn query(query: impl ::serde::Serialize) -> crate::Result<Vec<::serde_json::Value>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(query)?,
        ])
        .to_string();
        let raw = crate::host::call("tasks_query", &args)?;
        crate::wire::decode_json_array(&raw)
    }

    /// Typed form of `query`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn query_as<T: ::serde::de::DeserializeOwned>(query: impl ::serde::Serialize) -> crate::Result<Vec<T>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(query)?,
        ])
        .to_string();
        let raw = crate::host::call("tasks_query", &args)?;
        crate::wire::decode_json_array_as(&raw)
    }

    /// `raisin.tasks.update` — registry method `tasks_update`.
    pub fn update(task_id: &str, updates: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(task_id)?,
            ::serde_json::to_value(updates)?,
        ])
        .to_string();
        let raw = crate::host::call("tasks_update", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `update`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn update_as<T: ::serde::de::DeserializeOwned>(task_id: &str, updates: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(task_id)?,
            ::serde_json::to_value(updates)?,
        ])
        .to_string();
        let raw = crate::host::call("tasks_update", &args)?;
        crate::wire::decode_json_as(&raw)
    }

}

pub mod tx {
    /// `raisin.tx.add` — registry method `tx_add`.
    pub fn add(tx_id: &str, workspace: &str, data: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(data)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_add", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `add`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn add_as<T: ::serde::de::DeserializeOwned>(tx_id: &str, workspace: &str, data: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(data)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_add", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.tx.begin` — registry method `tx_begin`.
    pub fn begin() -> crate::Result<String> {
        let args = "[]".to_string();
        let raw = crate::host::call("tx_begin", &args)?;
        crate::wire::decode_string(&raw)
    }

    /// `raisin.tx.commit` — registry method `tx_commit`.
    pub fn commit(tx_id: &str) -> crate::Result<()> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_commit", &args)?;
        crate::wire::decode_void(&raw)
    }

    /// `raisin.tx.create` — registry method `tx_create`.
    pub fn create(tx_id: &str, workspace: &str, parent_path: &str, data: impl ::serde::Serialize) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(parent_path)?,
            ::serde_json::to_value(data)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_create", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `create`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn create_as<T: ::serde::de::DeserializeOwned>(tx_id: &str, workspace: &str, parent_path: &str, data: impl ::serde::Serialize) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(parent_path)?,
            ::serde_json::to_value(data)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_create", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.tx.createDeep` — registry method `tx_createDeep`.
    pub fn create_deep(tx_id: &str, workspace: &str, parent_path: &str, data: impl ::serde::Serialize, parent_node_type: &str) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(parent_path)?,
            ::serde_json::to_value(data)?,
            ::serde_json::to_value(parent_node_type)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_createDeep", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `create_deep`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn create_deep_as<T: ::serde::de::DeserializeOwned>(tx_id: &str, workspace: &str, parent_path: &str, data: impl ::serde::Serialize, parent_node_type: &str) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(parent_path)?,
            ::serde_json::to_value(data)?,
            ::serde_json::to_value(parent_node_type)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_createDeep", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.tx.delete` — registry method `tx_delete`.
    pub fn delete(tx_id: &str, workspace: &str, path: &str) -> crate::Result<()> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(path)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_delete", &args)?;
        crate::wire::decode_void(&raw)
    }

    /// `raisin.tx.deleteById` — registry method `tx_deleteById`.
    pub fn delete_by_id(tx_id: &str, workspace: &str, id: &str) -> crate::Result<()> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(id)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_deleteById", &args)?;
        crate::wire::decode_void(&raw)
    }

    /// `raisin.tx.get` — registry method `tx_get`.
    pub fn get(tx_id: &str, workspace: &str, id: &str) -> crate::Result<Option<::serde_json::Value>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(id)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_get", &args)?;
        crate::wire::decode_optional_json(&raw)
    }

    /// Typed form of `get`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn get_as<T: ::serde::de::DeserializeOwned>(tx_id: &str, workspace: &str, id: &str) -> crate::Result<Option<T>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(id)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_get", &args)?;
        crate::wire::decode_optional_json_as(&raw)
    }

    /// `raisin.tx.getByPath` — registry method `tx_getByPath`.
    pub fn get_by_path(tx_id: &str, workspace: &str, path: &str) -> crate::Result<Option<::serde_json::Value>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(path)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_getByPath", &args)?;
        crate::wire::decode_optional_json(&raw)
    }

    /// Typed form of `get_by_path`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn get_by_path_as<T: ::serde::de::DeserializeOwned>(tx_id: &str, workspace: &str, path: &str) -> crate::Result<Option<T>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(path)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_getByPath", &args)?;
        crate::wire::decode_optional_json_as(&raw)
    }

    /// `raisin.tx.listChildren` — registry method `tx_listChildren`.
    pub fn list_children(tx_id: &str, workspace: &str, parent_path: &str) -> crate::Result<Vec<::serde_json::Value>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(parent_path)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_listChildren", &args)?;
        crate::wire::decode_json_array(&raw)
    }

    /// Typed form of `list_children`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn list_children_as<T: ::serde::de::DeserializeOwned>(tx_id: &str, workspace: &str, parent_path: &str) -> crate::Result<Vec<T>> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(parent_path)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_listChildren", &args)?;
        crate::wire::decode_json_array_as(&raw)
    }

    /// `raisin.tx.move` — registry method `tx_move`.
    pub fn r#move(tx_id: &str, workspace: &str, node_path: &str, new_parent_path: &str) -> crate::Result<::serde_json::Value> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(node_path)?,
            ::serde_json::to_value(new_parent_path)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_move", &args)?;
        crate::wire::decode_json(&raw)
    }

    /// Typed form of `r#move`. `T` is inferred from the binding site
    /// (turbofish is unavailable when the method takes a JSON argument).
    pub fn move_as<T: ::serde::de::DeserializeOwned>(tx_id: &str, workspace: &str, node_path: &str, new_parent_path: &str) -> crate::Result<T> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(node_path)?,
            ::serde_json::to_value(new_parent_path)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_move", &args)?;
        crate::wire::decode_json_as(&raw)
    }

    /// `raisin.tx.put` — registry method `tx_put`.
    pub fn put(tx_id: &str, workspace: &str, data: impl ::serde::Serialize) -> crate::Result<()> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(data)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_put", &args)?;
        crate::wire::decode_void(&raw)
    }

    /// `raisin.tx.rollback` — registry method `tx_rollback`.
    pub fn rollback(tx_id: &str) -> crate::Result<()> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_rollback", &args)?;
        crate::wire::decode_void(&raw)
    }

    /// `raisin.tx.setActor` — registry method `tx_setActor`.
    pub fn set_actor(tx_id: &str, actor: &str) -> crate::Result<()> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(actor)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_setActor", &args)?;
        crate::wire::decode_void(&raw)
    }

    /// `raisin.tx.setMessage` — registry method `tx_setMessage`.
    pub fn set_message(tx_id: &str, message: &str) -> crate::Result<()> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(message)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_setMessage", &args)?;
        crate::wire::decode_void(&raw)
    }

    /// `raisin.tx.update` — registry method `tx_update`.
    pub fn update(tx_id: &str, workspace: &str, path: &str, data: impl ::serde::Serialize) -> crate::Result<()> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(path)?,
            ::serde_json::to_value(data)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_update", &args)?;
        crate::wire::decode_void(&raw)
    }

    /// `raisin.tx.updateProperty` — registry method `tx_updateProperty`.
    pub fn update_property(tx_id: &str, workspace: &str, node_path: &str, property_path: &str, value: impl ::serde::Serialize) -> crate::Result<()> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(node_path)?,
            ::serde_json::to_value(property_path)?,
            ::serde_json::to_value(value)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_updateProperty", &args)?;
        crate::wire::decode_void(&raw)
    }

    /// `raisin.tx.upsert` — registry method `tx_upsert`.
    pub fn upsert(tx_id: &str, workspace: &str, data: impl ::serde::Serialize) -> crate::Result<()> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(data)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_upsert", &args)?;
        crate::wire::decode_void(&raw)
    }

    /// `raisin.tx.upsertDeep` — registry method `tx_upsertDeep`.
    pub fn upsert_deep(tx_id: &str, workspace: &str, data: impl ::serde::Serialize, parent_node_type: &str) -> crate::Result<()> {
        let args = ::serde_json::Value::Array(vec![
            ::serde_json::to_value(tx_id)?,
            ::serde_json::to_value(workspace)?,
            ::serde_json::to_value(data)?,
            ::serde_json::to_value(parent_node_type)?,
        ])
        .to_string();
        let raw = crate::host::call("tx_upsertDeep", &args)?;
        crate::wire::decode_void(&raw)
    }

}

