// Code generated by `cargo run -p raisin-functions --bin gen-bindings`.
// DO NOT EDIT — edit `crates/raisin-functions/src/runtime/bindings/` and
// re-run `make gen-bindings` instead.
//
// Generated companion to the hand-written `raisin.d.ts`. It describes the
// `raisin.*` surface exactly as the bindings registry defines it, with no
// prose and no hand-authored helper types.

declare namespace raisin {
  namespace admin {
    namespace nodes {
      function create(workspace: string, parentPath: string, data: any): Promise<any>;
      function delete(workspace: string, path: string): Promise<void>;
      function get(workspace: string, path: string): Promise<any | null>;
      function getById(workspace: string, id: string): Promise<any | null>;
      function getChildren(workspace: string, parentPath: string, limit?: number): Promise<any[]>;
      function query(workspace: string, query: any): Promise<any[]>;
      function update(workspace: string, path: string, data: any): Promise<any>;
      function updateProperty(workspace: string, nodePath: string, propertyPath: string, value: any): Promise<void>;
    }
    namespace sql {
      function execute(sql: string, params: any[]): Promise<number>;
      function query(sql: string, params: any[]): Promise<any>;
    }
  }

  namespace ai {
    function completion(request: any): Promise<any>;
    function embed(request: any): Promise<any>;
    function getDefaultModel(useCase: string): Promise<any | null>;
    function listModels(): Promise<any[]>;
    function listProviders(): Promise<any[]>;
  }

  namespace assets {
    function ensureContent(workspace: string, nodeRef: string): Promise<any>;
    function reextract(workspace: string, nodeRef: string): Promise<any>;
    function setExtractedText(workspace: string, nodeRef: string, text: string, options: any): Promise<any>;
    function signedUrl(workspace: string, nodeRef: string, options: any): Promise<any>;
  }

  namespace branches {
    function compare(branch: string, baseBranch: string): Promise<any>;
    function copyNodes(sourceBranch: string, targetBranch: string, opts: any): Promise<any>;
    function diff(branch: string, baseBranch: string): Promise<any>;
  }

  namespace crypto {
    function generateKeyPair(alg?: string | null): Promise<any>;
    function hash(input: string, alg?: string | null): Promise<string>;
    function randomBytes(n: number): Promise<string>;
    function signJwt(claims: any, private_jwk: any, opts?: any): Promise<string>;
    function uuid(): Promise<string>;
    function verifyJwt(token: string, opts?: any): Promise<any>;
  }

  namespace date {
    function addDays(timestamp: number, days: number): Promise<number>;
    function diffDays(ts1: number, ts2: number): Promise<number>;
    function format(timestamp: number, format?: string | null): Promise<string>;
    function now(): Promise<string>;
    function parse(dateStr: string, format?: string | null): Promise<number>;
    function timestamp(): Promise<number>;
    function timestampMillis(): Promise<number>;
  }

  namespace email {
    function providers(): Promise<any>;
    function send(message: any): Promise<any>;
  }

  namespace events {
    function emit(eventType: string, data: any): Promise<void>;
  }

  namespace flows {
    function run(flowPath: string, input: any): Promise<any>;
  }

  namespace functions {
    function call(functionPath: string, arguments: any): Promise<any>;
    function execute(functionPath: string, arguments: any, context: any): Promise<any>;
  }

  namespace http {
    function request(method: string, url: string, options: any): Promise<any>;
  }

  namespace identities {
    function findByEmail(email: string): Promise<any | null>;
    function update(id: string, patch: any): Promise<any>;
  }

  namespace imap {
    function fetchMessage(conn: any, uid: number, opts?: any): Promise<any>;
    function fetchSince(conn: any, sinceUid: number, opts?: any): Promise<any>;
    function listMailboxes(conn: any): Promise<any>;
  }

  namespace integrations {
    function syncNow(mountId: string, mode?: string | null): Promise<any>;
  }

  namespace inventory {
    function claim(pool: string, n: number, capacity: number): Promise<any>;
    function release(pool: string, n: number): Promise<number>;
  }

  namespace locks {
    function acquire(key: string, ttlMs: number, owner?: string | null): Promise<any>;
    function release(key: string, token: number): Promise<boolean>;
    function renew(key: string, token: number, ttlMs: number): Promise<boolean>;
  }

  namespace nodes {
    function addResource(workspace: string, nodePath: string, propertyPath: string, uploadData: any): Promise<any>;
    function applyChildOrder(workspace: string, parentPath: string, sourceBranch: string, targetBranch: string): Promise<void>;
    function create(workspace: string, parentPath: string, data: any): Promise<any>;
    function delete(workspace: string, path: string): Promise<void>;
    function get(workspace: string, path: string): Promise<any | null>;
    function getById(workspace: string, id: string): Promise<any | null>;
    function getChildren(workspace: string, parentPath: string, limit?: number): Promise<any[]>;
    function history(workspace: string, id: string, limit?: number): Promise<any[]>;
    function move(workspace: string, nodePath: string, newParentPath: string): Promise<any>;
    function moveChildAfter(workspace: string, parentPath: string, childName: string, afterChildName: string): Promise<void>;
    function moveChildBefore(workspace: string, parentPath: string, childName: string, beforeChildName: string): Promise<void>;
    function query(workspace: string, query: any): Promise<any[]>;
    function reorderChild(workspace: string, parentPath: string, childName: string, position: number): Promise<void>;
    function update(workspace: string, path: string, data: any): Promise<any>;
    function updateProperty(workspace: string, nodePath: string, propertyPath: string, value: any): Promise<void>;
  }

  namespace notify {
    function notify(options: any): Promise<any>;
  }

  namespace ocr {
    function image(base64Data: string, options: any): Promise<any>;
  }

  namespace pdf {
    function extractText(base64Data: string): Promise<any>;
    function getPageCount(base64Data: string): Promise<number>;
    function ocr(base64Data: string, options: any): Promise<any>;
    function processFromStorage(storageKey: string, options: any): Promise<any>;
  }

  namespace platform {
    function hook(name: string, payload: any): Promise<any>;
  }

  namespace resources {
    function getBinary(storageKey: string): Promise<string>;
  }

  namespace scheduler {
    function cancel(jobIdOrKey: string): Promise<any>;
    function get(jobIdOrKey: string): Promise<any>;
    function list(filter?: any): Promise<any>;
    function schedule(request: any): Promise<any>;
  }

  namespace secrets {
    function delete(name: string): Promise<any>;
    function get(name: string, version?: number): Promise<string>;
    function list(): Promise<any[]>;
    function put(name: string, value: string): Promise<any>;
    function resolve(value: string): Promise<string>;
    function rotate(name: string, value: string): Promise<any>;
  }

  namespace sql {
    function execute(sql: string, params: any[]): Promise<number>;
    function query(sql: string, params: any[]): Promise<any>;
  }

  namespace tasks {
    function complete(task_id: string, response: any): Promise<any>;
    function create(request: any): Promise<any>;
    function query(query: any): Promise<any[]>;
    function update(task_id: string, updates: any): Promise<any>;
  }

  namespace tx {
    function add(txId: string, workspace: string, data: any): Promise<any>;
    function begin(): Promise<string>;
    function commit(txId: string): Promise<void>;
    function create(txId: string, workspace: string, parentPath: string, data: any): Promise<any>;
    function createDeep(txId: string, workspace: string, parentPath: string, data: any, parentNodeType: string): Promise<any>;
    function delete(txId: string, workspace: string, path: string): Promise<void>;
    function deleteById(txId: string, workspace: string, id: string): Promise<void>;
    function get(txId: string, workspace: string, id: string): Promise<any | null>;
    function getByPath(txId: string, workspace: string, path: string): Promise<any | null>;
    function listChildren(txId: string, workspace: string, parentPath: string): Promise<any[]>;
    function move(txId: string, workspace: string, nodePath: string, newParentPath: string): Promise<any>;
    function put(txId: string, workspace: string, data: any): Promise<void>;
    function rollback(txId: string): Promise<void>;
    function setActor(txId: string, actor: string): Promise<void>;
    function setMessage(txId: string, message: string): Promise<void>;
    function update(txId: string, workspace: string, path: string, data: any): Promise<void>;
    function updateProperty(txId: string, workspace: string, nodePath: string, propertyPath: string, value: any): Promise<void>;
    function upsert(txId: string, workspace: string, data: any): Promise<void>;
    function upsertDeep(txId: string, workspace: string, data: any, parentNodeType: string): Promise<void>;
  }

}
