import type { FileEntry } from './types.js';

/**
 * Substitution variables for the connector-adapter scaffold.
 *
 * `name` is the adapter slug used for the function path (`/adapters/<name>`),
 * the integration template folder, and the package name. `provider` is the
 * `provider_type` recorded on the integration node (OAuth provider slug).
 */
export interface AdapterVars {
  /** Adapter slug, e.g. `dropbox`. Lower-kebab-case. */
  name: string;
  /** Provider type slug written to the integration node. Defaults to `name`. */
  provider: string;
  /** One-line human description used in manifest + node titles. */
  description: string;
}

/** Title-case a kebab/underscore slug for human-facing titles. */
function titleCase(slug: string): string {
  return slug
    .split(/[-_]/g)
    .filter((s) => s.length > 0)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join(' ');
}

function manifestYaml(v: AdapterVars): string {
  return `name: ${v.name}-adapter
version: 0.1.0
title: ${titleCase(v.name)} Adapter
description: >
  ${v.description}
author: ""
license: MIT
icon: plug
color: "#6366f1"
keywords:
  - ${v.name}
  - integration
  - virtual-nodes
  - sync
  - adapter
# Discovery contract for the admin console's Connectors gallery.
category: integrations

# Not a built-in package - installed on demand, never auto-installed.
builtin: false

provides:
  functions:
    - /adapters/${v.name}
  # Pre-configured connector template (disabled until credentials are supplied).
  content:
    - raisin:system/integrations/${v.name}

# Sync configuration for package updates. Declares the paths this package owns
# so re-installs merge cleanly instead of colliding with other packages.
sync:
  defaults:
    mode: merge
    on_conflict: prefer_server

  filters:
    - root: /adapters/${v.name}
      include:
        - "**"
      mode: merge
    - root: /integrations/${v.name}
      workspace: raisin:system
      include:
        - "**"
      mode: merge

# Workspace configuration for auto-created folders.
workspace_patches:
  functions:
    default_folder_type: raisin:Folder
  raisin:system:
    default_folder_type: raisin:Folder
`;
}

function readmeMd(v: AdapterVars): string {
  const title = titleCase(v.name);
  return `# ${title} Adapter

Virtual-node connector scaffold for **${title}**. Mount a remote folder into a
RaisinDB workspace path; the sync engine polls the provider, maps each item to a
node, and keeps the subtree in sync.

This package implements the frozen adapter contract in
\`docs/reference/virtual-node-adapters.md\`.

> Generated by \`raisindb create adapter\`. The shipped adapter is a working
> **stub**: \`capabilities\` returns conservative read-only flags and \`list\`
> returns an empty page. Fill in the TODO markers in
> \`content/functions/adapters/${v.name}/index.js\` to talk to the real API.

## What it ships

| Path | Workspace | Purpose |
|------|-----------|---------|
| \`/adapters/${v.name}\` | \`functions\` | Adapter function (\`handler(input)\`). |
| \`/integrations/${v.name}\` | \`raisin:system\` | Pre-configured connector template, **disabled**. |

## Install

From the package directory:

    raisindb package deploy . --repo <your-repo> --install

Or build a \`.rap\` and upload it:

    raisindb package create .
    raisindb package upload ${v.name}-adapter-0.1.0.rap --repo <your-repo>

## Configure the connector

1. Open the admin console -> **Connectors** -> **${title}**.
2. Paste your OAuth **Client ID** and **Client secret**. The secret is encrypted
   into \`client_secret_encrypted\` (AES-256-GCM) server-side; it is never stored
   in cleartext and never ships in this package.
3. Set \`redirect_uri\` to match your deployment callback, e.g.
   \`https://<your-host>/api/integrations/oauth/callback\`.
4. Fill in \`auth_url\`, \`token_url\`, and \`scopes\` for your provider in
   \`content/_raisin__system/integrations/${v.name}/.node.yaml\`.
5. **Enable** the connector, then **connect an account**.

## Implement the adapter

Edit \`content/functions/adapters/${v.name}/index.js\`:

- Replace the \`list\` stub with real API calls via \`raisin.http.fetch\`.
- Raise \`can_write\` / \`supports_changes\` in \`capabilities\` as you add
  \`create\`/\`update\`/\`delete\`/\`get_changes\`.
- Widen the adapter's \`network_policy.allowed_urls\` (in \`.node.yaml\`) to the
  provider's API + token hosts.

## Security notes

- The integration template ships \`enabled: false\` and contains **no** client
  secret.
- Refresh tokens never enter the function sandbox; the adapter receives only a
  short-lived \`access_token\`. On \`401\`, throw \`auth_expired\` and the engine
  handles the reconnect/refresh cycle.
- Outbound HTTP is restricted by the adapter's \`network_policy\`.
`;
}

function adapterIndexJs(v: AdapterVars): string {
  const title = titleCase(v.name);
  return `/**
 * ${title} virtual-node adapter (scaffold).
 *
 * Implements the frozen adapter contract (docs/reference/virtual-node-adapters.md).
 * The sync engine invokes this function directly, decrypts the account
 * credential just before the call, and materializes returned items into nodes.
 *
 * Entrypoint: handler(input) - exactly one argument.
 *   input = { operation, params, credential, mount }
 *
 * Token lifecycle is owned by the engine: credential.access_token is a current,
 * decrypted token. There is NO refresh logic here. If a token is rejected,
 * throw the reserved "auth_expired" code and let the engine reconnect.
 */

// TODO: point at your provider's REST base + OAuth token host, and mirror them
// in the adapter .node.yaml network_policy.allowed_urls.
var API_BASE = "https://api.example.com/v1";

// Error convention: throw a plain Error carrying a machine-readable \`code\`.
// The engine dispatches on reserved codes: auth_expired, rate_limited, conflict.
function coded(message, code) {
  var e = new Error(message);
  e.code = code;
  return e;
}

// Map an HTTP status to the reserved error codes. Never swallow an auth failure
// into an empty result - that reads to the engine as "everything was deleted".
function raiseForStatus(resp, context) {
  var status = resp.status;
  if (status >= 200 && status < 300) return;
  if (status === 401) throw coded("Access token rejected", "auth_expired");
  if (status === 429) throw coded("Rate limit exceeded", "rate_limited");
  var body = resp.body || {};
  var msg = (body && body.message) || ("Request failed (" + status + ")");
  throw new Error(context + ": " + msg);
}

// Normalize one provider item into the adapter contract's ExternalItem shape.
// TODO: map real provider fields onto these keys.
function toExternalItem(raw) {
  return {
    external_id: raw.id,
    name: raw.name,
    mime_type: raw.mime_type || null,
    size_bytes: raw.size != null ? Number(raw.size) : null,
    is_folder: !!raw.is_folder,
    parent_id: raw.parent_id || null,
    created_at: raw.created_at || null,
    modified_at: raw.modified_at || null,
    // A stable per-item version lets the engine's etag skip-write suppress
    // needless revisions. Prefer a monotonic counter over modified time.
    etag: raw.version != null ? String(raw.version) : raw.modified_at || null,
    web_url: raw.web_url || null,
    download_url: raw.download_url || null,
    metadata: {},
  };
}

// ---- operations -----------------------------------------------------------

// Conservative defaults: this scaffold only reads, and only a flat list. Raise
// these flags as you implement create/update/delete/get_changes below.
function opCapabilities() {
  return {
    can_read: true,
    can_write: false,
    can_create_folders: false,
    supports_changes: false,
    supports_webhooks: false,
    supports_search: false,
    supports_push: false,
    default_ttl: null,
    max_file_size: null,
  };
}

// Return one page of children under params.folder_id (defaults to the mount
// root). Paginate via next_cursor. This stub returns an empty page so a fresh
// install syncs cleanly with zero remote items until you wire the real call.
function opList(credential, mount, params) {
  var folderId = params.folder_id || mount.remote_root;
  // TODO: replace with a real request, e.g.:
  //   var url = API_BASE + "/folders/" + encodeURIComponent(folderId) + "/children";
  //   var resp = raisin.http.fetch(url, {
  //     method: "GET",
  //     headers: { Authorization: "Bearer " + credential.access_token },
  //   });
  //   raiseForStatus(resp, "list");
  //   var items = (resp.body.items || []).map(toExternalItem);
  //   return { items: items, next_cursor: resp.body.next_cursor || null };
  void folderId;
  return { items: [], next_cursor: null };
}

// TODO: implement get(item_id | path) -> ExternalItem | null.
function opGet(credential, mount, params) {
  throw coded("get not implemented in this scaffold", "not_implemented");
}

// ---- dispatch -------------------------------------------------------------

function handler(input) {
  var operation = input.operation;
  var params = input.params || {};
  var credential = input.credential;
  var mount = input.mount || {};

  switch (operation) {
    case "capabilities":
      return opCapabilities();
    case "list":
      return opList(credential, mount, params);
    case "get":
      return opGet(credential, mount, params);
    // TODO: case "get_content": ...
    // TODO: case "create": ...
    // TODO: case "update": ...
    // TODO: case "delete": ...
    // TODO: case "get_changes": ...
    default:
      throw new Error("Unsupported operation: " + operation);
  }
}
`;
}

function adapterNodeYaml(v: AdapterVars): string {
  const title = titleCase(v.name);
  return `node_type: raisin:Function
properties:
  title: ${title} Adapter
  description: >
    Virtual-node adapter for ${title}. Translates the normalized adapter
    operations (capabilities, list, get, ...) into provider REST calls. Invoked
    directly by the sync engine with a decrypted access token; owns no
    token-refresh logic. Generated scaffold - implement the TODO operations.
  language: javascript
  entry_file: index.js:handler
  execution_mode: Async
  enabled: true
  version: 1
  resource_limits:
    # Raised well above the default: sync operations may page through a remote
    # API and should not trip a short function timeout.
    timeout_ms: 120000
    max_memory_bytes: 67108864
  # Restrictive placeholder: outbound HTTP is DENIED until you list the exact
  # provider API + OAuth token hosts here. Replace the example host.
  network_policy:
    http_enabled: true
    request_timeout_ms: 120000
    max_concurrent_requests: 10
    allowed_urls:
      # TODO: replace with your provider's real hosts, e.g.
      #   - "https://api.dropboxapi.com/**"
      #   - "https://api.dropbox.com/**"
      - "https://api.example.com/**"
  input_schema:
    type: object
    required:
      - operation
    properties:
      operation:
        type: string
        description: One of capabilities, list, get, get_content, create, update, delete, get_changes
      params:
        type: object
        description: Operation-specific arguments
      credential:
        type: object
        description: Decrypted account credential { access_token, account_id, provider_type }
      mount:
        type: object
        description: Read-only mount snapshot { mount_id, remote_root, mount_path, sync_config }
  output_schema:
    type: object
    description: Operation-specific result (ExternalItem, page, Capabilities, ...)
`;
}

function integrationNodeYaml(v: AdapterVars): string {
  const title = titleCase(v.name);
  return `node_type: raisin:Integration
properties:
  title: ${title}
  provider_type: ${v.provider}
  # Adapter path inside the \`functions\` workspace (see content/functions/adapters).
  adapter_function: /adapters/${v.name}
  # Disabled until an operator supplies client_id/client_secret via the admin
  # console. The client secret is NEVER stored here - the console encrypts it
  # into client_secret_encrypted (AES-256-GCM) on the node.
  enabled: false
  oauth_config:
    # TODO: fill in your provider's OAuth endpoints and scopes.
    auth_url: ""
    token_url: ""
    scopes: []
    # Filled in by the admin console to match the deployment's callback URL,
    # e.g. https://<host>/api/integrations/oauth/callback
    redirect_uri: ""
    # Request a refresh token so offline sync works, where the provider supports it.
    access_type: offline
    prompt: consent
  # No connected_accounts, client_id, or client_secret_encrypted are shipped.
`;
}

/**
 * Build the full file tree for a connector-adapter scaffold package. Paths are
 * relative to the target directory; the system-workspace folder uses the
 * encoded workspace name (`_raisin__system`) matching the built-in packages.
 */
export function adapterFiles(v: AdapterVars): FileEntry[] {
  const fnDir = `content/functions/adapters/${v.name}`;
  const sysDir = `content/_raisin__system/integrations/${v.name}`;
  return [
    { path: 'manifest.yaml', content: manifestYaml(v) },
    { path: 'README.md', content: readmeMd(v) },
    { path: `${fnDir}/index.js`, content: adapterIndexJs(v) },
    { path: `${fnDir}/.node.yaml`, content: adapterNodeYaml(v) },
    { path: `${sysDir}/.node.yaml`, content: integrationNodeYaml(v) },
  ];
}
