// Code generated by `cargo run -p raisin-functions --bin gen-bindings`.
// DO NOT EDIT — edit `crates/raisin-functions/src/runtime/bindings/` and
// re-run `make gen-bindings` instead.

package raisin

import "encoding/json"

// AdminNodesAPI is the `raisin.admin.nodes` namespace.
type AdminNodesAPI struct{}

// AdminNodes is the entry point for the `raisin.admin.nodes` namespace.
var AdminNodes AdminNodesAPI

// Create calls the RaisinDB registry method "admin_nodes_create".
func (AdminNodesAPI) Create(workspace string, parentPath string, data any) (json.RawMessage, error) {
	return callJSON("admin_nodes_create", []any{workspace, parentPath, data})
}

// Delete calls the RaisinDB registry method "admin_nodes_delete".
func (AdminNodesAPI) Delete(workspace string, path string) error {
	return callVoid("admin_nodes_delete", []any{workspace, path})
}

// Get calls the RaisinDB registry method "admin_nodes_get".
func (AdminNodesAPI) Get(workspace string, path string) (json.RawMessage, error) {
	return callJSON("admin_nodes_get", []any{workspace, path})
}

// GetById calls the RaisinDB registry method "admin_nodes_getById".
func (AdminNodesAPI) GetById(workspace string, id string) (json.RawMessage, error) {
	return callJSON("admin_nodes_getById", []any{workspace, id})
}

// GetChildren calls the RaisinDB registry method "admin_nodes_getChildren".
func (AdminNodesAPI) GetChildren(workspace string, parentPath string, limit *uint32) (json.RawMessage, error) {
	return callJSON("admin_nodes_getChildren", []any{workspace, parentPath, limit})
}

// Query calls the RaisinDB registry method "admin_nodes_query".
func (AdminNodesAPI) Query(workspace string, query any) (json.RawMessage, error) {
	return callJSON("admin_nodes_query", []any{workspace, query})
}

// Update calls the RaisinDB registry method "admin_nodes_update".
func (AdminNodesAPI) Update(workspace string, path string, data any) (json.RawMessage, error) {
	return callJSON("admin_nodes_update", []any{workspace, path, data})
}

// UpdateProperty calls the RaisinDB registry method "admin_nodes_updateProperty".
func (AdminNodesAPI) UpdateProperty(workspace string, nodePath string, propertyPath string, value any) error {
	return callVoid("admin_nodes_updateProperty", []any{workspace, nodePath, propertyPath, value})
}

// AdminSqlAPI is the `raisin.admin.sql` namespace.
type AdminSqlAPI struct{}

// AdminSql is the entry point for the `raisin.admin.sql` namespace.
var AdminSql AdminSqlAPI

// Execute calls the RaisinDB registry method "admin_sql_execute".
func (AdminSqlAPI) Execute(sql string, params []any) (int64, error) {
	return callInt64("admin_sql_execute", []any{sql, params})
}

// Query calls the RaisinDB registry method "admin_sql_query".
func (AdminSqlAPI) Query(sql string, params []any) (json.RawMessage, error) {
	return callJSON("admin_sql_query", []any{sql, params})
}

// AiAPI is the `raisin.ai` namespace.
type AiAPI struct{}

// Ai is the entry point for the `raisin.ai` namespace.
var Ai AiAPI

// Completion calls the RaisinDB registry method "ai_completion".
func (AiAPI) Completion(request any) (json.RawMessage, error) {
	return callJSON("ai_completion", []any{request})
}

// Embed calls the RaisinDB registry method "ai_embed".
func (AiAPI) Embed(request any) (json.RawMessage, error) {
	return callJSON("ai_embed", []any{request})
}

// GetDefaultModel calls the RaisinDB registry method "ai_getDefaultModel".
func (AiAPI) GetDefaultModel(useCase string) (json.RawMessage, error) {
	return callJSON("ai_getDefaultModel", []any{useCase})
}

// ListModels calls the RaisinDB registry method "ai_listModels".
func (AiAPI) ListModels() (json.RawMessage, error) {
	return callJSON("ai_listModels", nil)
}

// ListProviders calls the RaisinDB registry method "ai_listProviders".
func (AiAPI) ListProviders() (json.RawMessage, error) {
	return callJSON("ai_listProviders", nil)
}

// AssetsAPI is the `raisin.assets` namespace.
type AssetsAPI struct{}

// Assets is the entry point for the `raisin.assets` namespace.
var Assets AssetsAPI

// EnsureContent calls the RaisinDB registry method "asset_ensure_content".
func (AssetsAPI) EnsureContent(workspace string, nodeRef string) (json.RawMessage, error) {
	return callJSON("asset_ensure_content", []any{workspace, nodeRef})
}

// Reextract calls the RaisinDB registry method "asset_reextract".
func (AssetsAPI) Reextract(workspace string, nodeRef string) (json.RawMessage, error) {
	return callJSON("asset_reextract", []any{workspace, nodeRef})
}

// SetExtractedText calls the RaisinDB registry method "asset_set_extraction".
func (AssetsAPI) SetExtractedText(workspace string, nodeRef string, text string, options any) (json.RawMessage, error) {
	return callJSON("asset_set_extraction", []any{workspace, nodeRef, text, options})
}

// SignedUrl calls the RaisinDB registry method "asset_signed_url".
func (AssetsAPI) SignedUrl(workspace string, nodeRef string, options any) (json.RawMessage, error) {
	return callJSON("asset_signed_url", []any{workspace, nodeRef, options})
}

// BranchesAPI is the `raisin.branches` namespace.
type BranchesAPI struct{}

// Branches is the entry point for the `raisin.branches` namespace.
var Branches BranchesAPI

// Compare calls the RaisinDB registry method "branches_compare".
func (BranchesAPI) Compare(branch string, baseBranch string) (json.RawMessage, error) {
	return callJSON("branches_compare", []any{branch, baseBranch})
}

// CopyNodes calls the RaisinDB registry method "branches_copyNodes".
func (BranchesAPI) CopyNodes(sourceBranch string, targetBranch string, opts any) (json.RawMessage, error) {
	return callJSON("branches_copyNodes", []any{sourceBranch, targetBranch, opts})
}

// Diff calls the RaisinDB registry method "branches_diff".
func (BranchesAPI) Diff(branch string, baseBranch string) (json.RawMessage, error) {
	return callJSON("branches_diff", []any{branch, baseBranch})
}

// CryptoAPI is the `raisin.crypto` namespace.
type CryptoAPI struct{}

// Crypto is the entry point for the `raisin.crypto` namespace.
var Crypto CryptoAPI

// GenerateKeyPair calls the RaisinDB registry method "crypto_generate_key_pair".
func (CryptoAPI) GenerateKeyPair(alg *string) (json.RawMessage, error) {
	return callJSON("crypto_generate_key_pair", []any{alg})
}

// Hash calls the RaisinDB registry method "crypto_hash".
func (CryptoAPI) Hash(input string, alg *string) (string, error) {
	return callString("crypto_hash", []any{input, alg})
}

// RandomBytes calls the RaisinDB registry method "crypto_random_bytes".
func (CryptoAPI) RandomBytes(n uint32) (string, error) {
	return callString("crypto_random_bytes", []any{n})
}

// SignJwt calls the RaisinDB registry method "crypto_sign_jwt".
func (CryptoAPI) SignJwt(claims any, private_jwk any, opts any) (string, error) {
	return callString("crypto_sign_jwt", []any{claims, private_jwk, opts})
}

// Uuid calls the RaisinDB registry method "crypto_uuid".
func (CryptoAPI) Uuid() (string, error) {
	return callString("crypto_uuid", nil)
}

// VerifyJwt calls the RaisinDB registry method "crypto_verify_jwt".
func (CryptoAPI) VerifyJwt(token string, opts any) (json.RawMessage, error) {
	return callJSON("crypto_verify_jwt", []any{token, opts})
}

// DateAPI is the `raisin.date` namespace.
type DateAPI struct{}

// Date is the entry point for the `raisin.date` namespace.
var Date DateAPI

// AddDays calls the RaisinDB registry method "date_addDays".
func (DateAPI) AddDays(timestamp int64, days int64) (int64, error) {
	return callInt64("date_addDays", []any{timestamp, days})
}

// DiffDays calls the RaisinDB registry method "date_diffDays".
func (DateAPI) DiffDays(ts1 int64, ts2 int64) (int64, error) {
	return callInt64("date_diffDays", []any{ts1, ts2})
}

// Format calls the RaisinDB registry method "date_format".
func (DateAPI) Format(timestamp int64, format *string) (string, error) {
	return callString("date_format", []any{timestamp, format})
}

// Now calls the RaisinDB registry method "date_now".
func (DateAPI) Now() (string, error) {
	return callString("date_now", nil)
}

// Parse calls the RaisinDB registry method "date_parse".
func (DateAPI) Parse(dateStr string, format *string) (int64, error) {
	return callInt64("date_parse", []any{dateStr, format})
}

// Timestamp calls the RaisinDB registry method "date_timestamp".
func (DateAPI) Timestamp() (int64, error) {
	return callInt64("date_timestamp", nil)
}

// TimestampMillis calls the RaisinDB registry method "date_timestampMillis".
func (DateAPI) TimestampMillis() (int64, error) {
	return callInt64("date_timestampMillis", nil)
}

// EmailAPI is the `raisin.email` namespace.
type EmailAPI struct{}

// Email is the entry point for the `raisin.email` namespace.
var Email EmailAPI

// Providers calls the RaisinDB registry method "email_providers".
func (EmailAPI) Providers() (json.RawMessage, error) {
	return callJSON("email_providers", nil)
}

// Send calls the RaisinDB registry method "email_send".
func (EmailAPI) Send(message any) (json.RawMessage, error) {
	return callJSON("email_send", []any{message})
}

// EventsAPI is the `raisin.events` namespace.
type EventsAPI struct{}

// Events is the entry point for the `raisin.events` namespace.
var Events EventsAPI

// Emit calls the RaisinDB registry method "events_emit".
func (EventsAPI) Emit(eventType string, data any) error {
	return callVoid("events_emit", []any{eventType, data})
}

// FlowsAPI is the `raisin.flows` namespace.
type FlowsAPI struct{}

// Flows is the entry point for the `raisin.flows` namespace.
var Flows FlowsAPI

// Run calls the RaisinDB registry method "flows_run".
func (FlowsAPI) Run(flowPath string, input any) (json.RawMessage, error) {
	return callJSON("flows_run", []any{flowPath, input})
}

// FunctionsAPI is the `raisin.functions` namespace.
type FunctionsAPI struct{}

// Functions is the entry point for the `raisin.functions` namespace.
var Functions FunctionsAPI

// Call calls the RaisinDB registry method "functions_call".
func (FunctionsAPI) Call(functionPath string, arguments any) (json.RawMessage, error) {
	return callJSON("functions_call", []any{functionPath, arguments})
}

// Execute calls the RaisinDB registry method "functions_execute".
func (FunctionsAPI) Execute(functionPath string, arguments any, context any) (json.RawMessage, error) {
	return callJSON("functions_execute", []any{functionPath, arguments, context})
}

// HttpAPI is the `raisin.http` namespace.
type HttpAPI struct{}

// Http is the entry point for the `raisin.http` namespace.
var Http HttpAPI

// Request calls the RaisinDB registry method "http_request".
func (HttpAPI) Request(method string, url string, options any) (json.RawMessage, error) {
	return callJSON("http_request", []any{method, url, options})
}

// IdentitiesAPI is the `raisin.identities` namespace.
type IdentitiesAPI struct{}

// Identities is the entry point for the `raisin.identities` namespace.
var Identities IdentitiesAPI

// FindByEmail calls the RaisinDB registry method "identities_findByEmail".
func (IdentitiesAPI) FindByEmail(email string) (json.RawMessage, error) {
	return callJSON("identities_findByEmail", []any{email})
}

// Update calls the RaisinDB registry method "identities_update".
func (IdentitiesAPI) Update(id string, patch any) (json.RawMessage, error) {
	return callJSON("identities_update", []any{id, patch})
}

// ImapAPI is the `raisin.imap` namespace.
type ImapAPI struct{}

// Imap is the entry point for the `raisin.imap` namespace.
var Imap ImapAPI

// FetchMessage calls the RaisinDB registry method "imap_fetch_message".
func (ImapAPI) FetchMessage(conn any, uid int64, opts any) (json.RawMessage, error) {
	return callJSON("imap_fetch_message", []any{conn, uid, opts})
}

// FetchSince calls the RaisinDB registry method "imap_fetch_since".
func (ImapAPI) FetchSince(conn any, sinceUid int64, opts any) (json.RawMessage, error) {
	return callJSON("imap_fetch_since", []any{conn, sinceUid, opts})
}

// ListMailboxes calls the RaisinDB registry method "imap_list_mailboxes".
func (ImapAPI) ListMailboxes(conn any) (json.RawMessage, error) {
	return callJSON("imap_list_mailboxes", []any{conn})
}

// IntegrationsAPI is the `raisin.integrations` namespace.
type IntegrationsAPI struct{}

// Integrations is the entry point for the `raisin.integrations` namespace.
var Integrations IntegrationsAPI

// SyncNow calls the RaisinDB registry method "integrations_sync_now".
func (IntegrationsAPI) SyncNow(mountId string, mode *string) (json.RawMessage, error) {
	return callJSON("integrations_sync_now", []any{mountId, mode})
}

// InventoryAPI is the `raisin.inventory` namespace.
type InventoryAPI struct{}

// Inventory is the entry point for the `raisin.inventory` namespace.
var Inventory InventoryAPI

// Claim calls the RaisinDB registry method "inventory_claim".
func (InventoryAPI) Claim(pool string, n int64, capacity int64) (json.RawMessage, error) {
	return callJSON("inventory_claim", []any{pool, n, capacity})
}

// Release calls the RaisinDB registry method "inventory_release".
func (InventoryAPI) Release(pool string, n int64) (int64, error) {
	return callInt64("inventory_release", []any{pool, n})
}

// LocksAPI is the `raisin.locks` namespace.
type LocksAPI struct{}

// Locks is the entry point for the `raisin.locks` namespace.
var Locks LocksAPI

// Acquire calls the RaisinDB registry method "locks_acquire".
func (LocksAPI) Acquire(key string, ttlMs int64, owner *string) (json.RawMessage, error) {
	return callJSON("locks_acquire", []any{key, ttlMs, owner})
}

// Release calls the RaisinDB registry method "locks_release".
func (LocksAPI) Release(key string, token int64) (bool, error) {
	return callBool("locks_release", []any{key, token})
}

// Renew calls the RaisinDB registry method "locks_renew".
func (LocksAPI) Renew(key string, token int64, ttlMs int64) (bool, error) {
	return callBool("locks_renew", []any{key, token, ttlMs})
}

// NodesAPI is the `raisin.nodes` namespace.
type NodesAPI struct{}

// Nodes is the entry point for the `raisin.nodes` namespace.
var Nodes NodesAPI

// AddResource calls the RaisinDB registry method "nodes_addResource".
func (NodesAPI) AddResource(workspace string, nodePath string, propertyPath string, uploadData any) (json.RawMessage, error) {
	return callJSON("nodes_addResource", []any{workspace, nodePath, propertyPath, uploadData})
}

// ApplyChildOrder calls the RaisinDB registry method "nodes_applyChildOrder".
func (NodesAPI) ApplyChildOrder(workspace string, parentPath string, sourceBranch string, targetBranch string) error {
	return callVoid("nodes_applyChildOrder", []any{workspace, parentPath, sourceBranch, targetBranch})
}

// Create calls the RaisinDB registry method "nodes_create".
func (NodesAPI) Create(workspace string, parentPath string, data any) (json.RawMessage, error) {
	return callJSON("nodes_create", []any{workspace, parentPath, data})
}

// Delete calls the RaisinDB registry method "nodes_delete".
func (NodesAPI) Delete(workspace string, path string) error {
	return callVoid("nodes_delete", []any{workspace, path})
}

// Get calls the RaisinDB registry method "nodes_get".
func (NodesAPI) Get(workspace string, path string) (json.RawMessage, error) {
	return callJSON("nodes_get", []any{workspace, path})
}

// GetById calls the RaisinDB registry method "nodes_getById".
func (NodesAPI) GetById(workspace string, id string) (json.RawMessage, error) {
	return callJSON("nodes_getById", []any{workspace, id})
}

// GetChildren calls the RaisinDB registry method "nodes_getChildren".
func (NodesAPI) GetChildren(workspace string, parentPath string, limit *uint32) (json.RawMessage, error) {
	return callJSON("nodes_getChildren", []any{workspace, parentPath, limit})
}

// History calls the RaisinDB registry method "nodes_history".
func (NodesAPI) History(workspace string, id string, limit *uint32) (json.RawMessage, error) {
	return callJSON("nodes_history", []any{workspace, id, limit})
}

// Move calls the RaisinDB registry method "nodes_move".
func (NodesAPI) Move(workspace string, nodePath string, newParentPath string) (json.RawMessage, error) {
	return callJSON("nodes_move", []any{workspace, nodePath, newParentPath})
}

// MoveChildAfter calls the RaisinDB registry method "nodes_moveChildAfter".
func (NodesAPI) MoveChildAfter(workspace string, parentPath string, childName string, afterChildName string) error {
	return callVoid("nodes_moveChildAfter", []any{workspace, parentPath, childName, afterChildName})
}

// MoveChildBefore calls the RaisinDB registry method "nodes_moveChildBefore".
func (NodesAPI) MoveChildBefore(workspace string, parentPath string, childName string, beforeChildName string) error {
	return callVoid("nodes_moveChildBefore", []any{workspace, parentPath, childName, beforeChildName})
}

// Query calls the RaisinDB registry method "nodes_query".
func (NodesAPI) Query(workspace string, query any) (json.RawMessage, error) {
	return callJSON("nodes_query", []any{workspace, query})
}

// ReorderChild calls the RaisinDB registry method "nodes_reorderChild".
func (NodesAPI) ReorderChild(workspace string, parentPath string, childName string, position uint32) error {
	return callVoid("nodes_reorderChild", []any{workspace, parentPath, childName, position})
}

// Update calls the RaisinDB registry method "nodes_update".
func (NodesAPI) Update(workspace string, path string, data any) (json.RawMessage, error) {
	return callJSON("nodes_update", []any{workspace, path, data})
}

// UpdateProperty calls the RaisinDB registry method "nodes_updateProperty".
func (NodesAPI) UpdateProperty(workspace string, nodePath string, propertyPath string, value any) error {
	return callVoid("nodes_updateProperty", []any{workspace, nodePath, propertyPath, value})
}

// NotifyAPI is the `raisin.notify` namespace.
type NotifyAPI struct{}

// Notify is the entry point for the `raisin.notify` namespace.
var Notify NotifyAPI

// Notify calls the RaisinDB registry method "notify_send".
func (NotifyAPI) Notify(options any) (json.RawMessage, error) {
	return callJSON("notify_send", []any{options})
}

// OcrAPI is the `raisin.ocr` namespace.
type OcrAPI struct{}

// Ocr is the entry point for the `raisin.ocr` namespace.
var Ocr OcrAPI

// Image calls the RaisinDB registry method "ocr_image".
func (OcrAPI) Image(base64Data string, options any) (json.RawMessage, error) {
	return callJSON("ocr_image", []any{base64Data, options})
}

// PdfAPI is the `raisin.pdf` namespace.
type PdfAPI struct{}

// Pdf is the entry point for the `raisin.pdf` namespace.
var Pdf PdfAPI

// ExtractText calls the RaisinDB registry method "pdf_extractText".
func (PdfAPI) ExtractText(base64Data string) (json.RawMessage, error) {
	return callJSON("pdf_extractText", []any{base64Data})
}

// GetPageCount calls the RaisinDB registry method "pdf_getPageCount".
func (PdfAPI) GetPageCount(base64Data string) (int64, error) {
	return callInt64("pdf_getPageCount", []any{base64Data})
}

// Ocr calls the RaisinDB registry method "pdf_ocr".
func (PdfAPI) Ocr(base64Data string, options any) (json.RawMessage, error) {
	return callJSON("pdf_ocr", []any{base64Data, options})
}

// ProcessFromStorage calls the RaisinDB registry method "pdf_processFromStorage".
func (PdfAPI) ProcessFromStorage(storageKey string, options any) (json.RawMessage, error) {
	return callJSON("pdf_processFromStorage", []any{storageKey, options})
}

// PlatformAPI is the `raisin.platform` namespace.
type PlatformAPI struct{}

// Platform is the entry point for the `raisin.platform` namespace.
var Platform PlatformAPI

// Hook calls the RaisinDB registry method "platform_hook".
func (PlatformAPI) Hook(name string, payload any) (json.RawMessage, error) {
	return callJSON("platform_hook", []any{name, payload})
}

// ResourcesAPI is the `raisin.resources` namespace.
type ResourcesAPI struct{}

// Resources is the entry point for the `raisin.resources` namespace.
var Resources ResourcesAPI

// GetBinary calls the RaisinDB registry method "resources_getBinary".
func (ResourcesAPI) GetBinary(storageKey string) (string, error) {
	return callString("resources_getBinary", []any{storageKey})
}

// SchedulerAPI is the `raisin.scheduler` namespace.
type SchedulerAPI struct{}

// Scheduler is the entry point for the `raisin.scheduler` namespace.
var Scheduler SchedulerAPI

// Cancel calls the RaisinDB registry method "scheduler_cancel".
func (SchedulerAPI) Cancel(jobIdOrKey string) (json.RawMessage, error) {
	return callJSON("scheduler_cancel", []any{jobIdOrKey})
}

// Get calls the RaisinDB registry method "scheduler_get".
func (SchedulerAPI) Get(jobIdOrKey string) (json.RawMessage, error) {
	return callJSON("scheduler_get", []any{jobIdOrKey})
}

// List calls the RaisinDB registry method "scheduler_list".
func (SchedulerAPI) List(filter any) (json.RawMessage, error) {
	return callJSON("scheduler_list", []any{filter})
}

// Schedule calls the RaisinDB registry method "scheduler_schedule".
func (SchedulerAPI) Schedule(request any) (json.RawMessage, error) {
	return callJSON("scheduler_schedule", []any{request})
}

// SecretsAPI is the `raisin.secrets` namespace.
type SecretsAPI struct{}

// Secrets is the entry point for the `raisin.secrets` namespace.
var Secrets SecretsAPI

// Delete calls the RaisinDB registry method "secrets_delete".
func (SecretsAPI) Delete(name string) (json.RawMessage, error) {
	return callJSON("secrets_delete", []any{name})
}

// Get calls the RaisinDB registry method "secrets_get".
func (SecretsAPI) Get(name string, version *int64) (string, error) {
	return callString("secrets_get", []any{name, version})
}

// List calls the RaisinDB registry method "secrets_list".
func (SecretsAPI) List() (json.RawMessage, error) {
	return callJSON("secrets_list", nil)
}

// Put calls the RaisinDB registry method "secrets_put".
func (SecretsAPI) Put(name string, value string) (json.RawMessage, error) {
	return callJSON("secrets_put", []any{name, value})
}

// Resolve calls the RaisinDB registry method "secrets_resolve".
func (SecretsAPI) Resolve(value string) (string, error) {
	return callString("secrets_resolve", []any{value})
}

// Rotate calls the RaisinDB registry method "secrets_rotate".
func (SecretsAPI) Rotate(name string, value string) (json.RawMessage, error) {
	return callJSON("secrets_rotate", []any{name, value})
}

// SqlAPI is the `raisin.sql` namespace.
type SqlAPI struct{}

// Sql is the entry point for the `raisin.sql` namespace.
var Sql SqlAPI

// Execute calls the RaisinDB registry method "sql_execute".
func (SqlAPI) Execute(sql string, params []any) (int64, error) {
	return callInt64("sql_execute", []any{sql, params})
}

// Query calls the RaisinDB registry method "sql_query".
func (SqlAPI) Query(sql string, params []any) (json.RawMessage, error) {
	return callJSON("sql_query", []any{sql, params})
}

// TasksAPI is the `raisin.tasks` namespace.
type TasksAPI struct{}

// Tasks is the entry point for the `raisin.tasks` namespace.
var Tasks TasksAPI

// Complete calls the RaisinDB registry method "tasks_complete".
func (TasksAPI) Complete(task_id string, response any) (json.RawMessage, error) {
	return callJSON("tasks_complete", []any{task_id, response})
}

// Create calls the RaisinDB registry method "tasks_create".
func (TasksAPI) Create(request any) (json.RawMessage, error) {
	return callJSON("tasks_create", []any{request})
}

// Query calls the RaisinDB registry method "tasks_query".
func (TasksAPI) Query(query any) (json.RawMessage, error) {
	return callJSON("tasks_query", []any{query})
}

// Update calls the RaisinDB registry method "tasks_update".
func (TasksAPI) Update(task_id string, updates any) (json.RawMessage, error) {
	return callJSON("tasks_update", []any{task_id, updates})
}

// TxAPI is the `raisin.tx` namespace.
type TxAPI struct{}

// Tx is the entry point for the `raisin.tx` namespace.
var Tx TxAPI

// Add calls the RaisinDB registry method "tx_add".
func (TxAPI) Add(txId string, workspace string, data any) (json.RawMessage, error) {
	return callJSON("tx_add", []any{txId, workspace, data})
}

// Begin calls the RaisinDB registry method "tx_begin".
func (TxAPI) Begin() (string, error) {
	return callString("tx_begin", nil)
}

// Commit calls the RaisinDB registry method "tx_commit".
func (TxAPI) Commit(txId string) error {
	return callVoid("tx_commit", []any{txId})
}

// Create calls the RaisinDB registry method "tx_create".
func (TxAPI) Create(txId string, workspace string, parentPath string, data any) (json.RawMessage, error) {
	return callJSON("tx_create", []any{txId, workspace, parentPath, data})
}

// CreateDeep calls the RaisinDB registry method "tx_createDeep".
func (TxAPI) CreateDeep(txId string, workspace string, parentPath string, data any, parentNodeType string) (json.RawMessage, error) {
	return callJSON("tx_createDeep", []any{txId, workspace, parentPath, data, parentNodeType})
}

// Delete calls the RaisinDB registry method "tx_delete".
func (TxAPI) Delete(txId string, workspace string, path string) error {
	return callVoid("tx_delete", []any{txId, workspace, path})
}

// DeleteById calls the RaisinDB registry method "tx_deleteById".
func (TxAPI) DeleteById(txId string, workspace string, id string) error {
	return callVoid("tx_deleteById", []any{txId, workspace, id})
}

// Get calls the RaisinDB registry method "tx_get".
func (TxAPI) Get(txId string, workspace string, id string) (json.RawMessage, error) {
	return callJSON("tx_get", []any{txId, workspace, id})
}

// GetByPath calls the RaisinDB registry method "tx_getByPath".
func (TxAPI) GetByPath(txId string, workspace string, path string) (json.RawMessage, error) {
	return callJSON("tx_getByPath", []any{txId, workspace, path})
}

// ListChildren calls the RaisinDB registry method "tx_listChildren".
func (TxAPI) ListChildren(txId string, workspace string, parentPath string) (json.RawMessage, error) {
	return callJSON("tx_listChildren", []any{txId, workspace, parentPath})
}

// Move calls the RaisinDB registry method "tx_move".
func (TxAPI) Move(txId string, workspace string, nodePath string, newParentPath string) (json.RawMessage, error) {
	return callJSON("tx_move", []any{txId, workspace, nodePath, newParentPath})
}

// Put calls the RaisinDB registry method "tx_put".
func (TxAPI) Put(txId string, workspace string, data any) error {
	return callVoid("tx_put", []any{txId, workspace, data})
}

// Rollback calls the RaisinDB registry method "tx_rollback".
func (TxAPI) Rollback(txId string) error {
	return callVoid("tx_rollback", []any{txId})
}

// SetActor calls the RaisinDB registry method "tx_setActor".
func (TxAPI) SetActor(txId string, actor string) error {
	return callVoid("tx_setActor", []any{txId, actor})
}

// SetMessage calls the RaisinDB registry method "tx_setMessage".
func (TxAPI) SetMessage(txId string, message string) error {
	return callVoid("tx_setMessage", []any{txId, message})
}

// Update calls the RaisinDB registry method "tx_update".
func (TxAPI) Update(txId string, workspace string, path string, data any) error {
	return callVoid("tx_update", []any{txId, workspace, path, data})
}

// UpdateProperty calls the RaisinDB registry method "tx_updateProperty".
func (TxAPI) UpdateProperty(txId string, workspace string, nodePath string, propertyPath string, value any) error {
	return callVoid("tx_updateProperty", []any{txId, workspace, nodePath, propertyPath, value})
}

// Upsert calls the RaisinDB registry method "tx_upsert".
func (TxAPI) Upsert(txId string, workspace string, data any) error {
	return callVoid("tx_upsert", []any{txId, workspace, data})
}

// UpsertDeep calls the RaisinDB registry method "tx_upsertDeep".
func (TxAPI) UpsertDeep(txId string, workspace string, data any, parentNodeType string) error {
	return callVoid("tx_upsertDeep", []any{txId, workspace, data, parentNodeType})
}

