// SPDX-License-Identifier: BSL-1.1
//
// RaisinDB - Git-like hierarchical multi model database
// Copyright (C) 2019-2025 SOLUTAS GmbH, Switzerland

//! JavaScript environment setup for the QuickJS runtime.
//!
//! Sets up the complete raisin API:
//! - `__raisin_call` — the registry gateway (see `gateway.rs`); every
//!   `raisin.*` method dispatches through the shared bindings registry, the
//!   same single-definition-per-method registry the Starlark runtime uses.
//! - `__raisin_internal` — the few genuinely runtime-local host functions
//!   (per-execution temp files, W3C fetch plumbing).
//! - `api_wrapper.js` — the public `globalThis.raisin` surface (per-method
//!   error conventions, `Resource` class, transactions, admin escalation).

use rquickjs::{Ctx, Object, Value};
use std::sync::{Arc, Mutex};

use crate::api::FunctionApi;
use crate::runtime::fetch::{AbortRegistry, StreamRegistry, FETCH_POLYFILL};
use crate::runtime::timers::{TimerRegistry, TIMERS_POLYFILL};
use crate::types::LogEntry;

use super::api_fetch::register_fetch_internal;
use super::api_temp::register_temp_internal;
use super::console::{create_console_api, setup_timers_api};
use super::gateway::{register_plugin_gateway, register_registry_gateway};

/// Setup the JavaScript environment with the raisin API.
///
/// This provides the full raisin API including:
/// - raisin.context (execution context)
/// - raisin.nodes (node operations)
/// - raisin.sql (SQL queries)
/// - raisin.http (HTTP requests)
/// - raisin.events (event emission)
/// - console (logging with capture)
/// - W3C Fetch API (fetch, Request, Response, Headers, etc.)
pub(super) fn setup_js_environment<'js>(
    ctx: &Ctx<'js>,
    logs: Arc<Mutex<Vec<LogEntry>>>,
    context_data: &serde_json::Value,
    api: Arc<dyn FunctionApi>,
    log_emitter: Option<raisin_storage::LogEmitter>,
) -> std::result::Result<(), rquickjs::Error> {
    let globals = ctx.globals();

    // Create shared registries for fetch API
    let abort_registry = Arc::new(AbortRegistry::new());
    let stream_registry = Arc::new(StreamRegistry::new());

    // Create timer registry for setTimeout/setInterval
    let timer_registry = Arc::new(TimerRegistry::new());

    // Each step names itself on failure.
    //
    // `rquickjs` renders every failure here as `Error::Exception`, whose Display
    // is the fixed string "Exception generated by QuickJS" — and when QuickJS is
    // in an exception STATE without an exception OBJECT (an allocation failure
    // against the runtime's memory limit, a stack overflow, an internal error)
    // even `ctx.catch()` yields nothing to print. A caller then learns only that
    // "something in setup threw", which has now cost two investigations.
    //
    // `step` is what turns that into an answer. It costs a `&str` per call.
    let step = |name: &'static str, r: std::result::Result<(), rquickjs::Error>| {
        if let Err(e) = &r {
            tracing::error!(
                step = name,
                error = %e,
                "JS environment setup failed at this step"
            );
        }
        r
    };

    // Setup the raisin API (registry gateway + runtime-local host fns + JS wrapper)
    step(
        "setup_raisin_api",
        setup_raisin_api(
            ctx,
            api.clone(),
            abort_registry.clone(),
            stream_registry.clone(),
        ),
    )?;

    // Setup timer APIs (setTimeout, clearTimeout, setInterval, clearInterval)
    step("setup_timers_api", setup_timers_api(ctx, timer_registry))?;

    // Add context as a read-only property on the raisin object.
    //
    // The byte length is logged because this is the ONLY step whose cost scales
    // with its input: `context_data` carries the whole function input, which for
    // an adapter call includes the mount config and its state. A parse that
    // fails here is far more likely to be an allocation failure on a large blob
    // than a malformed one, and the size is the difference between those two
    // readings.
    let context_json = serde_json::to_string(context_data).unwrap_or("{}".to_string());
    let context_len = context_json.len();
    let context_bytes: Vec<u8> = context_json.into_bytes();
    let context_val: Value = match ctx.json_parse(context_bytes) {
        Ok(value) => value,
        Err(e) => {
            tracing::error!(
                step = "json_parse(context)",
                context_bytes = context_len,
                error = %e,
                "JS environment setup failed parsing the function context"
            );
            return Err(e);
        }
    };

    // Get the raisin object that was created by setup_raisin_api
    let raisin: Object = match globals.get("raisin") {
        Ok(object) => object,
        Err(e) => {
            tracing::error!(step = "globals.get(raisin)", error = %e, "JS environment setup failed");
            return Err(e);
        }
    };
    step("raisin.set(context)", raisin.set("context", context_val))?;

    // Create console object with log capture and real-time streaming
    let console = match create_console_api(ctx, logs, log_emitter) {
        Ok(console) => console,
        Err(e) => {
            tracing::error!(step = "create_console_api", error = %e, "JS environment setup failed");
            return Err(e);
        }
    };
    step("globals.set(console)", globals.set("console", console))?;

    // Setup W3C Fetch API by evaluating the JavaScript polyfill
    // This creates: fetch, Request, Response, Headers, ReadableStream,
    // AbortController, AbortSignal, FormData, DOMException
    step(
        "eval(fetch polyfill)",
        ctx.eval::<(), _>(FETCH_POLYFILL.as_bytes().to_vec()),
    )?;

    // Setup timer APIs by evaluating JavaScript polyfill
    // This creates: setTimeout, clearTimeout, setInterval, clearInterval
    step(
        "eval(timers polyfill)",
        ctx.eval::<(), _>(TIMERS_POLYFILL.as_bytes().to_vec()),
    )?;

    Ok(())
}

/// Register the registry gateway plus the runtime-local internal functions,
/// then evaluate the JS wrapper code that creates the public API.
fn setup_raisin_api<'js>(
    ctx: &Ctx<'js>,
    api: Arc<dyn FunctionApi>,
    abort_registry: Arc<AbortRegistry>,
    stream_registry: Arc<StreamRegistry>,
) -> std::result::Result<(), rquickjs::Error> {
    let globals = ctx.globals();

    // The single dispatch point for all raisin.* API methods: looks the
    // method up in the shared bindings registry and runs its invoker.
    register_registry_gateway(ctx, api.clone())?;

    // Gateway for function-binding plugin methods (raisin.<ns>.*). Routes to
    // FunctionApi::plugin_call, bypassing the registry. A no-op at the JS level
    // when no plugins are registered (nothing calls it).
    register_plugin_gateway(ctx, api.clone())?;

    // Internal namespace for the runtime-local host functions that cannot be
    // expressed as registry invokers (they bind per-execution state, not
    // FunctionApi): temp files and the W3C fetch plumbing.
    let internal = Object::new(ctx.clone())?;
    register_temp_internal(ctx, &internal)?;
    register_fetch_internal(ctx, &internal, api, abort_registry, stream_registry)?;
    globals.set("__raisin_internal", internal)?;

    // Evaluate JS code that creates the public API with JSON parsing, then the
    // registered function-binding plugins' snippets (empty in public builds).
    ctx.eval::<(), _>(api_wrapper_source().clone())?;

    Ok(())
}

/// The API wrapper concatenated with the plugin snippets, assembled once.
///
/// A fresh `AsyncContext` per execution is deliberate tenant isolation, so the
/// ~41 KB wrapper genuinely must be evaluated each time — but it does not need
/// to be *rebuilt* each time. This used to allocate a fresh `String`, copy the
/// whole wrapper into it and re-run plugin assembly on every single execution.
///
/// Plugins register during startup, before any function runs, so capturing them
/// on first use is safe. `Ctx::eval` takes `impl Into<Vec<u8>>` and so still
/// copies once — that copy is imposed by rquickjs and cannot be elided here.
fn api_wrapper_source() -> &'static Vec<u8> {
    static SRC: std::sync::LazyLock<Vec<u8>> = std::sync::LazyLock::new(|| {
        let mut src = String::with_capacity(API_WRAPPER_JS.len() + 1024);
        src.push_str(API_WRAPPER_JS);
        src.push_str(&crate::plugin::assemble_plugin_js());
        src.into_bytes()
    });
    &SRC
}

/// JavaScript source that creates the public `globalThis.raisin` API.
///
/// This wraps `__raisin_call` (registry dispatch, JSON-string results) into a
/// developer-friendly API with parsed return values, per-method error
/// conventions, the Resource class, transaction support, and admin escalation.
const API_WRAPPER_JS: &str = include_str!("api_wrapper.js");
