// SPDX-License-Identifier: BSL-1.1

//! CRUD handlers for node operations: create, update, delete, get.

use chrono::Utc;
use parking_lot::RwLock;
use raisin_core::sanitize_name;
use raisin_models::nodes::properties::PropertyValue;
use raisin_models::nodes::Node;
use raisin_storage::transactional::TransactionalStorage;
use std::collections::HashMap;
use std::sync::Arc;

use crate::{
    connection::ConnectionState,
    error::WsError,
    handler::WsState,
    protocol::{
        NodeCreatePayload, NodeDeletePayload, NodeGetPayload, NodeUpdatePayload, RequestEnvelope,
        ResponseEnvelope,
    },
};

use super::helpers::{build_node_service, extract_context, json_to_property_value};

/// Handle node creation
pub async fn handle_node_create<S, B>(
    state: &Arc<WsState<S, B>>,
    connection_state: &Arc<RwLock<ConnectionState>>,
    request: RequestEnvelope,
) -> Result<Option<ResponseEnvelope>, WsError>
where
    S: raisin_storage::Storage + TransactionalStorage,
    B: raisin_binary::BinaryStorage,
{
    let payload: NodeCreatePayload = serde_json::from_value(request.payload.clone())?;
    let ctx = extract_context(&request)?;
    let node_service = build_node_service(state, connection_state, &ctx);

    // Extract parent path from the full path
    // For example: "/posts/my-post" -> parent_path="/posts", name="my-post"
    //              "/my-post" -> parent_path="/", name="my-post"
    let (parent_path, node_name) = if let Some(idx) = payload.path.rfind('/') {
        let parent = &payload.path[..idx];
        let name = &payload.path[idx + 1..];
        (if parent.is_empty() { "/" } else { parent }, name)
    } else {
        ("/", payload.path.as_str())
    };

    // Sanitize the node name to keep consistency with non-transactional creates
    let clean_name = sanitize_name(node_name).map_err(|err| {
        WsError::InvalidRequest(format!("Invalid node name '{}': {}", node_name, err))
    })?;

    // Generate a unique ID for the new node
    let node_id = uuid::Uuid::new_v4().to_string();

    // Convert properties from HashMap<String, serde_json::Value> to HashMap<String, PropertyValue>
    let properties: HashMap<String, PropertyValue> = payload
        .properties
        .into_iter()
        .map(|(k, v)| (k, json_to_property_value(&v)))
        .collect();

    // Build the node from payload
    let mut node = Node {
        id: node_id.clone(),
        name: clean_name.clone(),
        path: String::new(), // Will be auto-generated by add_node or set for transactions
        node_type: payload.node_type,
        archetype: None,
        properties,
        children: vec![],
        order_key: String::new(), // Will be assigned by add_node
        has_children: None,
        parent: None, // Will be auto-derived by storage layer from path
        version: 1,
        created_at: None, // Will be set by add_node
        updated_at: None, // Will be set by add_node
        published_at: None,
        published_by: None,
        updated_by: None,
        created_by: None,
        translations: None,
        tenant_id: Some(ctx.tenant_id.to_string()),
        workspace: Some(ctx.workspace.to_string()),
        owner_id: None,
        relations: vec![],
    };

    // Set full path (used directly for transactional context; overwritten for non-transactional)
    let full_path = if parent_path == "/" || parent_path.is_empty() {
        format!("/{}", clean_name)
    } else {
        format!("{}/{}", parent_path, clean_name)
    };
    node.path = full_path.clone();
    node.parent = Node::extract_parent_name_from_path(&full_path);

    // Ensure timestamps exist so transactional adds persist metadata
    let now = Utc::now();
    if node.created_at.is_none() {
        node.created_at = Some(now);
    }
    if node.updated_at.is_none() {
        node.updated_at = Some(now);
    }

    // If content is provided, add it to properties
    if let Some(content) = payload.content {
        node.properties
            .insert("content".to_string(), json_to_property_value(&content));
    }

    // Check if there's an active transaction in the connection state
    // If so, use the transaction context instead of direct NodeService
    let tx_arc_opt = {
        let connection_guard = connection_state.read();
        connection_guard.get_transaction_context()
    }; // Guard is dropped here, before any await

    let created_node = if let Some(tx_ctx) = tx_arc_opt {
        // Use transaction context to create the node
        // Use add_node for create operations (optimized, skips existence checks)
        tx_ctx.add_node(ctx.workspace, &node).await?;
        node
    } else {
        // No active transaction, use regular NodeService with add_node
        // This will validate the NodeType, parent, properties, and publish events centrally
        node_service.add_node(parent_path, node).await?
    };

    Ok(Some(ResponseEnvelope::success(
        request.request_id,
        serde_json::to_value(created_node)?,
    )))
}

/// Handle node update
pub async fn handle_node_update<S, B>(
    state: &Arc<WsState<S, B>>,
    connection_state: &Arc<RwLock<ConnectionState>>,
    request: RequestEnvelope,
) -> Result<Option<ResponseEnvelope>, WsError>
where
    S: raisin_storage::Storage + TransactionalStorage,
    B: raisin_binary::BinaryStorage,
{
    let payload: NodeUpdatePayload = serde_json::from_value(request.payload.clone())?;
    let ctx = extract_context(&request)?;
    let node_service = build_node_service(state, connection_state, &ctx);

    // Get the existing node
    let mut node = node_service
        .get(&payload.node_id)
        .await?
        .ok_or_else(|| WsError::InvalidRequest(format!("Node not found: {}", payload.node_id)))?;

    // Update properties - convert from JSON to PropertyValue
    for (key, value) in payload.properties {
        node.properties.insert(key, json_to_property_value(&value));
    }

    // Update content if provided
    if let Some(content) = payload.content {
        node.properties
            .insert("content".to_string(), json_to_property_value(&content));
    }

    // Update timestamp
    node.updated_at = Some(chrono::Utc::now());

    // Save the updated node
    node_service.update_node(node.clone()).await?;

    Ok(Some(ResponseEnvelope::success(
        request.request_id,
        serde_json::to_value(node)?,
    )))
}

/// Handle node deletion
pub async fn handle_node_delete<S, B>(
    state: &Arc<WsState<S, B>>,
    connection_state: &Arc<RwLock<ConnectionState>>,
    request: RequestEnvelope,
) -> Result<Option<ResponseEnvelope>, WsError>
where
    S: raisin_storage::Storage + TransactionalStorage,
    B: raisin_binary::BinaryStorage,
{
    let payload: NodeDeletePayload = serde_json::from_value(request.payload.clone())?;
    let ctx = extract_context(&request)?;
    let node_service = build_node_service(state, connection_state, &ctx);

    // Delete the node
    let deleted = node_service.delete(&payload.node_id).await?;

    Ok(Some(ResponseEnvelope::success(
        request.request_id,
        serde_json::json!({ "deleted": deleted }),
    )))
}

/// Handle node get
pub async fn handle_node_get<S, B>(
    state: &Arc<WsState<S, B>>,
    connection_state: &Arc<RwLock<ConnectionState>>,
    request: RequestEnvelope,
) -> Result<Option<ResponseEnvelope>, WsError>
where
    S: raisin_storage::Storage + TransactionalStorage,
    B: raisin_binary::BinaryStorage,
{
    let payload: NodeGetPayload = serde_json::from_value(request.payload.clone())?;
    let ctx = extract_context(&request)?;
    let node_service = build_node_service(state, connection_state, &ctx);

    // Get the node
    let node = node_service.get(&payload.node_id).await?;

    Ok(Some(ResponseEnvelope::success(
        request.request_id,
        serde_json::to_value(node)?,
    )))
}
