// Code generated by `cargo run -p raisin-functions --bin gen-bindings`.
// DO NOT EDIT — edit `crates/raisin-functions/src/runtime/bindings/` and
// re-run `make gen-bindings` instead.

import { call } from "./abi";

// --- JSON argument helpers -------------------------------------------------
// AssemblyScript ships no JSON encoder, so the few shapes the gateway needs
// are built here rather than pulling a library into every artifact.

function jsonString(s: string): string {
  let out = "\"";
  for (let i = 0; i < s.length; i++) {
    const c = s.charCodeAt(i);
    if (c == 0x22) out += "\\\"";
    else if (c == 0x5c) out += "\\\\";
    else if (c == 0x0a) out += "\\n";
    else if (c == 0x0d) out += "\\r";
    else if (c == 0x09) out += "\\t";
    else if (c < 0x20) out += "\\u" + c.toString(16).padStart(4, "0");
    else out += String.fromCharCode(c);
  }
  return out + "\"";
}

function jsonStringOrNull(s: string | null): string {
  return s == null ? "null" : jsonString(s!);
}

function jsonStringArray(items: string[]): string {
  let out = "[";
  for (let i = 0; i < items.length; i++) {
    if (i > 0) out += ",";
    out += jsonString(items[i]);
  }
  return out + "]";
}

function argsOf(parts: string[]): string {
  let out = "[";
  for (let i = 0; i < parts.length; i++) {
    if (i > 0) out += ",";
    out += parts[i];
  }
  return out + "]";
}

export namespace admin {
export namespace nodes {
  /** `raisin.admin.nodes.create` — registry method `admin_nodes_create`. Returns raw JSON. */
  export function create(workspace: string, parentPath: string, data: string): string {
    return call("admin_nodes_create", argsOf([jsonString(workspace), jsonString(parentPath), data]));
  }

  /** `raisin.admin.nodes.delete` — registry method `admin_nodes_delete`. Returns raw JSON. */
  export function delete_(workspace: string, path: string): string {
    return call("admin_nodes_delete", argsOf([jsonString(workspace), jsonString(path)]));
  }

  /** `raisin.admin.nodes.get` — registry method `admin_nodes_get`. Returns raw JSON. */
  export function get(workspace: string, path: string): string {
    return call("admin_nodes_get", argsOf([jsonString(workspace), jsonString(path)]));
  }

  /** `raisin.admin.nodes.getById` — registry method `admin_nodes_getById`. Returns raw JSON. */
  export function getById(workspace: string, id: string): string {
    return call("admin_nodes_getById", argsOf([jsonString(workspace), jsonString(id)]));
  }

  /** `raisin.admin.nodes.getChildren` — registry method `admin_nodes_getChildren`. Returns raw JSON. */
  export function getChildren(workspace: string, parentPath: string, limit: i64): string {
    return call("admin_nodes_getChildren", argsOf([jsonString(workspace), jsonString(parentPath), (limit < 0 ? "null" : limit.toString())]));
  }

  /** `raisin.admin.nodes.query` — registry method `admin_nodes_query`. Returns raw JSON. */
  export function query(workspace: string, query: string): string {
    return call("admin_nodes_query", argsOf([jsonString(workspace), query]));
  }

  /** `raisin.admin.nodes.update` — registry method `admin_nodes_update`. Returns raw JSON. */
  export function update(workspace: string, path: string, data: string): string {
    return call("admin_nodes_update", argsOf([jsonString(workspace), jsonString(path), data]));
  }

  /** `raisin.admin.nodes.updateProperty` — registry method `admin_nodes_updateProperty`. Returns raw JSON. */
  export function updateProperty(workspace: string, nodePath: string, propertyPath: string, value: string): string {
    return call("admin_nodes_updateProperty", argsOf([jsonString(workspace), jsonString(nodePath), jsonString(propertyPath), value]));
  }

}
}

export namespace admin {
export namespace sql {
  /** `raisin.admin.sql.execute` — registry method `admin_sql_execute`. Returns raw JSON. */
  export function execute(sql: string, params: string): string {
    return call("admin_sql_execute", argsOf([jsonString(sql), params]));
  }

  /** `raisin.admin.sql.query` — registry method `admin_sql_query`. Returns raw JSON. */
  export function query(sql: string, params: string): string {
    return call("admin_sql_query", argsOf([jsonString(sql), params]));
  }

}
}

export namespace ai {
  /** `raisin.ai.completion` — registry method `ai_completion`. Returns raw JSON. */
  export function completion(request: string): string {
    return call("ai_completion", argsOf([request]));
  }

  /** `raisin.ai.embed` — registry method `ai_embed`. Returns raw JSON. */
  export function embed(request: string): string {
    return call("ai_embed", argsOf([request]));
  }

  /** `raisin.ai.getDefaultModel` — registry method `ai_getDefaultModel`. Returns raw JSON. */
  export function getDefaultModel(useCase: string): string {
    return call("ai_getDefaultModel", argsOf([jsonString(useCase)]));
  }

  /** `raisin.ai.listModels` — registry method `ai_listModels`. Returns raw JSON. */
  export function listModels(): string {
    return call("ai_listModels", "[]");
  }

  /** `raisin.ai.listProviders` — registry method `ai_listProviders`. Returns raw JSON. */
  export function listProviders(): string {
    return call("ai_listProviders", "[]");
  }

}

export namespace assets {
  /** `raisin.assets.ensureContent` — registry method `asset_ensure_content`. Returns raw JSON. */
  export function ensureContent(workspace: string, nodeRef: string): string {
    return call("asset_ensure_content", argsOf([jsonString(workspace), jsonString(nodeRef)]));
  }

  /** `raisin.assets.reextract` — registry method `asset_reextract`. Returns raw JSON. */
  export function reextract(workspace: string, nodeRef: string): string {
    return call("asset_reextract", argsOf([jsonString(workspace), jsonString(nodeRef)]));
  }

  /** `raisin.assets.setExtractedText` — registry method `asset_set_extraction`. Returns raw JSON. */
  export function setExtractedText(workspace: string, nodeRef: string, text: string, options: string): string {
    return call("asset_set_extraction", argsOf([jsonString(workspace), jsonString(nodeRef), jsonString(text), options]));
  }

  /** `raisin.assets.signedUrl` — registry method `asset_signed_url`. Returns raw JSON. */
  export function signedUrl(workspace: string, nodeRef: string, options: string): string {
    return call("asset_signed_url", argsOf([jsonString(workspace), jsonString(nodeRef), options]));
  }

}

export namespace branches {
  /** `raisin.branches.compare` — registry method `branches_compare`. Returns raw JSON. */
  export function compare(branch: string, baseBranch: string): string {
    return call("branches_compare", argsOf([jsonString(branch), jsonString(baseBranch)]));
  }

  /** `raisin.branches.copyNodes` — registry method `branches_copyNodes`. Returns raw JSON. */
  export function copyNodes(sourceBranch: string, targetBranch: string, opts: string): string {
    return call("branches_copyNodes", argsOf([jsonString(sourceBranch), jsonString(targetBranch), opts]));
  }

  /** `raisin.branches.diff` — registry method `branches_diff`. Returns raw JSON. */
  export function diff(branch: string, baseBranch: string): string {
    return call("branches_diff", argsOf([jsonString(branch), jsonString(baseBranch)]));
  }

}

export namespace crypto {
  /** `raisin.crypto.generateKeyPair` — registry method `crypto_generate_key_pair`. Returns raw JSON. */
  export function generateKeyPair(alg: string | null): string {
    return call("crypto_generate_key_pair", argsOf([jsonStringOrNull(alg)]));
  }

  /** `raisin.crypto.hash` — registry method `crypto_hash`. Returns raw JSON. */
  export function hash(input: string, alg: string | null): string {
    return call("crypto_hash", argsOf([jsonString(input), jsonStringOrNull(alg)]));
  }

  /** `raisin.crypto.randomBytes` — registry method `crypto_random_bytes`. Returns raw JSON. */
  export function randomBytes(n: u32): string {
    return call("crypto_random_bytes", argsOf([n.toString()]));
  }

  /** `raisin.crypto.signJwt` — registry method `crypto_sign_jwt`. Returns raw JSON. */
  export function signJwt(claims: string, private_jwk: string, opts: string | null): string {
    return call("crypto_sign_jwt", argsOf([claims, private_jwk, (opts == null ? "null" : opts!)]));
  }

  /** `raisin.crypto.uuid` — registry method `crypto_uuid`. Returns raw JSON. */
  export function uuid(): string {
    return call("crypto_uuid", "[]");
  }

  /** `raisin.crypto.verifyJwt` — registry method `crypto_verify_jwt`. Returns raw JSON. */
  export function verifyJwt(token: string, opts: string | null): string {
    return call("crypto_verify_jwt", argsOf([jsonString(token), (opts == null ? "null" : opts!)]));
  }

}

export namespace date {
  /** `raisin.date.addDays` — registry method `date_addDays`. Returns raw JSON. */
  export function addDays(timestamp: i64, days: i64): string {
    return call("date_addDays", argsOf([timestamp.toString(), days.toString()]));
  }

  /** `raisin.date.diffDays` — registry method `date_diffDays`. Returns raw JSON. */
  export function diffDays(ts1: i64, ts2: i64): string {
    return call("date_diffDays", argsOf([ts1.toString(), ts2.toString()]));
  }

  /** `raisin.date.format` — registry method `date_format`. Returns raw JSON. */
  export function format(timestamp: i64, format: string | null): string {
    return call("date_format", argsOf([timestamp.toString(), jsonStringOrNull(format)]));
  }

  /** `raisin.date.now` — registry method `date_now`. Returns raw JSON. */
  export function now(): string {
    return call("date_now", "[]");
  }

  /** `raisin.date.parse` — registry method `date_parse`. Returns raw JSON. */
  export function parse(dateStr: string, format: string | null): string {
    return call("date_parse", argsOf([jsonString(dateStr), jsonStringOrNull(format)]));
  }

  /** `raisin.date.timestamp` — registry method `date_timestamp`. Returns raw JSON. */
  export function timestamp(): string {
    return call("date_timestamp", "[]");
  }

  /** `raisin.date.timestampMillis` — registry method `date_timestampMillis`. Returns raw JSON. */
  export function timestampMillis(): string {
    return call("date_timestampMillis", "[]");
  }

}

export namespace email {
  /** `raisin.email.providers` — registry method `email_providers`. Returns raw JSON. */
  export function providers(): string {
    return call("email_providers", "[]");
  }

  /** `raisin.email.send` — registry method `email_send`. Returns raw JSON. */
  export function send(message: string): string {
    return call("email_send", argsOf([message]));
  }

}

export namespace events {
  /** `raisin.events.emit` — registry method `events_emit`. Returns raw JSON. */
  export function emit(eventType: string, data: string): string {
    return call("events_emit", argsOf([jsonString(eventType), data]));
  }

}

export namespace flows {
  /** `raisin.flows.run` — registry method `flows_run`. Returns raw JSON. */
  export function run(flowPath: string, input: string): string {
    return call("flows_run", argsOf([jsonString(flowPath), input]));
  }

}

export namespace functions {
  /** `raisin.functions.call` — registry method `functions_call`. Returns raw JSON. */
  export function call(functionPath: string, arguments: string): string {
    return call("functions_call", argsOf([jsonString(functionPath), arguments]));
  }

  /** `raisin.functions.execute` — registry method `functions_execute`. Returns raw JSON. */
  export function execute(functionPath: string, arguments: string, context: string): string {
    return call("functions_execute", argsOf([jsonString(functionPath), arguments, context]));
  }

}

export namespace http {
  /** `raisin.http.request` — registry method `http_request`. Returns raw JSON. */
  export function request(method: string, url: string, options: string): string {
    return call("http_request", argsOf([jsonString(method), jsonString(url), options]));
  }

}

export namespace identities {
  /** `raisin.identities.findByEmail` — registry method `identities_findByEmail`. Returns raw JSON. */
  export function findByEmail(email: string): string {
    return call("identities_findByEmail", argsOf([jsonString(email)]));
  }

  /** `raisin.identities.update` — registry method `identities_update`. Returns raw JSON. */
  export function update(id: string, patch: string): string {
    return call("identities_update", argsOf([jsonString(id), patch]));
  }

}

export namespace imap {
  /** `raisin.imap.fetchMessage` — registry method `imap_fetch_message`. Returns raw JSON. */
  export function fetchMessage(conn: string, uid: i64, opts: string | null): string {
    return call("imap_fetch_message", argsOf([conn, uid.toString(), (opts == null ? "null" : opts!)]));
  }

  /** `raisin.imap.fetchSince` — registry method `imap_fetch_since`. Returns raw JSON. */
  export function fetchSince(conn: string, sinceUid: i64, opts: string | null): string {
    return call("imap_fetch_since", argsOf([conn, sinceUid.toString(), (opts == null ? "null" : opts!)]));
  }

  /** `raisin.imap.listMailboxes` — registry method `imap_list_mailboxes`. Returns raw JSON. */
  export function listMailboxes(conn: string): string {
    return call("imap_list_mailboxes", argsOf([conn]));
  }

}

export namespace integrations {
  /** `raisin.integrations.syncNow` — registry method `integrations_sync_now`. Returns raw JSON. */
  export function syncNow(mountId: string, mode: string | null): string {
    return call("integrations_sync_now", argsOf([jsonString(mountId), jsonStringOrNull(mode)]));
  }

}

export namespace inventory {
  /** `raisin.inventory.claim` — registry method `inventory_claim`. Returns raw JSON. */
  export function claim(pool: string, n: i64, capacity: i64): string {
    return call("inventory_claim", argsOf([jsonString(pool), n.toString(), capacity.toString()]));
  }

  /** `raisin.inventory.release` — registry method `inventory_release`. Returns raw JSON. */
  export function release(pool: string, n: i64): string {
    return call("inventory_release", argsOf([jsonString(pool), n.toString()]));
  }

}

export namespace locks {
  /** `raisin.locks.acquire` — registry method `locks_acquire`. Returns raw JSON. */
  export function acquire(key: string, ttlMs: i64, owner: string | null): string {
    return call("locks_acquire", argsOf([jsonString(key), ttlMs.toString(), jsonStringOrNull(owner)]));
  }

  /** `raisin.locks.release` — registry method `locks_release`. Returns raw JSON. */
  export function release(key: string, token: i64): string {
    return call("locks_release", argsOf([jsonString(key), token.toString()]));
  }

  /** `raisin.locks.renew` — registry method `locks_renew`. Returns raw JSON. */
  export function renew(key: string, token: i64, ttlMs: i64): string {
    return call("locks_renew", argsOf([jsonString(key), token.toString(), ttlMs.toString()]));
  }

}

export namespace nodes {
  /** `raisin.nodes.addResource` — registry method `nodes_addResource`. Returns raw JSON. */
  export function addResource(workspace: string, nodePath: string, propertyPath: string, uploadData: string): string {
    return call("nodes_addResource", argsOf([jsonString(workspace), jsonString(nodePath), jsonString(propertyPath), uploadData]));
  }

  /** `raisin.nodes.applyChildOrder` — registry method `nodes_applyChildOrder`. Returns raw JSON. */
  export function applyChildOrder(workspace: string, parentPath: string, sourceBranch: string, targetBranch: string): string {
    return call("nodes_applyChildOrder", argsOf([jsonString(workspace), jsonString(parentPath), jsonString(sourceBranch), jsonString(targetBranch)]));
  }

  /** `raisin.nodes.create` — registry method `nodes_create`. Returns raw JSON. */
  export function create(workspace: string, parentPath: string, data: string): string {
    return call("nodes_create", argsOf([jsonString(workspace), jsonString(parentPath), data]));
  }

  /** `raisin.nodes.delete` — registry method `nodes_delete`. Returns raw JSON. */
  export function delete_(workspace: string, path: string): string {
    return call("nodes_delete", argsOf([jsonString(workspace), jsonString(path)]));
  }

  /** `raisin.nodes.get` — registry method `nodes_get`. Returns raw JSON. */
  export function get(workspace: string, path: string): string {
    return call("nodes_get", argsOf([jsonString(workspace), jsonString(path)]));
  }

  /** `raisin.nodes.getById` — registry method `nodes_getById`. Returns raw JSON. */
  export function getById(workspace: string, id: string): string {
    return call("nodes_getById", argsOf([jsonString(workspace), jsonString(id)]));
  }

  /** `raisin.nodes.getChildren` — registry method `nodes_getChildren`. Returns raw JSON. */
  export function getChildren(workspace: string, parentPath: string, limit: i64): string {
    return call("nodes_getChildren", argsOf([jsonString(workspace), jsonString(parentPath), (limit < 0 ? "null" : limit.toString())]));
  }

  /** `raisin.nodes.history` — registry method `nodes_history`. Returns raw JSON. */
  export function history(workspace: string, id: string, limit: i64): string {
    return call("nodes_history", argsOf([jsonString(workspace), jsonString(id), (limit < 0 ? "null" : limit.toString())]));
  }

  /** `raisin.nodes.move` — registry method `nodes_move`. Returns raw JSON. */
  export function move(workspace: string, nodePath: string, newParentPath: string): string {
    return call("nodes_move", argsOf([jsonString(workspace), jsonString(nodePath), jsonString(newParentPath)]));
  }

  /** `raisin.nodes.moveChildAfter` — registry method `nodes_moveChildAfter`. Returns raw JSON. */
  export function moveChildAfter(workspace: string, parentPath: string, childName: string, afterChildName: string): string {
    return call("nodes_moveChildAfter", argsOf([jsonString(workspace), jsonString(parentPath), jsonString(childName), jsonString(afterChildName)]));
  }

  /** `raisin.nodes.moveChildBefore` — registry method `nodes_moveChildBefore`. Returns raw JSON. */
  export function moveChildBefore(workspace: string, parentPath: string, childName: string, beforeChildName: string): string {
    return call("nodes_moveChildBefore", argsOf([jsonString(workspace), jsonString(parentPath), jsonString(childName), jsonString(beforeChildName)]));
  }

  /** `raisin.nodes.query` — registry method `nodes_query`. Returns raw JSON. */
  export function query(workspace: string, query: string): string {
    return call("nodes_query", argsOf([jsonString(workspace), query]));
  }

  /** `raisin.nodes.reorderChild` — registry method `nodes_reorderChild`. Returns raw JSON. */
  export function reorderChild(workspace: string, parentPath: string, childName: string, position: u32): string {
    return call("nodes_reorderChild", argsOf([jsonString(workspace), jsonString(parentPath), jsonString(childName), position.toString()]));
  }

  /** `raisin.nodes.update` — registry method `nodes_update`. Returns raw JSON. */
  export function update(workspace: string, path: string, data: string): string {
    return call("nodes_update", argsOf([jsonString(workspace), jsonString(path), data]));
  }

  /** `raisin.nodes.updateProperty` — registry method `nodes_updateProperty`. Returns raw JSON. */
  export function updateProperty(workspace: string, nodePath: string, propertyPath: string, value: string): string {
    return call("nodes_updateProperty", argsOf([jsonString(workspace), jsonString(nodePath), jsonString(propertyPath), value]));
  }

}

export namespace notify {
  /** `raisin.notify.notify` — registry method `notify_send`. Returns raw JSON. */
  export function notify(options: string): string {
    return call("notify_send", argsOf([options]));
  }

}

export namespace ocr {
  /** `raisin.ocr.image` — registry method `ocr_image`. Returns raw JSON. */
  export function image(base64Data: string, options: string): string {
    return call("ocr_image", argsOf([jsonString(base64Data), options]));
  }

}

export namespace pdf {
  /** `raisin.pdf.extractText` — registry method `pdf_extractText`. Returns raw JSON. */
  export function extractText(base64Data: string): string {
    return call("pdf_extractText", argsOf([jsonString(base64Data)]));
  }

  /** `raisin.pdf.getPageCount` — registry method `pdf_getPageCount`. Returns raw JSON. */
  export function getPageCount(base64Data: string): string {
    return call("pdf_getPageCount", argsOf([jsonString(base64Data)]));
  }

  /** `raisin.pdf.ocr` — registry method `pdf_ocr`. Returns raw JSON. */
  export function ocr(base64Data: string, options: string): string {
    return call("pdf_ocr", argsOf([jsonString(base64Data), options]));
  }

  /** `raisin.pdf.processFromStorage` — registry method `pdf_processFromStorage`. Returns raw JSON. */
  export function processFromStorage(storageKey: string, options: string): string {
    return call("pdf_processFromStorage", argsOf([jsonString(storageKey), options]));
  }

}

export namespace platform {
  /** `raisin.platform.hook` — registry method `platform_hook`. Returns raw JSON. */
  export function hook(name: string, payload: string): string {
    return call("platform_hook", argsOf([jsonString(name), payload]));
  }

}

export namespace resources {
  /** `raisin.resources.getBinary` — registry method `resources_getBinary`. Returns raw JSON. */
  export function getBinary(storageKey: string): string {
    return call("resources_getBinary", argsOf([jsonString(storageKey)]));
  }

}

export namespace scheduler {
  /** `raisin.scheduler.cancel` — registry method `scheduler_cancel`. Returns raw JSON. */
  export function cancel(jobIdOrKey: string): string {
    return call("scheduler_cancel", argsOf([jsonString(jobIdOrKey)]));
  }

  /** `raisin.scheduler.get` — registry method `scheduler_get`. Returns raw JSON. */
  export function get(jobIdOrKey: string): string {
    return call("scheduler_get", argsOf([jsonString(jobIdOrKey)]));
  }

  /** `raisin.scheduler.list` — registry method `scheduler_list`. Returns raw JSON. */
  export function list(filter: string | null): string {
    return call("scheduler_list", argsOf([(filter == null ? "null" : filter!)]));
  }

  /** `raisin.scheduler.schedule` — registry method `scheduler_schedule`. Returns raw JSON. */
  export function schedule(request: string): string {
    return call("scheduler_schedule", argsOf([request]));
  }

}

export namespace secrets {
  /** `raisin.secrets.delete` — registry method `secrets_delete`. Returns raw JSON. */
  export function delete_(name: string): string {
    return call("secrets_delete", argsOf([jsonString(name)]));
  }

  /** `raisin.secrets.get` — registry method `secrets_get`. Returns raw JSON. */
  export function get(name: string, version: i64): string {
    return call("secrets_get", argsOf([jsonString(name), (version < 0 ? "null" : version.toString())]));
  }

  /** `raisin.secrets.list` — registry method `secrets_list`. Returns raw JSON. */
  export function list(): string {
    return call("secrets_list", "[]");
  }

  /** `raisin.secrets.put` — registry method `secrets_put`. Returns raw JSON. */
  export function put(name: string, value: string): string {
    return call("secrets_put", argsOf([jsonString(name), jsonString(value)]));
  }

  /** `raisin.secrets.resolve` — registry method `secrets_resolve`. Returns raw JSON. */
  export function resolve(value: string): string {
    return call("secrets_resolve", argsOf([jsonString(value)]));
  }

  /** `raisin.secrets.rotate` — registry method `secrets_rotate`. Returns raw JSON. */
  export function rotate(name: string, value: string): string {
    return call("secrets_rotate", argsOf([jsonString(name), jsonString(value)]));
  }

}

export namespace sql {
  /** `raisin.sql.execute` — registry method `sql_execute`. Returns raw JSON. */
  export function execute(sql: string, params: string): string {
    return call("sql_execute", argsOf([jsonString(sql), params]));
  }

  /** `raisin.sql.query` — registry method `sql_query`. Returns raw JSON. */
  export function query(sql: string, params: string): string {
    return call("sql_query", argsOf([jsonString(sql), params]));
  }

}

export namespace tasks {
  /** `raisin.tasks.complete` — registry method `tasks_complete`. Returns raw JSON. */
  export function complete(task_id: string, response: string): string {
    return call("tasks_complete", argsOf([jsonString(task_id), response]));
  }

  /** `raisin.tasks.create` — registry method `tasks_create`. Returns raw JSON. */
  export function create(request: string): string {
    return call("tasks_create", argsOf([request]));
  }

  /** `raisin.tasks.query` — registry method `tasks_query`. Returns raw JSON. */
  export function query(query: string): string {
    return call("tasks_query", argsOf([query]));
  }

  /** `raisin.tasks.update` — registry method `tasks_update`. Returns raw JSON. */
  export function update(task_id: string, updates: string): string {
    return call("tasks_update", argsOf([jsonString(task_id), updates]));
  }

}

export namespace tx {
  /** `raisin.tx.add` — registry method `tx_add`. Returns raw JSON. */
  export function add(txId: string, workspace: string, data: string): string {
    return call("tx_add", argsOf([jsonString(txId), jsonString(workspace), data]));
  }

  /** `raisin.tx.begin` — registry method `tx_begin`. Returns raw JSON. */
  export function begin(): string {
    return call("tx_begin", "[]");
  }

  /** `raisin.tx.commit` — registry method `tx_commit`. Returns raw JSON. */
  export function commit(txId: string): string {
    return call("tx_commit", argsOf([jsonString(txId)]));
  }

  /** `raisin.tx.create` — registry method `tx_create`. Returns raw JSON. */
  export function create(txId: string, workspace: string, parentPath: string, data: string): string {
    return call("tx_create", argsOf([jsonString(txId), jsonString(workspace), jsonString(parentPath), data]));
  }

  /** `raisin.tx.createDeep` — registry method `tx_createDeep`. Returns raw JSON. */
  export function createDeep(txId: string, workspace: string, parentPath: string, data: string, parentNodeType: string): string {
    return call("tx_createDeep", argsOf([jsonString(txId), jsonString(workspace), jsonString(parentPath), data, jsonString(parentNodeType)]));
  }

  /** `raisin.tx.delete` — registry method `tx_delete`. Returns raw JSON. */
  export function delete_(txId: string, workspace: string, path: string): string {
    return call("tx_delete", argsOf([jsonString(txId), jsonString(workspace), jsonString(path)]));
  }

  /** `raisin.tx.deleteById` — registry method `tx_deleteById`. Returns raw JSON. */
  export function deleteById(txId: string, workspace: string, id: string): string {
    return call("tx_deleteById", argsOf([jsonString(txId), jsonString(workspace), jsonString(id)]));
  }

  /** `raisin.tx.get` — registry method `tx_get`. Returns raw JSON. */
  export function get(txId: string, workspace: string, id: string): string {
    return call("tx_get", argsOf([jsonString(txId), jsonString(workspace), jsonString(id)]));
  }

  /** `raisin.tx.getByPath` — registry method `tx_getByPath`. Returns raw JSON. */
  export function getByPath(txId: string, workspace: string, path: string): string {
    return call("tx_getByPath", argsOf([jsonString(txId), jsonString(workspace), jsonString(path)]));
  }

  /** `raisin.tx.listChildren` — registry method `tx_listChildren`. Returns raw JSON. */
  export function listChildren(txId: string, workspace: string, parentPath: string): string {
    return call("tx_listChildren", argsOf([jsonString(txId), jsonString(workspace), jsonString(parentPath)]));
  }

  /** `raisin.tx.move` — registry method `tx_move`. Returns raw JSON. */
  export function move(txId: string, workspace: string, nodePath: string, newParentPath: string): string {
    return call("tx_move", argsOf([jsonString(txId), jsonString(workspace), jsonString(nodePath), jsonString(newParentPath)]));
  }

  /** `raisin.tx.put` — registry method `tx_put`. Returns raw JSON. */
  export function put(txId: string, workspace: string, data: string): string {
    return call("tx_put", argsOf([jsonString(txId), jsonString(workspace), data]));
  }

  /** `raisin.tx.rollback` — registry method `tx_rollback`. Returns raw JSON. */
  export function rollback(txId: string): string {
    return call("tx_rollback", argsOf([jsonString(txId)]));
  }

  /** `raisin.tx.setActor` — registry method `tx_setActor`. Returns raw JSON. */
  export function setActor(txId: string, actor: string): string {
    return call("tx_setActor", argsOf([jsonString(txId), jsonString(actor)]));
  }

  /** `raisin.tx.setMessage` — registry method `tx_setMessage`. Returns raw JSON. */
  export function setMessage(txId: string, message: string): string {
    return call("tx_setMessage", argsOf([jsonString(txId), jsonString(message)]));
  }

  /** `raisin.tx.update` — registry method `tx_update`. Returns raw JSON. */
  export function update(txId: string, workspace: string, path: string, data: string): string {
    return call("tx_update", argsOf([jsonString(txId), jsonString(workspace), jsonString(path), data]));
  }

  /** `raisin.tx.updateProperty` — registry method `tx_updateProperty`. Returns raw JSON. */
  export function updateProperty(txId: string, workspace: string, nodePath: string, propertyPath: string, value: string): string {
    return call("tx_updateProperty", argsOf([jsonString(txId), jsonString(workspace), jsonString(nodePath), jsonString(propertyPath), value]));
  }

  /** `raisin.tx.upsert` — registry method `tx_upsert`. Returns raw JSON. */
  export function upsert(txId: string, workspace: string, data: string): string {
    return call("tx_upsert", argsOf([jsonString(txId), jsonString(workspace), data]));
  }

  /** `raisin.tx.upsertDeep` — registry method `tx_upsertDeep`. Returns raw JSON. */
  export function upsertDeep(txId: string, workspace: string, data: string, parentNodeType: string): string {
    return call("tx_upsertDeep", argsOf([jsonString(txId), jsonString(workspace), data, jsonString(parentNodeType)]));
  }

}

